### ISSUE TITLE
Feature request: Implementation of rotation of Element by an arbitrary angle

### ISSUE THREAD

**Issue by denis60111** [jgraph/mxgraph#1]
_#413849085_
_Application:  diagram.ly, mxGraph JS 1.10.0.5_

Currently, the only way to rotate an element by an arbitrary angle is to use "Arrange" -> "Rotate" menu item. This rotates element by 90 degrees. We would like to be able to rotate an element by an arbitrary angle, both by using a menu item (and some kind of dialog) and by using the same sort of control that Microsoft Ofiice applications use to rotate shapes.

See green handle on the top of the shape (screenshot from Microsoft Word):

!['rotation'](/downloads/denis60111/Images/2012-05-23_1203.png)

**Comment by nieyangyang712** [comment]
"Error: 2: Duplicate ID"？？？
