### ISSUE TITLE
JGraph - Include Pan(hand) Symbol in ToolBar

### ISSUE THREAD

**Issue by subbiah89** [jgraph/mxgraph#101]
I am working based on grapheditor. I want to include Pan (hand) symbol in toolbar. I added the symbol.
We have any existing functionaly for action.js for that click? Please advice

**Comment by davidjgraph** [comment]
For programming questions please submit to Stackoverflow using the mxgraph tag, https://stackoverflow.com/questions/tagged/mxgraph
