### ISSUE TITLE
Make mxGraph available for asynchronous apps

### ISSUE THREAD

**Issue by newlukai** [jgraph/mxgraph#105]
I want to display a process graph with mxGraph. The hierarchical layout perfectly fits my need. Unfortunately, mxGraph uses document.write to manipulate the DOM. This doesn't work in my Polymer app which makes heavy use of asynchronity.

**Comment by davidjgraph** [comment]
Doesn't work specifically how?

**Comment by newlukai** [comment]
Sorry for the very unspecific explanation, I was short in time.

I've written a wrapping custom element whose only purpose is to set the mxBasePath variable and to include the mxClient.js file. This custom element is (HTML-) imported into another custom element which should render a graph.

In Chromes Console the following message is logged multiple times when starting this app: "Failed to execute 'write' on 'Document': It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened.".

**Comment by alderg** [comment]
How did you include the mxClient.js file?

**Comment by stalkerg** [comment]
> mxGraph uses document.write to manipulate the DOM

Really!? Holly crap! Back to 00x?

**Comment by alderg** [comment]
No, we do not use document.write in the production mxClient.js file, only in the development mxClient.js file and this can easily be changed on line 314 in mxClient.js.

**Comment by newlukai** [comment]
I'm so sorry, I really had a dev file in place. Thank you very much, Alder!

But there are still some questions I'm facing using the production version of mxGraph:

1. My first try to get a production version was to `npm install` it. But version 3.7.5 can't be built on my machine because of [issue 83](https://github.com/jgraph/mxgraph/issues/83).
2. Even if `npm install` would work, I can't use it without fürther adaptions. In my app, I've an `app` folder which is delivered to the client by express. Unfortunately, the `node_modules` folder is a sibling of the `app` folder and thus wouldn't make it to the client.
3. So I downloaded a release and copied the files `mxClient.min.js` and `css/common.css` into `app/elements/mxgraph`. A custom component `mxgraph-scripts.html` consists of only two `script` tags, the first one setting `mxBasePath`, the other one pointing to the minified mxClient file. That currently does the trick.
4. In my Polymer scenario, which makes heavy use of custom components and thus `document-fragment`s, I got an error while moving the mouse over the graph. The error was caused by calling `window.getComputedStyle` passing a ´document-fragment` (which is not an `HTMLElement`). According to MDN, passing a non `HTMLElement` object to `getComputedStyle` results in an error. So I modified mxGraph's `getOffset` method to skip the call of `mxUtils.getCurrentStyle` if the current node is not an `HTMLElement`.

I would appreciate to have a proper "installation" of mxGraph. The best solution for me would be to have a bower component (which builds ;) ). Additionally, it would be cool to have a `<jgraph-mxgraph>` custom element.

Regarding the error calling `getComputedStyle` on non `HTMLELements` I could provide a PR fixing `mxUtils.getCurrentStyle`.

**Comment by davidjgraph** [comment]
Please file one ticket per subject.

**Comment by newlukai** [comment]
I would have done this once we discussed the best approach or best-practice. But if you insist:

- [issue 107 (error with document-fragments) ](https://github.com/jgraph/mxgraph/issues/107)
- [issue 108 (Bower component)](https://github.com/jgraph/mxgraph/issues/108)
- [issue 109 (Custom component)](https://github.com/jgraph/mxgraph/issues/109)
