### ISSUE TITLE
Don't call window.getComputedStyle for non-HTMLElement objects

### ISSUE THREAD

**Issue by newlukai** [jgraph/mxgraph#107]
My Polymer app makes heavy use of custom components, which means the introduction of `DocumentFragment`s in the DOM.
While moving the mouse over an graph in such an app, an error is thrown. This error is caused by the fact that `getOffset` calls `mxUtil.getCurrentStyle` which calls `window.getComputedStyle` for the graph container and also all parents of that container. Some of these parents are of type `DocumentFragment`, not `HTMLElement`. According to MDN, passing a non-`HTMLElement` object to `window.getComputedStyle` results in an error.

**Comment by stalkerg** [comment]
I think we should just use https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect I think we should not calc element position by hands for modern browsers.

**Comment by davidjgraph** [comment]
What's a example reproduction case in vanilla JS? Where is the documentation that says not to pass a non HTMLElement?
