### ISSUE TITLE
[Deprecation] Synchronous XMLHttpRequest on the main thread

### ISSUE THREAD

**Issue by stalkerg** [jgraph/mxgraph#111]
I got this message from Chrome:
```
mxClient.js:11045 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
mxXmlRequest.send @ mxClient.js:11045
load @ mxClient.js:3519
add @ mxClient.js:1505
(anonymous) @ mxClient.js:54238
```

**Comment by alderg** [comment]
See grapheditor example (grapheditor/www/index.html lines 83 ff).

**Comment by stalkerg** [comment]
But it's not a solution it is just disable loading default bundle. 
I mean why default behavior and default functionality should be used that deprecation approach?

**Comment by alderg** [comment]
What problem are you trying to solve?

**Comment by stalkerg** [comment]
>What problem are you trying to solve?

warning if I use default bundle. Maybe it's not a big problem but I think you should mark this as a bug and fix in future releases. 
At least for avoid duplicates because users who will find this warning and will try to put issue here.

**Comment by moh223322** [comment]
Iam facing the same issue , alderg I didn't understand your fix the issue.

**Comment by davidjgraph** [comment]
https://github.com/jgraph/mxgraph/blob/master/javascript/examples/grapheditor/www/index.html#L85 onwards demonstrates how to load asynchronsously.

**Comment by mattsrinc** [comment]
How can this be fixed in
https://github.com/jgraph/mxgraph/blob/master/javascript/examples/editors/diagrameditor.html
too?
