### ISSUE TITLE
Encapsulation and provide ES6/AMD modules.

### ISSUE THREAD

**Issue by stalkerg** [jgraph/mxgraph#112]
Approaches and architecture this library from 00x, I suppose see ~50 mx* objects/functions in "window" looks like porn in 2017. You should provide normal isolation modules for async/dynamic load or integrated to Rollup/Webpack. 
For my opinion most quicker way it is drop out your "build system" and porting build process to Rollup.  
With Rollup, you can generate all kind of modules and use perfect ES6 modules inside your project. 

I see here a lot of problems with integration mxGrap into modern frameworks (Polymer, Angular, React...) and all this you can solve by one refactoring. 

I can understand what you do not want to spend time for that, but at least you interested to merge big pull request with JS refactoring? 

Thanks.

**Comment by alderg** [comment]
Agreed. Please fork the repo to avoid breaking existing code.

**Comment by stalkerg** [comment]
> Please fork the repo to avoid breaking existing code.

Sorry, but what do you mean? I anyway can't make any changes or pull request without a fork and I don't have any rights in this repo.

**Comment by davidjgraph** [comment]
i.e. we wouldn't take such a change back into this repo, it needs a new start for such a change. The best idea would be to create an mxgraph17 (or whatever) and try to evolve a fresh project around that.

**Comment by stalkerg** [comment]
ok, thanks for answers.

**Comment by stalkerg** [comment]
For everybody how to want to help can try https://github.com/stalkerg/monstergraph .
In the current state, all modules build by rollup and helloworld is working.

**Comment by javvadisreenu** [comment]
@stalkerg  please help on  latest mxgraph type destinations and TS files or how to get mxgraph objects into angular 4 scope sample projects.

**Comment by stalkerg** [comment]
@javvadisreenu right now it's not possible and you should ask developers. (but we have clear answer I think - never in mxgraph)
If you talk about monstergraph it's possible like a common ES6/AMD module, at least hello world working fine and you can test.
