### ISSUE TITLE
Group shapes problem

### ISSUE THREAD

**Issue by blucobalto** [jgraph/mxgraph#114]
Hi,
I have problems when I use a group. 
After rotation the dimensions and alignment of the shapes is wrong.

Add 2 shape (any - example ellipse and rectangle).
Select these shapes and group.
Rotate with group handle.
Resize group.

Problem:
Selection rectangle does not bound shapes
Strange resize, breaks alignment and preview changes position once mouse up.

This is the same problem in Drawio:
(https://github.com/jgraph/drawio/issues/137)

Thanks a lot,
Blu

**Comment by Fmajor** [comment]
similar problems:

Add 2 shape.
Select these shapes and group.
drop the group into a swimlane object and become its child
resize the swimlane, group size not changed.

also, another bug
if you resize the group by mouse, all children's size are correctly calculated, but if you change it on the right panel
<img width="232" alt="screen shot 2017-12-27 at 6 48 06 pm" src="https://user-images.githubusercontent.com/1620897/34379520-8eff44c2-eb36-11e7-8ac4-25e174820561.png">
 nothing changed.

there must be some bug in the group resize code.

**Comment by zhangml17** [comment]
Same problem, hasn't it been solved yet?
