### ISSUE TITLE
MxGraph Export

### ISSUE THREAD

**Issue by subbiah89** [jgraph/mxgraph#118]
How to export the custom images in diagram canvas using mxgraph xml?
The custom images are not coming in the exported PNG image.

**Comment by sonha** [comment]
I have this exact same problem

**Comment by shyamsdmx** [comment]
+1

**Comment by sonha** [comment]
I solved it !

**Comment by subbiah89** [comment]
Is there any solution. Plz help me

**Comment by shyamsdmx** [comment]
how did u solve it?

**Comment by 21knowledgePHP** [comment]
Please van toi share.. I Have mxgraph but canot export
