### ISSUE TITLE
reload graph from database

### ISSUE THREAD

**Issue by reminoir** [jgraph/mxgraph#119]
i need save xml code in database and reload this 
i use  this code  :
` var xml ='<root><mxCell id="2" value="Hello," vertex="1"><mxGeometry x="20" y="20" width="80" height="30" as="geometry"/></mxCell><mxCell id="3" value="World!" vertex="1"><mxGeometry x="200" y="150" width="80" height="30" as="geometry"/></mxCell><mxCell id="4" value="" edge="1" source="2" target="3"><mxGeometry relative="1" as="geometry"/></mxCell></root>';
                    var doc = mxUtils.parseXml(xml);                  
                    var codec = new mxCodec(doc);
                    var elt = doc.documentElement.firstChild;
                    var cells = [];

                    while (elt != null)
                    {
                        cells.push(codec.decode(elt));
                        elt = elt.nextSibling;
                    }

                    graph.addCells(cells);`

but dont working true

**Comment by davidjgraph** [comment]
Please post developer questions to https://stackoverflow.com/questions/tagged/mxgraph

**Comment by reminoir** [comment]
in stackoverflow don't answer to question
    On Saturday, November 11, 2017, 1:44:13 PM GMT+3:30, David Benson <notifications@github.com> wrote:  
 
 
Closed #119.
