### ISSUE TITLE
Import Function does not work properly

### ISSUE THREAD

**Issue by gabriele92** [jgraph/mxgraph#120]
Import function does not work properly, as it is not able to import layers of an existing diagram.
My workaround:
substitute these lines in Actions.js (this.addAction('import...', [...] )

var children = model.getChildren(model.getChildAt(model.getRoot(), 0));
editor.graph.setSelectionCells(editor.graph.importCells(children));			

with something like this:

editorUi.editor.graph.model.beginUpdate();
try {
                    
                    editorUi.editor.setGraphXml(doc.documentElement);

 }
                catch (e) {
                    console.error(e);
                }
finally {
                    editorUi.editor.graph.model.endUpdate();
}

And this works.
Can you confirm this as a bug?

Thanks in advance,

Gabriele Gaudenzi

**Comment by davidjgraph** [comment]
Yes, here you go.

**Comment by alderg** [comment]
Ciao Gabriele! Thanks for your feedback. I'll be looking at this issue ASAP.

**Comment by gabriele92** [comment]
Thank you very much!

Gabriele

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release. (No thread bumping, please.)
