### ISSUE TITLE
How to customize shapes in grapheditor from Javascript example?

### ISSUE THREAD

**Issue by adamfakrullah** [jgraph/mxgraph#121]
How to change and customize shape wihthin sidebar in grapheditor Javascript example?Hope all of you can help me to solve this problem?

**Comment by davidjgraph** [comment]
What have you tried?

**Comment by adamfakrullah** [comment]
I tried to remove the shapes. for example i try to remove general palette but it failed, can help me how to remove it?

**Comment by gabriele92** [comment]
try to comment out (for example) this line

this.addMiscPalette(false);

on Sidebar.js
