### ISSUE TITLE
GraphEditor calls non-existent isPageLink function when a HTML link is clicked in a cell

### ISSUE THREAD

**Issue by VsevolodGolovanov** [jgraph/mxgraph#126]
```
Graph.prototype.labelLinkClicked = function(state, elt, evt)
{
	var href = elt.getAttribute('href');
	
	if (href != null && !this.isPageLink(href))
	...
```
There is no `isPageLink`.

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.

**Comment by VsevolodGolovanov** [comment]
@alderg, can you explain the intent behind the function please? I defined it in my sources and currently always return false, because otherwise the click event is just suppressed. But I don't the logic. It's called "isPageLink", but the caller (labelLinkClicked) checks that the link is not a PageLink and only then opens it. Why would labelLinkClicked only open not page links? It seems backwards.

**Comment by alderg** [comment]
It's a special type of URL that we handle in a subclass. The name could probably be more generic.
