### ISSUE TITLE
there is no `ChangeGraphBackground` defined

### ISSUE THREAD

**Issue by laoxubuer** [jgraph/mxgraph#130]
![image](https://user-images.githubusercontent.com/7135991/33362189-2e77862c-d516-11e7-83d5-45161674a00f.png)

When I select a background image，there is an error occur.

![image](https://user-images.githubusercontent.com/7135991/33362251-7acb9662-d516-11e7-9d3c-2ddef21705bb.png)

**Comment by alderg** [comment]
Thanks for the report (should be ChangePageSetup). This will be fixed in the next release.
