### ISSUE TITLE
Graph sticking to mouse movement (panning without clicking)

### ISSUE THREAD

**Issue by VsevolodGolovanov** [jgraph/mxgraph#131]
mxGraph 3.7.5.
Can be reproduced in the GraphEditor example in Firefox 57. Does not reproduce in Chrome 62.

Mousedown right button above graph's container, then move the mouse and mouseup above a scrollbar. Now move mouse back onto the container and observe that it pans with the mouse.

If you enable the GraphEditor's chromeless mode, then it's reproducible just by dragging a scrollbar with the left mouse button.

The problem seems to stem from mxPanningHandler listening to mouseup only on graph's container. It should also listen on the document, like mxPanningManager does.

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
