### ISSUE TITLE
mxgraph 3.8.0 not installing via npm

### ISSUE THREAD

**Issue by fingerartur** [jgraph/mxgraph#133]
> $ npm install --save mxgraph
> 
> \> mxgraph@3.8.0 postinstall C:\Users\Artur\Documents\web\sites\dipl\research\angular\node_modules\mxgraph
> \> grunt build
> 
> Loading "Gruntfile.js" tasks...ERROR
> \>\> TypeError: Cannot read property 'map' of null
> Warning: Task "build" not found. Use --force to continue.
> 
> Aborted due to warnings.
> 

probably related to #116 #102 #83

**Comment by laoxubuer** [comment]
I found the same problem
