### ISSUE TITLE
Performance issue in mxSvgCanvas2D

### ISSUE THREAD

**Issue by vietduc1441** [jgraph/mxgraph#140]
We have to change a number of labels for cells in out graph. It is very slow. And when we investigate the performance. It seems that the cause is in mxSvgCanvas2D. 
Especially somewhere near: https://github.com/jgraph/mxgraph/blob/master/javascript/src/js/util/mxSvgCanvas2D.js#L1567

I am thinking that because in the code, it tries to read the offsetWidth of div2 multiple times, during that, there are some change in the layout then cause the reflow of the document.

![pef](https://user-images.githubusercontent.com/3817665/34240573-80fbe884-e60f-11e7-8087-92e9d5cc9142.png)

**Comment by alderg** [comment]
Thanks for the report. We've reduced the number of required reflows and reading offsetWidth to the minimum for the general case. Try optimizing the style instead, eg.
- Is HTML and/or word wrapping needed (see mxGraph.isHtmlLabel/isWrapping)?
- Is clipping acceptable (see mxConstants.STYLE_OVERFLOW)?

**Comment by vietduc1441** [comment]
Thanks. We find a solution to improve it:
- graph.setHtmlLabels(false)
- mxText.prototype.ignoreStringSize = true; //to avoid calling getBBox
