### ISSUE TITLE
Assign vertexes to center

### ISSUE THREAD

**Issue by winlandiano** [jgraph/mxgraph#141]
### What I want:

In my situation I need a simple linear layout in which all vertex are aligned either vertically or horizontally in the center. Yet I didn't found any parameters for this feature. The mxStackLayout may be a solution but it automatically put all elements upper left.

### What I've tried:
I found mxConstants.ALIGN_CENTER for `mxConstants.STYLE_ALIGN` and `STYLE_VERTICAL_ALIGN` yet they seemed to be used for labels). Therefore, no go.

What I've tried next is to use set the calculated distance to left to `margin_left` for each element in the get_layout function, in other words, do it manually. But this is a parent to children behavior, instead of a children to parent behavior(like in Android), which means, all children will have a same `margin_left`. So I made a embedded structure: for example I want a vertically centralized mxStackLayout, I firstly arrange a "anchor" all to the left, define the specific left distance to each of these "anchor", then build the real content as a child vertex to these "anchors". It's a ugly trick but it finally makes everything closer, at least seems to be (the "anchor" can be seen as a green dot lined box slightly to the left of box 1):

![image](https://user-images.githubusercontent.com/5996396/34249277-73876d7a-e639-11e7-83fc-11f0af918a06.png)

### The issure

Is there already any some other method to implement this? It's not a bug nor a failure, just some reasonable requirement not satisfied!

**Comment by alderg** [comment]
To align to the center, there is https://jgraph.github.io/mxgraph/docs/js-api/files/view/mxGraph-js.html#mxGraph.alignCells

**Comment by winlandiano** [comment]
@alderg Thanks for the answer! It seems that when I use layout like mxStackLayout this function won't work, only when I remove the mxLayout will the `this.resizeCell(cells[i], geo)` in mxGraph.js:3622 make effect. Does it mean I can only either centralize or use the advantage that mxLayout brings me?

**Comment by alderg** [comment]
Yes, unless you write your own layout which I'd probably recommend in this case.

**Comment by winlandiano** [comment]
@alderg Everythings' clear. Thanks a lot!
