### ISSUE TITLE
Is this a bug or on purpose?

### ISSUE THREAD

**Issue by lgleim** [jgraph/mxgraph#143]
Could you please clarify whether this is on purpose or a bug?
 If on purpose, would you mind adding another line in the comments with an explanation?
https://github.com/jgraph/mxgraph/blob/3a05b1a3b63be38fb61314784dccb8824536e9fb/javascript/src/js/layout/hierarchical/model/mxSwimlaneModel.js#L173

**Comment by davidjgraph** [comment]
It's just the default. It may not be the best default, but it'd be very hard to change it at this point.

**Comment by lgleim** [comment]
I was rather asking since the mxGraphHierarchyModel.prototype.... default is defined in mxSwimlaneModel.js

**Comment by lgleim** [comment]
Still wondering about this...
