### ISSUE TITLE
Architecture Diagram

### ISSUE THREAD

**Issue by dnskmr** [jgraph/mxgraph#145]
Hi,

I would like to draw the architecture diagram using mxgraph dynamically. can I draw using mxgraph?

**Comment by dnskmr** [comment]
David,

Why did you close the issue? Still, I did not get the proper resolution.

**Comment by davidjgraph** [comment]
There is no question to answer.

**Comment by dnskmr** [comment]
David,

Accepted there is no question, but I need some clarification on mxgraph that is can I draw the architecture diagram for the application?. I would like to draw the servers and it will be communicating via ports. I would like to group the servers. it will be grouped as subnet, subnet will be grouped as vpc. etc. 

Kindly explain me or suggest me something to meet the requirement. Or where can I ask my doubts related to mxgraph?

**Comment by davidjgraph** [comment]
mxGraph cannot "draw the architecture for the application".

**Comment by dnskmr** [comment]
But in mxGrapgh js examples having ports.html there we can add the servers, right?
