### ISSUE TITLE
380 Fails to install on Windows

### ISSUE THREAD

**Issue by ajl000** [jgraph/mxgraph#146]
C:\Users\Adam Law>npm version
{ npm: '5.6.0',
  ares: '1.13.0',
  cldr: '32.0',
  http_parser: '2.7.0',
  icu: '60.1',
  modules: '59',
  nghttp2: '1.25.0',
  node: '9.3.0',
  openssl: '1.0.2n',
  tz: '2017c',
  unicode: '10.0',
  uv: '1.18.0',
  v8: '6.2.414.46-node.15',
  zlib: '1.2.11' }

C:\Users\Adam Law>npm install mxgraph --save
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> mxgraph@3.8.0 postinstall C:\Users\Adam Law\node_modules\mxgraph
> grunt build

Loading "Gruntfile.js" tasks...ERROR
>> TypeError: Cannot read property 'map' of null
Warning: Task "build" not found. Use --force to continue.

Aborted due to warnings.
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Adam Law\package.json'
npm WARN Adam Law No description
npm WARN Adam Law No repository field.
npm WARN Adam Law No README data
npm WARN Adam Law No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! mxgraph@3.8.0 postinstall: `grunt build`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the mxgraph@3.8.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Adam Law\AppData\Roaming\npm-cache\_logs\2018-01-03T04_46_03_931Z-debug.log

....  From log

6847 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Adam Law\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "mxgraph" "--save"
6848 verbose node v9.3.0
6849 verbose npm  v5.6.0
6850 error code ELIFECYCLE
6851 error errno 3
6852 error mxgraph@3.8.0 postinstall: `grunt build`
6852 error Exit status 3
6853 error Failed at the mxgraph@3.8.0 postinstall script.
6853 error This is probably not a problem with npm. There is likely additional logging output above.
6854 verbose exit [ 3, true ]

**Comment by hannesN** [comment]
I also have this error on MacOSX. I am using a vue.js webpack sekeleton for my project.

**Comment by hannesN** [comment]
There is a fix: npm install mxgraph-map-fix
 instead of mxgraph. But this is version 3.7.5.

**Comment by chrisbu** [comment]
Windows 10.
All the following fail:
- npm install mxgraph 
- npm install mxgrapg-map-fix
- npm install git+https://github.com/jgraph/mxgraph.git --save

Error in all cases is like below:

> mxgraph@3.8.0 postinstall c:\Work\achord\code\achord\achord-cat-ui\node_modules\mxgraph
> grunt build --base "$(npm prefix)" --gruntfile etc/build/Gruntfile.js

c:\Work\achord\code\achord\achord-cat-ui\node_modules\grunt\lib\grunt\task.js:434
    process.chdir(grunt.option('base') || path.dirname(gruntfile));
            ^

Error: ENOENT: no such file or directory, uv_chdir
  at Error (native)
  at Task.task.init (c:\Work\achord\code\achord\achord-cat-ui\node_modules\grunt\lib\grunt\task.js:434:13)
  at Object.grunt.tasks (c:\Work\achord\code\achord\achord-cat-ui\node_modules\grunt\lib\grunt.js:111:8)

**Comment by become-iron** [comment]
Installing jjgraph (fork of mxgraph) works for me
[https://github.com/jonjomckay/jjgraph](https://github.com/jonjomckay/jjgraph)
[https://www.npmjs.com/package/jjgraph](https://www.npmjs.com/package/jjgraph)

**Comment by davidjgraph** [comment]
We don't use NPM, so there's no point reporting this. Either submit a PR or....
