### ISSUE TITLE
[BUG] WeightedCellSorter declared twice with exactly inverted compare semantics

### ISSUE THREAD

**Issue by lgleim** [jgraph/mxgraph#147]
The WeightedCellSorter class is defined twice with exactly inverted behavior of the compare function. For production builds this is mightigated by the concatenation order of the 'build system' but this is still certainly an issue.

https://github.com/jgraph/mxgraph-js/blob/339a1f5a168f3fa2a408185f01e4ed73e81cef9c/javascript/src/js/layout/hierarchical/stage/mxCoordinateAssignment.js#L1756

vs

https://github.com/jgraph/mxgraph-js/blob/339a1f5a168f3fa2a408185f01e4ed73e81cef9c/javascript/src/js/layout/mxCompactTreeLayout.js#L1129

**Comment by lgleim** [comment]
Also, which implementation has the expected behavior?

**Comment by davidjgraph** [comment]
The tree version isn't used, we'll remove it.
