### ISSUE TITLE
addMouseListener doesn't fire when an mxCelloverlay is clicked

### ISSUE THREAD

**Issue by leeroydan** [jgraph/mxgraph#149]
I have the following mouse listeners:

` graph.addMouseListener(
{
                mouseDown: function (sender, evt) {
                    viewer.touchStart = Date.now();
                },
                mouseMove: function (sender, evt) { },
                mouseUp: function (sender, evt) {
                    viewer.touchEnd = Date.now();
                }
            });`

The events fire when clicking anywhere within the graph, except when clicking an mxCellOverlay.

Is this expected behaviour?

**Comment by alderg** [comment]
Yes, mxCellOverlay fires a separate click event. The event listeners for that are installed in mxCellRenderer.prototype.installCellOverlayListeners.
