### ISSUE TITLE
Shape-texts overlay in IE 11

### ISSUE THREAD

**Issue by AndreasSchul** [jgraph/mxgraph#150]
Take 2 shapes with random text and give them the same position on the graph. In IE(11) the text from the underlying shape shines through. 

FF 57.0.1 (64-Bit) and Chrome Version 64.0.3282.71 (Official Build) beta (64-Bit) show correct behaviour.

Is any workaround available?

**Comment by davidjgraph** [comment]
No, IE 11 doesn't support foreign objects in SVG, so we're limited to this workaround that has the z-order effect you see.

**Comment by arundhatikan6** [comment]
What is the exact workaround here?

**Comment by davidjgraph** [comment]
It's not really a workaround, it's just HTML. The SVG DOM is always "behind" in z-order, thus HTML labels alway overlay in front.
