### ISSUE TITLE
npm install on grunt fails

### ISSUE THREAD

**Issue by aldente05** [jgraph/mxgraph#152]
> mxgraph@3.8.0 postinstall /Users/alsahfer/Projects/icofr-vuejs/node_modules/mxgraph
> grunt build

Loading "Gruntfile.js" tasks...ERROR
>> TypeError: Cannot read property 'map' of null
Warning: Task "build" not found. Use --force to continue.

Aborted due to warnings.
npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! mxgraph@3.8.0 postinstall: `grunt build`
npm ERR! Exit status 3
npm ERR! 
npm ERR! Failed at the mxgraph@3.8.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alsahfer/.npm/_logs/2018-01-17T09_52_58_523Z-debug.log

how to solve it?

**Comment by davidjgraph** [comment]
I tried clone the repo from Github, running "npm install" in the root and the result seems correct to me. If you followed different steps, please detail what they were.
