### ISSUE TITLE
mxPrintPreview, graph.getLinkForCellState function does not exists

### ISSUE THREAD

**Issue by coclav** [jgraph/mxgraph#153]
I have upgraded to 3.8.0.0 direct from 3500 so don't know when this appeared.

I had to add to override getLinkForCellState function for print to work. As the whole thing is in a try/finally I didn't get why it was failing first.

```
var preview = new mxPrintPreview( /* ... */ );
preview.getLinkForCellState = function () {
  return null;
}
preview.open( /*....*/ );
```

the default implementation calls graph.getLinkForCellState so I could have implemented here but I decided to kill the thing at the source!

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
