### ISSUE TITLE
codec rebuild graph

### ISSUE THREAD

**Issue by marszoolong** [jgraph/mxgraph#165]
hi man,
in my case, i set cell value as an Object, like the following:
{
  "id": 10,
  "label": "loo"
}
when i saved the graph with codec, the value filed was saved like the following:

`<Object id=10 label="loo" as="value" />`

the problem is when rebuilding the graph, i get an incorrect cell value: the value of cells became a cell, and value of the cell is a cell  recursively
```
         var doc = MxUtils.parseXml(xmlString)
          var codec = new MxCodec(doc)
          var res = codec.decode(doc.documentElement, this.graph.getModel())
          console.log(this.graph.getModel())
```
console.log() result:
![image](https://user-images.githubusercontent.com/17477808/35910596-1277a49a-0c32-11e8-8ca6-bd348ac7660a.png)

and i wonder to know if this is an issue, thx

**Comment by alderg** [comment]
Works for me. Here is an example:
`var graph = new mxGraph(container);
var parent = graph.getDefaultParent();
				
graph.getModel().beginUpdate();
try
{
	var v1 = graph.insertVertex(parent, null, {'test': 'value'}, 20, 20, 80, 30);
	var v2 = graph.insertVertex(parent, null, {'test': 'value2'}, 200, 150, 80, 30);
	var e1 = graph.insertEdge(parent, null, {'test': 'value3'}, v1, v2);
}
finally
{
	graph.getModel().endUpdate();
}

var encoder = new mxCodec();
var node = encoder.encode(graph.getModel());
var codec = new mxCodec(node.ownerDocument)
var res = codec.decode(node, graph.getModel())
console.log(graph.getModel())`

**Comment by marszoolong** [comment]
@alderg thank you very much!  but the problem is you created a graph  by using insertVertex / insertEdge, this situation is OK. 

when we test the problem by using the example (fileio.html) of  mxgraph examples, an error will occur:

**mxCodec.js:357 Uncaught RangeError: Maximum call stack size exceeded
    at mxCodec.encode (mxCodec.js:357)**
