### ISSUE TITLE
An issue with getBoundingBoxFromGeometry

### ISSUE THREAD

**Issue by alpha-and-omega** [jgraph/mxgraph#166]
mxGraph.prototype.getBoundingBoxFromGeometry method has 2 small defects:
1) It does not include cell borders - cell borders are outside of it
2) It does not consider rotation - rotated cells are outside of it

I can implement it by myself. There is getBoundingBox and it supports rotation, but I cannot find a way to calculate outline of the cell/edge including border.
Is there a method for this or should I write it from scratch ?
Or more generally - do you have a method to calculate **visible** bounding box for the cell/group of cells/edges ?

**Comment by alderg** [comment]
Try mxCellState.boundingBox
