### ISSUE TITLE
EditorUI positions absolutely over all elements in page

### ISSUE THREAD

**Issue by arpieb** [jgraph/mxgraph#168]
First off, I'm enjoying working with the mxGraph codebase, hats off to the jgraph team!

I'm trying to create an editor in a specific page element using the EditorUI class provided in the library, and the editor keeps taking over the entire page with what appears to be absolute positioning.  Any attempt to wrangle it into place using CSS positioning of the container `div` is resulting in a clipped or hidden editor.

Simple test is to use the example document bundled with the code under `mxgraph/javascript/examples/grapheditor/www/index.html` and edit it to add a "header" `div` and target sibling `div` for the editor with the same `geEditor` class that the `body` element had:

```html
<!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=5,IE=9" ><![endif]-->
<!DOCTYPE html>
<html>
<head>
    <title>Grapheditor</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <link rel="stylesheet" type="text/css" href="styles/grapheditor.css">
	<script type="text/javascript">
		// Parses URL parameters. Supported parameters are:
		// - lang=xy: Specifies the language of the user interface.
		// - touch=1: Enables a touch-style user interface.
		// - storage=local: Enables HTML5 local storage.
		// - chrome=0: Chromeless mode.
		var urlParams = (function(url)
		{
			var result = new Object();
			var idx = url.lastIndexOf('?');

			if (idx > 0)
			{
				var params = url.substring(idx + 1).split('&');

				for (var i = 0; i < params.length; i++)
				{
					idx = params[i].indexOf('=');

					if (idx > 0)
					{
						result[params[i].substring(0, idx)] = params[i].substring(idx + 1);
					}
				}
			}

			return result;
		})(window.location.href);

		// Default resources are included in grapheditor resources
		mxLoadResources = false;
	</script>
	<script type="text/javascript" src="js/Init.js"></script>
	<script type="text/javascript" src="jscolor/jscolor.js"></script>
	<script type="text/javascript" src="sanitizer/sanitizer.min.js"></script>
	<script type="text/javascript" src="../../../src/js/mxClient.js"></script>
	<script type="text/javascript" src="js/EditorUi.js"></script>
	<script type="text/javascript" src="js/Editor.js"></script>
	<script type="text/javascript" src="js/Sidebar.js"></script>
	<script type="text/javascript" src="js/Graph.js"></script>
	<script type="text/javascript" src="js/Shapes.js"></script>
	<script type="text/javascript" src="js/Actions.js"></script>
	<script type="text/javascript" src="js/Menus.js"></script>
	<script type="text/javascript" src="js/Format.js"></script>
	<script type="text/javascript" src="js/Toolbar.js"></script>
	<script type="text/javascript" src="js/Dialogs.js"></script>
</head>
<body>
<div>Test header</div>
<div id="editor-ui-container" class="geEditor">
	<script type="text/javascript">
		// Extends EditorUi to update I/O action states based on availability of backend
		(function()
		{
			var editorUiInit = EditorUi.prototype.init;

			EditorUi.prototype.init = function()
			{
				editorUiInit.apply(this, arguments);
				this.actions.get('export').setEnabled(false);

				// Updates action states which require a backend
				if (!Editor.useLocalStorage)
				{
					mxUtils.post(OPEN_URL, '', mxUtils.bind(this, function(req)
					{
						var enabled = req.getStatus() != 404;
						this.actions.get('open').setEnabled(enabled || Graph.fileSupport);
						this.actions.get('import').setEnabled(enabled || Graph.fileSupport);
						this.actions.get('save').setEnabled(enabled);
						this.actions.get('saveAs').setEnabled(enabled);
						this.actions.get('export').setEnabled(enabled);
					}));
				}
			};

			// Adds required resources (disables loading of fallback properties, this can only
			// be used if we know that all keys are defined in the language specific file)
			mxResources.loadDefaultBundle = false;
			var bundle = mxResources.getDefaultBundle(RESOURCE_BASE, mxLanguage) ||
				mxResources.getSpecialBundle(RESOURCE_BASE, mxLanguage);

			// Fixes possible asynchronous requests
			mxUtils.getAll([bundle, STYLE_PATH + '/default.xml'], function(xhr)
			{
				// Adds bundle text to resources
				mxResources.parse(xhr[0].getText());

				// Configures the default graph theme
				var themes = new Object();
				themes[Graph.prototype.defaultThemeName] = xhr[1].getDocumentElement();

				// Main
				new EditorUi(new Editor(urlParams['chrome'] == '0', themes), document.getElementById("editor-ui-container"));
			}, function()
			{
				document.body.innerHTML = '<center style="margin-top:10%;">Error loading resource files. Please check browser console.</center>';
			});
		})();
	</script>
</div>
</body>
</html>
```

Am I missing something obvious here, or is this a bug in the EditorUI class?

Thanks!

**Comment by alderg** [comment]
"<div id="editor-ui-container" style="position:relative;left:100px;top:100px;height:480px;width:480px;">" works for me. What have you tried?

**Comment by arpieb** [comment]
I only used `position: relative;`, which iirc should cause any element positioning within that container element to be relative to the container origin.  What I'm seeing is the editor being positioned at the window origin, covering my header element.  I'm not looking to explicitly define the width and height of the container as I want the user to be able to scale their window as needed to gain more real estate between a header and footer `div`.

**Comment by alderg** [comment]
The "geFooterContainer" should be hidden (EditorUi.prototype.footerHeight = 0) if no minHeight of 90pxfor "geEditor" is used.

**Comment by malienist** [comment]
Can we relatively position the entire editor layout inside a reusable angular component?

**Comment by johanovic** [comment]
I see this issue was closed, but google lead me here. Just working from the basic example as @arpieb  I too cannot place the editor where I want. I am assuming I might not fully understand how embedding the editor in a page works. Do you maybe have a link to docs or another example (where the editor is part of a larger page)?

**Comment by arpieb** [comment]
@johanovic fwiw, I finally wound up having to embed the editor in an IFRAME element to get it to play nicely as a single component on a larger page - and I wasn't using anything crazy like React, Angular, just plain ol' HTML5...

**Comment by malienist** [comment]
@arpieb You can use a particular div `<div id="editor-container"></div>` to inject the editor layout into it which should have its position set to relative. 

Then change default container div to `editor-container` in EditorUi.js:

Change
`this.container = container || document.body;`

To
`this.container = document.getElementById('editor-container');`

Change position to absolute in grapheditor.css
`
.geMenubarContainer, .geToolbarContainer, .geDiagramContainer, .geSidebarContainer, .geFooterContainer, .geHsplit, .geVsplit {
	overflow:hidden;
	position:absolute;
	cursor:default;
}
`


I guess that should work out for you.
