### ISSUE TITLE
NPM publishing

### ISSUE THREAD

**Issue by lgleim** [jgraph/mxgraph#169]
The current package published to NPM is seriously broken. 

Based on your [publishing script](https://bitbucket.org/jgraph/mxgraph2/src/3b67f877d17bc2ae08dd3be459cee3be3905211c/etc/build/deploy.sh?at=master&fileviewer=file-view-default), what you are publishing to NPM [here](https://bitbucket.org/jgraph/mxgraph2/src/3b67f877d17bc2ae08dd3be459cee3be3905211c/etc/build/deploy.sh?at=master&fileviewer=file-view-default#deploy.sh-44) is the full mxgraph distribution. That is all source code, all build files, all resources in all languages. Additionally the package.json incorrectly contains webpack, grunt etc. as dependencies instead of devDependencies. Thus installing just the mxgraph package as a dependency in a newly created empty folder results in a total of **92 MB** of files.

The package.json further defines "main": "./javascript/dist/build.js" to be the entry point of the package. The dist folder is however excluded through the .gitignore file. Thus the mxgraph library actually cannot be included from npm in its current form - the package is broken. The github repository recently received a .npmignore file (https://github.com/jgraph/mxgraph/commit/78a73184b0fd0fcb138bc8ba425d47047282faa6) which mitigates this issue, this is however not in the bitbucket repository yet (although [referenced](https://bitbucket.org/jgraph/mxgraph2/src/3b67f877d17bc2ae08dd3be459cee3be3905211c/etc/build/deploy.sh?at=master&fileviewer=file-view-default#deploy.sh-43) in the deploy script).

Your build script actually also pushes the js code to a separate mxgraph-js repository. 
This looks a bit more like what an npm package should contain but is also incompatible with npm usage. In order to be compatible with your documentation, the [main file](https://bitbucket.org/jgraph/mxgraph2/src/3b67f877d17bc2ae08dd3be459cee3be3905211c/etc/build/mxgraph-js-package.json?at=master&fileviewer=file-view-default#mxgraph-js-package.json-6) should include the [UMD loader code](https://bitbucket.org/jgraph/mxgraph2/src/3b67f877d17bc2ae08dd3be459cee3be3905211c/etc/build/Gruntfile.js?at=master&fileviewer=file-view-default#Gruntfile.js-52) you add during the grunt build process. Nevertheless it is of course a cleaner solution to directly publish to npm from the original code.

In order to fix these issues I created a fork with a [single additional commit](https://bitbucket.org/lgleim/mxgraph2/commits/7374dd23a9025b2070e80afa851277dc6c3530c2?at=master) on bitbucket: https://bitbucket.org/lgleim/mxgraph2

Unfortunately I cannot create pull requests there and the github repo has a somewhat different structure.

Since I am not familiar with all the other requirements to be fulfilled in order to execute the build.sh script, I was not able to test the code with your build script. The build does complete successfully with the following steps:
```
git clone git@bitbucket.org:lgleim/mxgraph2.git
cd mxgraph2
sed "s/@VERSION@/3.9.2/" etc/build/mxgraph-package.json > package.json
npm install
# npm publish
```
So I kindly ask you to review and manually merge my [patch](https://bitbucket.org/lgleim/mxgraph2/commits/7374dd23a9025b2070e80afa851277dc6c3530c2?at=master) and (hopefully) to subsequently publish a working version of mxgraph to the npm registry.

**Comment by davidjgraph** [comment]
Thanks, I'll pull the changes in and release. Please that we don't use NPM, so we'll just pull in your changes and release as-is without testing.

**Comment by lgleim** [comment]
Thanks for the quick reaction. Unfortunately the buildstep still seems to fail.
It appears that [mxgraph-distro.zip](https://bitbucket.org/jgraph/mxgraph2/src/df2e0bbb0f33fe85fbd08c151de1dadfca478b35/etc/build/deploy.sh?at=master&fileviewer=file-view-default#deploy.sh-36) does not actually contain all the required source files. 

I guess they might be there after the code moving/copying/juggling logic in line [49-60 of deploy.sh](https://bitbucket.org/jgraph/mxgraph2/src/df2e0bbb0f33fe85fbd08c151de1dadfca478b35/etc/build/deploy.sh?at=master&fileviewer=file-view-default#deploy.sh-49). However again, I cannot test it.

So in order to clear things up a bit - is there a reason not to simply do the following to publish?
```
git clone git@bitbucket.org:jgraph/mxgraph2.git
cd mxgraph2
sed "s/@VERSION@/3.9.2/" etc/build/mxgraph-package.json > package.json
npm install
npm publish
```
Or alternatively following the [current clone step]:(https://bitbucket.org/jgraph/mxgraph2/src/df2e0bbb0f33fe85fbd08c151de1dadfca478b35/etc/build/deploy.sh?at=master&fileviewer=file-view-default#deploy.sh-36) 
```
cd mxgraph
sed "s/@VERSION@/$DOTVERSION/" $BUILD/../etc/build/mxgraph-package.json > package.json
npm install
npm publish  --access publicex
```

**Comment by lgleim** [comment]
In the spirit of harmonization I also created a pull request for the github repo to include the proper .npmignore:
https://github.com/jgraph/mxgraph/pull/170

**Comment by davidjgraph** [comment]
I'll pull anything we're given. Neither of us have any understanding of NPM, as long as it doesn't break it for us, you guys can break it as many times as you like :).

**Comment by lgleim** [comment]
Allright - is there a reason for the complicated deployment procedure of mxgraph-js? Is that package used at all? To me it actually rather adds to the confusion...

**Comment by davidjgraph** [comment]
Some users requested it.

**Comment by lgleim** [comment]
Allright. I'll try hard to not break anything.

**Comment by lgleim** [comment]
Do you [rebuild the entire mxgraph repository](https://bitbucket.org/jgraph/mxgraph2/src/df2e0bbb0f33fe85fbd08c151de1dadfca478b35/etc/build/deploy.sh?at=master&fileviewer=file-view-default#deploy.sh-59) on purpose during each build? In order to avoid divergence between the repositories?

**Comment by davidjgraph** [comment]
It's a master/slave arrangement, yes. This is how it evolved historically. Bitbucket was the only repo and closed source. Then we open sourced and pushed out the open source version on each release from BB to GH. I know there's options to use CI to build on a push to a repo, but, as I say, the build/deploy isn't broken for us and there's no resources for a re-work.

**Comment by lgleim** [comment]
I understand how these things evolve. In order to not break the pull request workflow in the future - how do you merge pull requests to the open source variant into your private repo? Allways manually?

**Comment by davidjgraph** [comment]
It's not private any more, https://bitbucket.org/jgraph/mxgraph2, I think submitting a PR should be possible on BB.

**Comment by lgleim** [comment]
In that case - how about just keeping both repositories synchronized?

**Comment by davidjgraph** [comment]
then we'd have noise like this NPM stuff in the root of our repo, that's not happening :)

**Comment by lgleim** [comment]
Allright, I think this will likely keep being a pain point for you in the future though. 

I [restructured the deploy script](https://bitbucket.org/lgleim/mxgraph2/commits/2a9f4c7d1ee382ea6747ff26fafc7ad5784e33af) (basically no changes, just reordering lines)  in a way that should finally fix the npm build without changing anything else. 

Please find the patch in my fork: https://bitbucket.org/lgleim/mxgraph2

**Comment by lgleim** [comment]
I just noticed that there was one too many exclusion in the .npmignore. Updated my repo accordingly.

**Comment by lgleim** [comment]
By the way - the settings of your bitbucket repository do not allow to submit public pull requests.

**Comment by davidjgraph** [comment]
Not sure about BB, my understanding was anyone with read access can submit a PR, but I could be wrong. I've deployed, does it work now?

**Comment by lgleim** [comment]
Regarding BB: Unfortunately not. I cannot create pull requests there.

Regarding redeployment: Also Unfortunately not. While [you included parts](https://bitbucket.org/jgraph/mxgraph2/commits/6db5cc01a9cc9de39954c2dd6b0d11e35a6fe1c7#chg-etc/build/deploy.sh) of [my changes](https://bitbucket.org/lgleim/mxgraph2/commits/2a9f4c7d1ee382ea6747ff26fafc7ad5784e33af#chg-etc/build/deploy.sh) to the deploy script, the relevant restructuring of the deployment process and what is published to npm did not make it into your code base. The changes still missing in the current version of your deploy script are directly apparent in a [side-by-side diff](https://www.diffchecker.com/0RW8yv3V). Nevertheless, I was still not able to test the script.

**Comment by lgleim** [comment]
And just now I noticed another issue with the .npmignore file, which is that it will never be copied over by the `cp -rf tmp/mxgraph/* mxgraph/` command, since it is a hidden file. Thus [an additional change](https://bitbucket.org/lgleim/mxgraph2/commits/fd1d3fa450c163c7105b8beb65f99fab8382a0a1) is required. C.f. [resulting side-by-side diff](https://www.diffchecker.com/Ha0bzs7j)

**Comment by ViksYelapale** [comment]
@davidjgraph any updates on this issue? Is it fixed?

I am using mxgraph version 3.9.3.

But when i tried to run `ng serve` , I get error as follows:

`Module not found: Error: Can't resolve 'mxgraph' in 'path to my file where I have imported and used mxgraph'`

**Comment by davidjgraph** [comment]
This change changes the behaviour of the deployment to git. It clones the Github version over the release, we currently do it the other way around. Unfortunately, I can't accept this change.

**Comment by lgleim** [comment]
Fine. Just please unpublish your npm package in order to stop confusing people if you do not intend to fix it.

**Comment by davidjgraph** [comment]
Then we'll just have a pile more requests for publishing to NPM. If someone can submit a PR to the BB repo with a fix that doesn't break our deploy, we're happy to accept it.

**Comment by marcz81** [comment]
Is there already a fix for this issue?

**Comment by davidjgraph** [comment]
What problem are you seeing?

**Comment by marcz81** [comment]
When I install mxGraph via
`npm install mxgraph --save and`

and load it in my js using
`var mxgraph = require("mxgraph")(
  mxImageBasePath: "./src/images",
  mxBasePath: "./src"
})`

I get the error `Module not found`

**Comment by lgleim** [comment]
The real issue is that the bundled script, i.e. the [package's main script](https://github.com/jgraph/mxgraph/blob/master/package.json#L18) is simply not included in what is published to npm.

**Comment by davidjgraph** [comment]
And I don't know what that means unfortunately, thus the impass :).

**Comment by davidjgraph** [comment]
Can we just move lines 64 and 65 line upwards https://bitbucket.org/jgraph/mxgraph2/src/master/etc/build/deploy.sh ?

That keeps the git deploy as it was, which was the problem with the previous patch.

We plan to move this to Github at some point, which will simplify things a little, but it's finding the resources to do it.

**Comment by davidjgraph** [comment]
I just tried npm install mxgraph on my command line and that works with 3.9.7. I'm assuming this issue is now resolved.

**Comment by mamhaidly** [comment]
I am getting the same issue with 3.9.8, any pointers on how to fix it?

**Comment by lgleim** [comment]
Just to reiterate - the general issue is the following:
The mxgraph package published to npm does not actually include the main entry file `"main": "./javascript/dist/build.js",` that is declared in the package.json. Thus (as far I can tell) if it is just installed as a general dependency (`npm install` without arguments, resolving your projects package.json dependencies), the file will never ever be able to be imported. Thus this issue.

However the package.json includes a `prepare` script (`"prepare": "grunt build --base ./ --gruntfile etc/build/Gruntfile.js"`), which is exectued by npm if you specifically manually install the mxgraph package.
`npm install mxgraph` (or even better npm install github:jgraph/mxgraph) pulls what is published to npm, actually installs all dev dependencies of the mxgraph library and builds it locally. Thus you can get it to work and this process also does not fail deterministically (hail npm) but it is still due to the simple fact, that the way this project is published to npm does not make any sense.

**Comment by lkeller-nviso** [comment]
I ended up on this bug while trying to understand how to use the module with webpack.

I think I found a reasonable workaround that allows to use the current npm package, I document it here in case it may be useful for somebody else:

In the webpack configuration I added:

```javascript
  module: {
    rules: [
      {
        test: require.resolve('mxgraph/javascript/mxClient.min.js'),
        use: [
          'imports-loader?mxBasePath=>"/ui/static/mxgraph/"',
          'exports-loader?mxEvent,mxGraph,mxRubberband'
        ]
      }
    ]
  }
```

This makes sure the `mxBasePath` is properly set and the required variables are exported from the volume. Notice that I include the minified version to avoid troubles, this is normally not recommended.

Then to make the mxgraph assets available I add the following:
```javascript
  plugins: [
    // copy mxgraph assets
    new CopyWebpackPlugin([
      {
        from: path.resolve(__dirname, '../node_modules/mxgraph/javascript/src'),
        to: config.dev.assetsSubDirectory + '/mxgraph',
        ignore: ['.*']
      }
    ])
  ]
```
With these two changes I can then use the module as follows:

```javascript
import {mxEvent, mxGraph, mxRubberband} from 'mxgraph/javascript/mxClient.min.js'

var graph = new mxGraph(container)

```

**Comment by mikalai-ramashka** [comment]
Add to package.json
```
"mxgraph": "git+ssh://git@github.com:jgraph/mxgraph.git#v3.9.11",
```

And everything is working fine:
```
import setupMxGraph from 'mxgraph';

const { mxEvent, mxGraph, mxRubberband } = setupMxGraph({
	mxImageBasePath: '../../src/images',
	mxBasePath: '../../src'
});
```
