### ISSUE TITLE
error: open is not a function in js/Menus.js

### ISSUE THREAD

**Issue by alpha-and-omega** [jgraph/mxgraph#171]
Present both in grapheditor and draw.io

How to reproduce:
1) Open grapheditor in browser:
2) add General->Text cell
3) Select Text menu, click Left text formatting (right, center too)
4) open javascript console

javascript console displays error: open is not a function in js/Menus.js

**Comment by davidjgraph** [comment]
Thanks for report. It's fixed upstream with https://bitbucket.org/jgraph/mxgraph2/commits/1669acd977ca4b00ddde10b2b93cb514efb47e44 and we'll release by Monday.
