### ISSUE TITLE
Bug in svg generation code

### ISSUE THREAD

**Issue by alpha-and-omega** [jgraph/mxgraph#174]
Bug leads to blurry svg graphs.
Bug present both in grapheditor and draw.io

How to reproduce:
1) goto draw.io
2) create rectangle, set width to 2pt, height 2pt, line width 2 pt.
3) select rectangle. Export selection as SVG.
4) open created svg code in a browser and take a screenshot
5) zoom in and see that rectangle is not 4x4 pixels, but blurred 3.5x3.5 pixels
6) look into source of generated SVG and see the cause:
**transform="translate(0.5,0.5)"**

Removing this part from SVG makes everything clear and beautiful.

**Comment by alpha-and-omega** [comment]
Oh. This relates to 'crisp' option of getSvg method. It shoud be named 'nocrisp' ;)

**Comment by alpha-and-omega** [comment]
I am reopening this ticket.

After some research I am assured that getSvg method is bugged.
**crisp** option of getSvg method was added to mitigate the fact, that lines in svg are drawn around the **basis**, and 1pt lines are shown as 0.5+0.5 points. So to make them clear there is **crisp** option of getSVG method to shift the viewpoint by 0.5x0.5. But it has problems with 2pt width lines, because **crisp** option becomes harmful and makes lines blurred.

But there is better way. getSVG should get exact (float values) bounding box and shift the graph so that there is no spaces between bounding box and the graph. This will make svg export always "crisp" without **crisp** option.

And even now with 0.5x0.5 crisp shift it works incorrectly, because shift should be -0.5x-0.5, not 0.5x0.5.

What do you think ?

**Comment by alderg** [comment]
Thanks for the detailed report, we'll investigate.

**Comment by alderg** [comment]
For backwards compatibility with older versions of IE we cannot use svg.getBBox.
