### ISSUE TITLE
Strange group resizing

### ISSUE THREAD

**Issue by alpha-and-omega** [jgraph/mxgraph#177]
Group resizing with livePreview is bugged, so I think livePreview should be disabled for this particular type of resize.

How to reproduce:
1) grapheditor / draw.io, create group with 2 rectangles
2) try to resize group by dragging left-top corner. Preview of resize does not resize rectangles but drags them. This looks ugly when decreasing size.

**Comment by alderg** [comment]
Live preview will be disabled for this case in the next release.
