### ISSUE TITLE
MxGraph XML,  load XML correctly when cells have childs, ports and columns?

### ISSUE THREAD

**Issue by td00k** [jgraph/mxgraph#181]
My interface I use tables as vertex (like schema example) and they have columns as child vertex, ports and overlays. When I use the basic code example for export XML (given in the mxCodec documentation), the cells don't render correctly, the tables (swimlanes) are displayed without anything append to them. Can someone help me with this?

**Comment by davidjgraph** [comment]
Please post programming questions to https://stackoverflow.com/questions/tagged/mxgraph
