### ISSUE TITLE
How to combine grapheditor with map API?

### ISSUE THREAD

**Issue by RenBaixiao** [jgraph/mxgraph#193]
I'd like to combine the grapheditor example with map API such as JavaScript API of baidu map, thus I can put some labels or marks while browsing the map. My plan is to substitute "div class=geDiagramContainer geDiagramBackdrop" with a map div. Does anyone have any other ideas or suggestions?

**Comment by alderg** [comment]
[Here](https://jgraph.github.io/mxgraph/javascript/examples/map.html) is an example for using Google maps with mxGraph.
