### ISSUE TITLE
Error in Grapheditor-Example: "Misc"-Palette can not be opened

### ISSUE THREAD

**Issue by AndreasSchul** [jgraph/mxgraph#202]
Version: 3.9.6

Unfortunately, you can not open the palette "Misc" in the sidebar. The reason is in the sidebar.js in 

`Sidebar.prototype.addMiscPalette = function(expand)`

There is missing a declaration

`var sb = this;`

in the beginning, so line 1080

`return sb.createVertexTemplateFromCells([cell], cell.geometry.width, cell.geometry.height, 'Shape Group');`

will fail.

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
