### ISSUE TITLE
Grapheditor example: sidebar.js has incomplete description for some shapes

### ISSUE THREAD

**Issue by AndreasSchul** [jgraph/mxgraph#203]
Version: 3.9.6

The shapes "Ellipse", "Circle", "Triangle" and "Diamond" from the "General"-palette appear as rectangles. 

The reason is an incomplete description in sidebar.js in lines 929, 931, 933 and 936:

> this.createVertexTemplateEntry('**shape=**...

The **bold** descriptor should be added in each line.

**Comment by alderg** [comment]
These are defined in styles/default.xml, are you loading that file?
