### ISSUE TITLE
Integrate scratch pad 

### ISSUE THREAD

**Issue by zjhiphop** [jgraph/mxgraph#206]
Hi, there, recently i have a requirement to integrate scratch pad like draw.io.

Basically, i want to add images from my local file system, but currently only support add by URL. And i checked the usage in draw.io,  the ScratchPad could do this. 

So is there any easy way to use the feature? Thanks

**Comment by davidjgraph** [comment]
The best example is the scratchpad implementation in draw.io, I'd either port the code over or use draw.io.
