### ISSUE TITLE
[feature]Would it be nice to have a constraint with absolute intersect point

### ISSUE THREAD

**Issue by RidgeSTD** [jgraph/mxgraph#207]
Hi,
would that be nice to let it possible to define an constraint intersect point on a Cell, say, always (0, 10) of a cell? In my case I always need the edge to be vertical and has 30px margin to the left (regard less the size of cells) but with neither style `exitX/entryX` nor by defining a constraint can I reach this. 

I found that in `mxGraph.prototype.getConnectionPoint` it's always calculated by for example:

```javascript
point = new mxPoint(bounds.x + constraint.point.x * bounds.width,
				bounds.y + constraint.point.y * bounds.height);
```
I used a small workaround that would do the trick. However it looks stupid:

```javascript
mxGraphView.prototype.getFixedTerminalPoint = function(edge, terminal, source, constraint) {
    if (terminal.cell._fix_constraint) {
        var bounds = this.getPerimeterBounds(terminal);
		return new mxPoint(bounds.x + _absolute_constraint.x, bounds.y + _absolute_constraint.y);
    }

    // following is the original code
    ... 
}
```

where _fix_constraint is a custom parameter defined while initializing. Of course it's just a brief description of my idea, one has to consider the `source` etc. too, in real situation there will  definitely be much more things to consider.

**Comment by alderg** [comment]
Has been implemented via exitDx/Dy and entryDx/Dy styles.
