### ISSUE TITLE
Error "Cannot start application: Failed to execute 'send' on 'XMLHttpRequest'"

### ISSUE THREAD

**Issue by TiedtTech** [jgraph/mxgraph#209]
When I try the example diagrameditor.html that is in the "javascript\examples\editors" folder when opening the HTML file I get the message:

Cannot start application: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'file:///D:/mxgraph-master/javascript/examples/editors/config/diagrameditor.xml'.

I'm using Chrome
what am I doing wrong?

**Comment by davidjgraph** [comment]
You cannot make XHR calls from JS loaded from the file system. You have to host this on a server, even if locally.
