### ISSUE TITLE
Custom shape

### ISSUE THREAD

**Issue by TiedtTech** [jgraph/mxgraph#210]
Hello, I wonder if it is possible for me to create and add new shape / component library?

**Comment by frenebo** [comment]
Yes, the documentation for mxShape shows how:

https://jgraph.github.io/mxgraph/docs/js-api/files/shape/mxShape-js.html#mxShape

Here are the first few paragraphs of the documentation:

> 
> To extend from this class, the basic code looks as follows.  In the special case where the custom shape consists only of one filled region or one filled region and an additional stroke the mxActor and mxCylinder should be subclassed, respectively.
> ```
> function CustomShape() { }
> 
> CustomShape.prototype = new mxShape();
> CustomShape.prototype.constructor = CustomShape;
> ```
> To register a custom shape in an existing graph instance, one must register the shape under a new name in the graph’s cell renderer as follows:
> ```
> mxCellRenderer.registerShape('customShape', CustomShape);
> ```
> The second argument is the name of the constructor.
> 
> In order to use the shape you can refer to the given name above in a stylesheet.  For example, to change the shape for the default vertex style, the following code is used:
> ```
> var style = graph.getStylesheet().getDefaultVertexStyle();
> style[mxConstants.STYLE_SHAPE] = 'customShape';
> ```
