### ISSUE TITLE
Custom shape for xml

### ISSUE THREAD

**Issue by TiedtTech** [jgraph/mxgraph#212]
Where do I get the documentation of custom shape creation by XML, what properties are there and what do they serve?

Another question, is there an online editor or is it trial and error?

**Comment by MohammedAbdulMateen** [comment]
I have similar requirement to create custom tool box item or a custom shape.

![image](https://user-images.githubusercontent.com/17563774/41852828-dc20b744-78a9-11e8-804b-18bd9151621a.png)

As we can see in the above diagram that there are 3 rectangles in the tool box, and in the graph we can see what those are i.e. User Question, Answer and Follow-up Question each having different color and different properties such as initial text

Could you please help me in creating 3 different rectangles with different properties

**Comment by MohammedAbdulMateen** [comment]
I see there is a basic example of creating a custom shape in `shape.html` file present in javascript/examples.

The following lines changes the default style but it changes for all vertices but in my case I want 3 different shapes present in the same graph which can be dragged and dropped from the toolbar.

```
// Changes the default style for vertices "in-place"
// to use the custom shape.
var style = graph.getStylesheet().getDefaultVertexStyle();
style[mxConstants.STYLE_SHAPE] = 'box';
				
// Adds a spacing for the label that matches the
// extrusion size
style[mxConstants.STYLE_SPACING_TOP] = BoxShape.prototype.extrude;
style[mxConstants.STYLE_SPACING_RIGHT] = BoxShape.prototype.extrude;
				
// Adds a gradient and shadow to improve the user experience
style[mxConstants.STYLE_GRADIENTCOLOR] = '#FFFFFF';
style[mxConstants.STYLE_SHADOW] = true;
// Note: The above changes default styles for all vertices
```
