### ISSUE TITLE
mxDoubleRectangleShape missing in JavaScript, incompletely implemented in Java

### ISSUE THREAD

**Issue by arpieb** [jgraph/mxgraph#217]
Trying to leverage the Java-based rendering API to create thumbnails of Javascript-created mxGraph XML, and discovered that not only is _mxDoubleRectangleShape_ missing in the Javascript API, but it doesn't properly support rounding in the Java API (yet _mxRectangleShape_ does).

Working on a fix in a fork, unless this is something already in progress and I just couldn't find the issue.

**Comment by alderg** [comment]
We use a special XML generated in JavaScript for export to avoid having to implement all the shapes twice. See https://github.com/jgraph/mxgraph/blob/master/java/examples/com/mxgraph/examples/web/resources/export.html
