### ISSUE TITLE
Create custom tool box item

### ISSUE THREAD

**Issue by MohammedAbdulMateen** [jgraph/mxgraph#219]
I have a requirement to create custom tool box item.

![41852828-dc20b744-78a9-11e8-804b-18bd9151621a](https://user-images.githubusercontent.com/17563774/41894584-fc2025fa-793c-11e8-8dc6-e3e6ee17aa60.png)

As we can see in the above diagram that there are 3 rectangles in the tool box, and in the graph we can see what those are i.e. User Question, Answer and Follow-up Question each having different color and different properties for e.g. such as different initial text

Could you please help me in creating 3 different rectangles with different properties. I created the graph by following `diagrameditor.html` in javascript/examples/editors folder.

I see there is a basic example of creating a custom shape in shape.html file present in javascript/examples.

The following lines changes the default style but it changes for all vertices but in my case I want 3 different shapes present in the same graph which can be dragged and dropped from the toolbar. So, the style should be at vertex level not the graph level, could you please help me in achieving this

```
// Changes the default style for vertices "in-place"
// to use the custom shape.
var style = graph.getStylesheet().getDefaultVertexStyle();
style[mxConstants.STYLE_SHAPE] = 'box';
				
// Adds a spacing for the label that matches the
// extrusion size
style[mxConstants.STYLE_SPACING_TOP] = BoxShape.prototype.extrude;
style[mxConstants.STYLE_SPACING_RIGHT] = BoxShape.prototype.extrude;
				
// Adds a gradient and shadow to improve the user experience
style[mxConstants.STYLE_GRADIENTCOLOR] = '#FFFFFF';
style[mxConstants.STYLE_SHADOW] = true;
// Note: The above changes default styles for all vertices
```

Thanks in advance

**Comment by mattsrinc** [comment]
You have diagrameditor.xml file, right?

Just add two additional different style templates in the mxStylesheet (tag) section by copying rectangle group and then change their style definitions accordingly.

And after that just repeat a similar action to create two additional icons (you already have) with calling them with different style template (and possibly different icon as well).

Someone has to answer, I still haven't got any. Hope I'll not wait that long.
