### ISSUE TITLE
cellLabelChanged don`t apply mutate newValue param

### ISSUE THREAD

**Issue by anzolo** [jgraph/mxgraph#221]
Hello!

In my model I have objects in vertex`s value. And I handle changes of label like below:

```
      let cellLabelChanged = this.graph.cellLabelChanged;
      this.graph.cellLabelChanged = function (cell, newValue, autoSize) {

        let elt = JSON.parse(JSON.stringify(cell.value));
        elt.name = newValue;

        newValue = elt;

        cellLabelChanged.apply(this, [cell, newValue, autoSize]);
      };
```

But "newValue" don`t mutate in object and in mxEvent.LABEL_CHANGED event go string value.

Can anybody give the advice? what i do wrong?

**Comment by davidjgraph** [comment]
Use `model.setValue()` and in general use the model for changing attributes as described in the [user manual](https://jgraph.github.io/mxgraph/docs/manual.html#3.1.1)
