### ISSUE TITLE
Swimlanes auto layout

### ISSUE THREAD

**Issue by larsbs** [jgraph/mxgraph#223]
Hi, I'm trying to achieve a specific layout in which you have swimlanes, and inside swimlanes you have an hierarchical layout. The thing is, swimlanes should take into account the other nodes in order to position themselves however, I can't make that happens, no matter what I try, all the nodes are always positioned at the beginning of the swimlane and all the edges are crossing. Basically, what I want to get is exactly something like this example: https://live.yworks.com/demos/complete/tableeditor/ but I don't know if that's possible in mxgraph

I've been searching online for quite a few days and a lot of people seem to struggle with this problem but there are no solutions to it, at least, I couldn't find any of them.

**Comment by AZhilkin** [comment]
You should check http://jgraph.github.io/mxgraph/javascript/examples/swimlanes.html . It seems it is what you are trying to do.

**Comment by larsbs** [comment]
I already did, it's not what I want because I wan't the swimlanes to auto position their nodes and in the example you linked, the nodes are positioned manually from the data.

**Comment by lawrae** [comment]
anyone got an answer to this question?

**Comment by ancabalc** [comment]
Hi, I know this is closed but I'm struggling with this issue and I was wondering if you got a solution for it.
Thank you!
