### ISSUE TITLE
memory leak for editing the graph

### ISSUE THREAD

**Issue by hqzxjczx** [jgraph/mxgraph#224]
### One-line summary [问题简述]
when i repeat drag one vertex on the graph's container,the number of  js heap size 、DOM Nodes  and js event listeners grow up all the time. inspecting it by allocation instrumentation timeline in the chrome devtool memory panel. images bellow:
![image](https://user-images.githubusercontent.com/16235271/42355636-a9b4b922-8100-11e8-8425-49ba31a41323.png)

init image
![image](https://user-images.githubusercontent.com/16235271/42355608-82598f38-8100-11e8-8f99-cd05e548b509.png)
after draging image

from images, the problem is mxEvent.objects referrance the element, which is added eventListeners.
### Version & Environment [版本及环境]
Google Chrome canary 69.0.3482.0 version
window10 
###  Expected behaviour [期望结果]
expect for no memroy leak by editing the graph.

**Comment by davidjgraph** [comment]
Did you invoke a garbage collection manually to confirm they are still referenced?

**Comment by hqzxjczx** [comment]
yes, after draging, invoke a garbage collection manually.@davidjgraph

**Comment by hqzxjczx** [comment]
![image](https://user-images.githubusercontent.com/16235271/42563760-99c6c412-8531-11e8-9638-b1d1b2c66239.png)

when tthe canvas container is blank, the count of the mxEvent.object count is 386.
![image](https://user-images.githubusercontent.com/16235271/42563862-d83d64f8-8531-11e8-8da7-fb176c8fd7d8.png)

after drawing one stencil graph to the canvas container, the count of the  mxEvent.object  is 611.

![image](https://user-images.githubusercontent.com/16235271/42563916-00ded202-8532-11e8-9166-b1e9ffa56dbf.png)

after drag the graph to another place in the canvas container, the count of the mxEvent.object is 753.

![image](https://user-images.githubusercontent.com/16235271/42564073-5ee5dd00-8532-11e8-97ba-d39607d4d965.png)

add another stencil graph to the canvas container, the count of mxEvent.object is 1320.

after analysing the source code, when trigger the 'change' event, invoke 'format.refresh' function. the 'format.refresh' invoke  'format.clear' function and 'format.init' function. the 'format.clear' function doesn't detach the reference for mxEvent.objects to elements. And the 'format.init' function is to remove the elements in the format.container, and create new DOM elements to append to format.container. so the elements referenced by mxEvent.objects and the listeners in the elements can't be garbaged by browser. 
from mxEvent class source code bellow.
```
var mxEvent =
{

	/**
	 * Class: mxEvent
	 * 
	 * Cross-browser DOM event support. For internal event handling,
	 * <mxEventSource> and the graph event dispatch loop in <mxGraph> are used.
	 * 
	 * Memory Leaks:
	 * 
	 * Use this class for adding and removing listeners to/from DOM nodes. The
	 * <removeAllListeners> function is provided to remove all listeners that
	 * have been added using <addListener>. The function should be invoked when
	 * the last reference is removed in the JavaScript code, typically when the
	 * referenced DOM node is removed from the DOM, and helps to reduce memory
	 * leaks in IE6.
	 * 
	 * Variable: objects
	 * 
	 * Contains all objects where any listener was added using <addListener>.
	 * This is used to reduce memory leaks in IE, see <mxClient.dispose>.
	 */
	objects: [],

	 /**
	  * Function: addListener
	  * 
	  * Binds the function to the specified event on the given element. Use
	  * <mxUtils.bind> in order to bind the "this" keyword inside the function
	  * to a given execution scope.
	  */
	addListener: function()
	{
		var updateListenerList = function(element, eventName, funct)
		{
			if (element.mxListenerList == null)
			{
				element.mxListenerList = [];
				mxEvent.objects.push(element);
			}
			
			var entry = {name: eventName, f: funct};
			element.mxListenerList.push(entry);
		};
		
		if (window.addEventListener)
		{
			return function(element, eventName, funct)
			{
				element.addEventListener(eventName, funct, false);
				updateListenerList(element, eventName, funct);
			};
		}
		else
		{
			return function(element, eventName, funct)
			{
				element.attachEvent('on' + eventName, funct);
				updateListenerList(element, eventName, funct);				
			};
		}
	}(),

	/**
	 * Function: removeListener
	 *
	 * Removes the specified listener from the given element.
	 */
	removeListener: function()
	{
		var updateListener = function(element, eventName, funct)
		{
			if (element.mxListenerList != null)
			{
				var listenerCount = element.mxListenerList.length;
				
				for (var i = 0; i < listenerCount; i++)
				{
					var entry = element.mxListenerList[i];
					
					if (entry.f == funct)
					{
						element.mxListenerList.splice(i, 1);
						break;
					}
				}
				
				if (element.mxListenerList.length == 0)
				{
					element.mxListenerList = null;
					
					var idx = mxUtils.indexOf(mxEvent.objects, element);
					
					if (idx >= 0)
					{
						mxEvent.objects.splice(idx, 1);
					}
				}
			}
		};
		
		if (window.removeEventListener)
		{
			return function(element, eventName, funct)
			{
				element.removeEventListener(eventName, funct, false);
				updateListener(element, eventName, funct);
			};
		}
		else
		{
			return function(element, eventName, funct)
			{
				element.detachEvent('on' + eventName, funct);
				updateListener(element, eventName, funct);
			};
		}
	}(),

```
we should know, that every DOM elements, which add listeners by mxEvent.addListener function, should invoke mxEvent.removeListeners when reomve DOM elements, but in the 'format.clear', it finally invoke the 'mxEventSource.prototype.removeListener', and is not invoke 'mxEvent.removeListener'. 
![image](https://user-images.githubusercontent.com/16235271/42566063-df502b4e-8537-11e8-8968-4b4280b15961.png)
![image](https://user-images.githubusercontent.com/16235271/42566094-fb36ce8a-8537-11e8-9c24-925ed32409e5.png)
![image](https://user-images.githubusercontent.com/16235271/42566215-79913dd8-8538-11e8-9bf7-460dbbfb2c50.png)

mxGraphModel  is extend mxEventSource, so it  invoke the bellow code:
```
/**
 * Function: removeListener
 *
 * Removes all occurrences of the given listener from <eventListeners>.
 */
mxEventSource.prototype.removeListener = function(funct)
{
	if (this.eventListeners != null)
	{
		var i = 0;
		
		while (i < this.eventListeners.length)
		{
			if (this.eventListeners[i+1] == funct)
			{
				this.eventListeners.splice(i, 2);
			}
			else
			{
				i += 2;
			}
		}
	}
};

```
it doesn't invoke mxEvent.removeListener function.

**Comment by alderg** [comment]
Thanks for the detailed report, we'll remove mxEvent.objects in the next release.
