### ISSUE TITLE
another problem to lead to memory leak

### ISSUE THREAD

**Issue by hqzxjczx** [jgraph/mxgraph#229]
One-line summary [问题简述]
![image](https://user-images.githubusercontent.com/16235271/42991274-ab60f866-8c37-11e8-8cd5-d6bd37bfb926.png)
![image](https://user-images.githubusercontent.com/16235271/42991294-b3e4e038-8c37-11e8-8473-e7801f23c852.png)
![image](https://user-images.githubusercontent.com/16235271/42991994-defe7ba6-8c39-11e8-83be-08b6dc4e1a89.png)
![image](https://user-images.githubusercontent.com/16235271/42992155-58d14daa-8c3a-11e8-971e-af9b399c0858.png)

 
```
  Toolbar.prototype.addMenu = function (label, tooltip, showLabels, name, c, showAll) {
    var menu = this.editorUi.menus.get(name);
    var elt = this.addMenuFunction(label, tooltip, showLabels, function () {
      menu.funct.apply(menu, arguments);
    }, c, showAll);

    menu.addListener('stateChanged', function () {
      elt.setEnabled(menu.enabled);
    });

    return elt;
  };
```
we can see that after dragged the rectangle graph, the length of  'sb.editorUi.menus.menus.fontFamily.eventListeners' (Array), grow up all the time. And the most serious problem is that the function referenced by the eventListeners, retained other local variables, such as the menu and elt.  the elt and menu reference other variables, which can not be garbaged by the browser, the will lead memory leak. so we can repaire the bug like this:
```
  Toolbar.prototype.addMenu = function (label, tooltip, showLabels, name, c, showAll) {
    var menu = this.editorUi.menus.get(name);
    var elt = this.addMenuFunction(label, tooltip, showLabels, function () {
      menu.funct.apply(menu, arguments);
    }, c, showAll);
    // repaire the memory leak
    if (menu.eventListeners != null) {
      var i = 0;

      while (i < menu.eventListeners.length) {
        if (menu.eventListeners[i + 1]) {
          // menu.eventListeners[i+1] = null
          menu.eventListeners.splice(i, 2);
        } else {
          i += 2;
        }
      }
    }
    menu.addListener('stateChanged', function () {
      elt.setEnabled(menu.enabled);
    });

    return elt;
  };
```
the images below is after repaired.
![image](https://user-images.githubusercontent.com/16235271/42992931-a0c80304-8c3c-11e8-888b-60d7cb6d9d04.png)
@davedwards @alderg 

Version & Environment [版本及环境]
Google Chrome canary 69.0.3482.0 version
window10

Expected behaviour [期望结果]
expect for no memroy leak by editing the graph.

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release. (Listener is not needed if DOM node is removed.)
