### ISSUE TITLE
Documentation Issue: mxGraph.validateGraph

### ISSUE THREAD

**Issue by MojoJojo** [jgraph/mxgraph#23]
Hi,

Not sure if I'm missing something but in the documentation for `validateGraph` method in `mxgraph/javascript/src/js/view/mxGraph.js`, it says:

> This function returns true  if no validation errors exist in the graph.

If you look at the `return` statement for the method (line 8445) it is defined as:

```
return (warning.length > 0 || !isValid) ? warning : null;
```

which means that the method returns either a `null` in case of successful validation or `warning` array in case of failed validations. Or am I missing something?

**Comment by alderg** [comment]
Thanks for the report, this will be fixed in the next release.
