### ISSUE TITLE
Custom Attribute of cell not coming when undo redo

### ISSUE THREAD

**Issue by subbiah89** [jgraph/mxgraph#235]
If I am deleting a vertex, I am updating one attribute in edges.
When I do UNDO I got vertex. But edge attribute not getting in UNDO.
please help on this

**Comment by davidjgraph** [comment]
Please read https://stackoverflow.com/help/how-to-ask for help of how to ask a good question on development issues. In your case, an MCVE is critical, https://stackoverflow.com/help/mcve.
