### ISSUE TITLE
Realtime Interaction with REST API

### ISSUE THREAD

**Issue by lixaotec** [jgraph/mxgraph#239]
Dear friends,

This is not an issue at all, however I could not find material on this.

How to accomplish a behavior to use mxgraph editor to 'create a shape' that requests a REST API and show the shape like a table with the returning data?

What is the way to accomplish it? Plugins? Draw.io? I don´t know where to start.

Thank you .

**Comment by masoudmanson** [comment]
Dear Lixaotec

Did you find any solution to this problem of yours?
I am having the same question and couldn't find any documentation on this one. I can write it on my own but I'd like to know if this hass already been solved or not?!

Thank you.

**Comment by lixaotec** [comment]
Dear @masoudmanson ,

Unfortunatelly not. In fact i gave up using this lib. Instead I´m using diagram-js lib.

Wish you luck
