### ISSUE TITLE
How Can I set the node Level ?

### ISSUE THREAD

**Issue by Thj007** [jgraph/mxgraph#241]
When X and Y are both in the same place of two node, how can I put the first node on top ?
                    var v1 = graph.insertVertex(parent, null, 'Click,', 20, 20, 60, 40);
                    var v2 = graph.insertVertex(parent, null, 'Doubleclick', 20, 20, 60, 60);

**Comment by davidjgraph** [comment]
graph.orderCells(false, v1);
