### ISSUE TITLE
Content-Security-Policy and inline code

### ISSUE THREAD

**Issue by internetscooter** [jgraph/mxgraph#242]
I have been looking at Javascript security and notice that mxgraph (and draw.io) index.html use inline code. 

There are a whole bunch of improvements to security through the [Content-Security-Policy](https://developers.google.com/web/fundamentals/security/csp/)

The first one I am looking at (and need to implement for my stuff to work) is refactoring the inline code as [Inline code is considered harmful](https://developers.google.com/web/fundamentals/security/csp/#inline_code_is_considered_harmful)

Is there any reason that it is implemented this way or is it just legacy? Are there examples of not using inline code about that can be used to update mxgraph/drawio?

**Comment by alderg** [comment]
It is just legacy. CSP is on our roadmap, but we can't give an ETA.

**Comment by internetscooter** [comment]
ok - thanks. Leave the issue open and I will try and submit code for the inline code

**Comment by alderg** [comment]
We use `"default-src 'self' 'unsafe-eval' *.jgraph.com *.draw.io apis.google.com *.googleapis.com drive.google.com api.trello.com js.live.net code.jquery.com www.dropbox.com; style-src 'unsafe-inline' *.draw.io *.jgraph.com; img-src https://* data:; child-src content.googleapis.com accounts.google.com;"` so far, style-src 'unsafe-inline' is OK and 'unsafe-eval' is due to https://github.com/jgraph/mxgraph/blob/v3.9.8/javascript/examples/grapheditor/www/js/Graph.js#L4360 which can only be avoided when adding all JS stencils to app.min.js.

**Comment by internetscooter** [comment]
I am still getting my head around Javascript and now understand how hard it is to pull out the inline code. I discovered though that the lack of Content Security Policy may not be *my* blocker. So I will stop here and will try and revisit this later. Documenting where I go to...

I can add the following to ./javascript/examples/grapheditor/www/index.html. This will add Content-Security-Policy without stopping anything working as-is (**with inlines unchanged**). The localhost:* is required if developers need to run a local instance with the "ant grapheditor" .

```
<head>
        <title>Grapheditor</title>
        <!-- Content-Security-Policy localhost:* is only required during development while running locally -->
        <meta http-equiv="Content-Security-Policy" content="
        default-src 'self' 'unsafe-eval' 'unsafe-inline' localhost:* *.jgraph.com *.draw.io apis.google.com *.googleapis.com drive.google.com api.trello.com js.live.net code.jquery.com www.dropbox.com;
        style-src 'unsafe-inline' localhost:* *.draw.io *.jgraph.com;
        img-src https://* data:;
        child-src content.googleapis.com accounts.google.com;">
```


The other interesting thing I found was [CSP Evaluator](https://csp-evaluator.withgoogle.com/) for sanity checking options. It flags 'unsafe-inline' as unsafe (obviously) but also things like *.googleapis.co and object-src missing. So everything needs to be reviewed to get the options right.

**Comment by davidjgraph** [comment]
CSP is probably outside of the scope of mxGraph in some ways, it's more an app level setting.

That said, we have removed the need for unsafe-eval in the codebase now, see https://github.com/jgraph/drawio/blob/86d47fe5389058dcd3f818efa02e4d6907634034/src/main/webapp/index.html#L162. That's the CSP for the desktop version, it might give some hints for what does need to be allowed.
