### ISSUE TITLE
How can i use mxgraph in vue.js?

### ISSUE THREAD

**Issue by lixin86** [jgraph/mxgraph#243]
In mxGraph 3.9.8 it is still not possible to install it with npm install.....
use <script> also can't use it in my project.
Is there any other way to use mxgraph in Vue?

**Comment by Diaskhan** [comment]
Could u provide code that u include js code?
There must be set in js path of recources! 

Why u cant use script tag in ure project ?

**Comment by Diaskhan** [comment]
<script type="text/javascript">
		mxBasePath = '../src';
	</script>

	
	<script type="text/javascript" src="../src/js/mxClient.js"></script>

**Comment by lixin86** [comment]
@Diaskhan thank you...i tried but that can't use,then i found that the path must be under the same path with index.html.

**Comment by Diaskhan** [comment]
If it helps, u Colud close issue!
