### ISSUE TITLE
export image problem

### ISSUE THREAD

**Issue by lijingjian001** [jgraph/mxgraph#249]
When I export a image from the xml of the graph that cell value is html. The superise is come. Someboy can help me!
![graph 1](https://user-images.githubusercontent.com/12969526/45163359-dd865280-b222-11e8-9b11-387839e4b77e.png)

**Comment by davidjgraph** [comment]
Please submit a bug report.

**Comment by lijingjian001** [comment]
It's not a bug,the xml is generated from web,but the image it's exported from webserver.The server don't have the proper to deal the xml has html.

**Comment by davidjgraph** [comment]
So, what is your question?

**Comment by lijingjian001** [comment]
Is there a mature way to process mxgraph's  XML that contains HTML into pictures?

**Comment by ekoz** [comment]
> Is there a mature way to process mxgraph's XML that contains HTML into pictures?

Hi, u can read demo [mxgraph/examples/web/ExportServlet.java](https://github.com/jgraph/mxgraph/blob/master/java/examples/com/mxgraph/examples/web/ExportServlet.java) to exprot img.

I try to export img which mxgraph node contains html, it's work ok. my code is here:
```
var xmlDoc = mxUtils.createXmlDocument();
var root = xmlDoc.createElement('output');
xmlDoc.appendChild(root);

var xmlCanvas = new mxXmlCanvas2D(root);
var imgExport = new mxImageExport();
imgExport.drawState(graph.getView().getState(graph.model.root), xmlCanvas);

var bounds = graph.getGraphBounds();
var w = Math.ceil(bounds.x + bounds.width + 10);
var h = Math.ceil(bounds.y + bounds.height + 10);

var xml = mxUtils.getXml(root);
new mxXmlRequest($.kbase.ctx + '/export.do?t=' + (new Date()).getTime(), 'format=png&w=' + w +
    '&h=' + h + '&bg=#F9F7ED&xml=' + encodeURIComponent(xml))
    .simulate(document, '_blank');
```
the result is:
![1552966373945](https://user-images.githubusercontent.com/3312512/54579257-9aacff00-4a3d-11e9-961d-2544217a5422.png)

**Comment by kvanapal** [comment]
I cannot find the java class mxImageExport in the source. Am i missing something?
