### ISSUE TITLE
Navigator.pointerEnabled is a non-standard API

### ISSUE THREAD

**Issue by bigdave** [jgraph/mxgraph#25]
Chrome 55.0.2846.4 canary is giving me the following message:

    Navigator.pointerEnabled is a non-standard API added for experiments only. It will be removed in near future.

This appears to be coming from https://github.com/jgraph/mxgraph/blob/master/javascript/src/js/mxClient.js#L230

I'm not sure how or if the removal of this affects the functionality of mxGraph, or when the removal is actually slated, but hopefully this gives you a heads-up on a potential problem in the near future.

**Comment by alderg** [comment]
Thanks for the report, this will be fixed in the next release.
