### ISSUE TITLE
How can i change the edge style.and make it update

### ISSUE THREAD

**Issue by lixin86** [jgraph/mxgraph#251]
i used mxcell.setStyle() to set a cell's style . it is successful,this style's value is changed but this style is not change.how can i updata this style after i change style's value

**Comment by davidjgraph** [comment]
When changing the model, always looks for the method being either on mxGraph or mxGraphModel. The methods on the cell itself tend to be in-place and not perform the updating required.

In your case use [model.setStyle()](https://jgraph.github.io/mxgraph/docs/js-api/files/model/mxGraphModel-js.html#mxGraphModel.setStyle)
