### ISSUE TITLE
mxGraph have different result between Java and Javascript version

### ISSUE THREAD

**Issue by danbenos** [jgraph/mxgraph#252]
I am using mxGraph 3.4 to render diagrams both client-side (Javascript) and server-side (Java). Despite exact same xml structure and stylesheet, the results is quite different, especially that in Java the text does not get wrapped properly.

Javascript result:
![capture](https://user-images.githubusercontent.com/43173272/45358806-e4b6b300-b5ca-11e8-9d5e-0e69a10b1832.PNG)

Java result:
![download](https://user-images.githubusercontent.com/43173272/45358812-e8e2d080-b5ca-11e8-9d39-f19d5171c9c9.png)

(I have the code I use to render the diagram in Java and in Javascript, as well as the stylesheet and diagram xml. But both are quite lengthy so I will add them later if requested.)

[I asked this question in SO, too.](https://stackoverflow.com/questions/52275317/mxgraph-have-different-result-between-java-and-javascript-version)

Is this a bug of older version?

**Comment by davidjgraph** [comment]
Java will render thing differently, that's just the nature of using two different rendering technologies. Java line wraps at different places, might have different font family support, only understands a certain sub-set of CSS in HTML, the list goes on. I wouldn't expect them to be the same.

If you be client and server side image generation that matches, you need something like headless Chrome, which is how we do the server-side image generation in draw.io, https://github.com/jgraph/draw-image-export2
