### ISSUE TITLE
Text no longer wrapping by the cell boundaries when spacing left / right are set

### ISSUE THREAD

**Issue by danbenos** [jgraph/mxgraph#255]
I am trying to render some cells with text inside it using Java version of mxGraph 3.4. The text are horizontally and vertically centered, and wrapped (whiteSpace = wrap, and overflow = visible). If I don't use spacing, the results are perfect.

![image](https://user-images.githubusercontent.com/43173272/45556759-4af63c80-b83c-11e8-8b78-10f3bc5d8440.png)

If I use spacing (spacingLeft in this case), I expect them to still get wrapped by the opposing cell border, like this:

![image](https://user-images.githubusercontent.com/43173272/45556772-53e70e00-b83c-11e8-9f94-6dc1771a89dd.png)

However, it seems that the spacing causes the text to also get wrapped later, way after the border.

![image](https://user-images.githubusercontent.com/43173272/45556783-5d707600-b83c-11e8-88a4-ba7b33f46b50.png)

Same thing happened if I used spacingRight. The width reserved to the text remained the same, and instead of the text starting at left border, they started outside it, seemingly equivalent to the size of spacingRight.

![image](https://user-images.githubusercontent.com/43173272/45556825-7bd67180-b83c-11e8-8e58-3c6ca7e8e990.png)

(I have the code I use to render the diagram in Java, but it's quite lengthy so I will add them later if requested.)

Is this a bug or an intentional behavior? Or maybe I set one of the styles wrong?

**Comment by davidjgraph** [comment]
Unfortunately, we don't provide support for the Swing rendering code, only the JavaScript code. I've updated the README to reflect that.
