### ISSUE TITLE
Multiplicity Max never considered

### ISSUE THREAD

**Issue by Robbenklopper** [jgraph/mxgraph#256]
I'm currently working with the multiplicities in the mxGraph 3.9.8 release for JS. 

What I did is this:

`
graph.multiplicities.push(new mx.mxMultiplicity(
      false, "Output", null, null, 0, 1, "Input",
      "More than one!",
      "Outputs can only be connected with inputs"));
`

The typeError works as expected but the countError never fires.

 I looked through the code and found something in `mxMultiplicity.prototype.check` that seamed suspicious:

`
if (this.countError != null && 
	((this.source && (this.max == 0 || (sourceOut >= this.max))) ||
	(!this.source && (this.max == 0 || (targetIn >= this.max))))) {
		error += this.countError + '\n';
}
`

In both the validation example and my own code `this.source` is always set. So if an error should be triggered when there are more connections to the target as allowed, the error will always be ignored. I may be completely wrong but I think checking `this.target` instead of `!this.source` would fix the problem.

If I'm wrong please let me know what I'm doing wrong

Thanks in advance

**Comment by alderg** [comment]
In the check function, `this.source` is a boolean that specifies if the rule applies to the source or target terminal.
