### ISSUE TITLE
Not able to get Dropped Target Elements

### ISSUE THREAD

**Issue by subbiah89** [jgraph/mxgraph#257]
If two cells are moved simultaneously within editor canvas, and dropped over two another different cells.
I can get the cells which are moved. But I am not able to get the two different dropped target cells..

How we can find all dropped target elements?.

**Comment by davidjgraph** [comment]
Hi. Your question is seeking debugging help but needs more information. The question should be updated to include desired behavior, a specific problem or error, and the shortest code necessary to reproduce the problem.
