### ISSUE TITLE
Feature request: allow text labels to use strikethrough text

### ISSUE THREAD

**Issue by crintin** [jgraph/mxgraph#259]
Currently, mxgraph supports "text-decoration: underline" but there is no way to add "line-through" styling to text. Can this be added to the applications functionality.

**Comment by davidjgraph** [comment]
There is a +1 icon under the original text, please use that and delete your comment

**Comment by elonderin** [comment]
done

**Comment by ashrafteleb** [comment]
Will be available with next release
