### ISSUE TITLE
Strange panning behaviour when ignoreCell is set to true

### ISSUE THREAD

**Issue by ajbond** [jgraph/mxgraph#261]
When panningHandler.ignoreCell is set to true panning with the left mouse button still works even after useLeftButtonForPanning and panningEnabled are both set to false.

**Comment by alderg** [comment]
Use the following override:

```
mxPanningHandler.prototype.isForcePanningEvent = function(me)
{
	return mxEvent.isMultiTouchEvent(me.getEvent());
};
```
