### ISSUE TITLE
Error 404 in mxXmlRequest.js

### ISSUE THREAD

**Issue by leosdad** [jgraph/mxgraph#268]
Hi,

The grapheditor example gives the following error:

**mxXmlRequest.js:356 POST http://localhost:55165/open 404 (Not Found)**

Apparently this occurs when loading the grapheditor.txt resource file.

Please help, thanks.

**Comment by leosdad** [comment]
Also, I create a folder called 'open' the problem is now error 405 (method not allowed). Same thing occurs with your own example: [http://jgraph.github.io/mxgraph/javascript/examples/grapheditor/www/index.html](url)

**Comment by gabriele92** [comment]
Your JAVA servlets are not running. Did you run the project from a JAVA IDE?

**Comment by hamzajis** [comment]
how to run java servlets in localhost then ?
