### ISSUE TITLE
Current npm package published is not working

### ISSUE THREAD

**Issue by epicfaace** [jgraph/mxgraph#269]
For now, you can use this package: https://www.npmjs.com/package/@epicfaace/mxgraph

But I'd like mxgraph to publish their latest version on the official npm repository.

**Comment by CccZss** [comment]
@epicfaace hello, I have a ploblem when i set `mxImageBasePath` and `mxBasePath` as follow
```javascript
var mxgroup = require("@epicfaace/mxgraph")({
  mxImageBasePath: "./src/images",
  mxBasePath: "./src"
});
```
the browser report some errors because the reference path of source : 
![image](https://user-images.githubusercontent.com/21032729/48004403-099f5080-e14c-11e8-98f2-87a97625afb2.png)
How do you set references to resources in the NPM package
( Sorry, my English is very poor )

**Comment by epicfaace** [comment]
Are you using webpack? If you are, you can try this in your webpack configuration:
```
new CopyWebpackPlugin([{ from: "./node_modules/@epicfaace/mxgraph/javascript/src", to: "./mxgraph"}],)
```

and then when initializing mxgraph, I do: 

```
const mxGraphInstance = require("@epicfaace/mxgraph")({
  mxBasePath: "./mxgraph"
});
```

**Comment by mcastelnuovo** [comment]
Hello, i'm using that package and webpack but that solution doesn't works for me. 
![image](https://user-images.githubusercontent.com/44273371/59772546-59b5c800-9282-11e9-9262-ef44e1000cc5.png)

It builds that URL, which doesn't exist, and finally get an empty response error.

Can you help me?

Thanks.

**Comment by epicfaace** [comment]
@mcastelnuovo what are your webpack settings?

**Comment by mcastelnuovo** [comment]
This is my webpack.config file
![image](https://user-images.githubusercontent.com/44273371/59774856-8b309280-9286-11e9-946b-fac3f36ef10a.png)
![image](https://user-images.githubusercontent.com/44273371/59774900-9f748f80-9286-11e9-8ade-495b51ab0b1a.png)

**Comment by epicfaace** [comment]
> @CccZss
> Are you using webpack? If you are, you can try this in your webpack configuration:
> 
> ```
> new CopyWebpackPlugin([{ from: "./node_modules/@epicfaace/mxgraph/javascript/src", to: "./mxgraph"}],)
> ```
> 
> and then when initializing mxgraph, I do:
> 
> ```
> const mxGraphInstance = require("@epicfaace/mxgraph")({
>   mxBasePath: "./mxgraph"
> });
> ```

@mcastelnuovo Make sure you use `CopyWebpackPlugin` as I mentioned in my earlier comment.

**Comment by mcastelnuovo** [comment]
I did and it builds this URL
![image](https://user-images.githubusercontent.com/44273371/59777698-815d5e00-928b-11e9-860d-ec4ee7995363.png)
Then, is recieve the same empty response error.

I'm not sure if is a problem in my configuration, it's a legacy project and i'm still learning how it works, Sorry if i'm not sure about some things.

**Comment by epicfaace** [comment]
I don't see CopyWebpackPlugin in your webpack configuration. 

It might help if you can link to your repo / project so I can see how it's set up.

**Comment by mcastelnuovo** [comment]
This is my entire webpack.config file

`const webpack = require('webpack');
const path = require('path');
const AssetsPlugin = require('assets-webpack-plugin');
const CleanWebpackPlugin = require('clean-webpack-plugin');
const ExtractTextPlugin = require("extract-text-webpack-plugin");
const CopyWebpackPlugin = require("copy-webpack-plugin")

const namePattern = '[name].[chunkhash]';

module.exports = {
    devtool: 'eval-source-map',
    entry: __dirname + '/public/js/app.ts',
    output: {
        filename: namePattern +'.js',
        path: path.resolve(__dirname, 'public/dist'),
        publicPath: '/static/dist/'
    },
    resolve: {
        modules: ['srv/public/js', 'node_modules'],
        extensions: ['.ts', '.js'],
        alias: {
            'backbone': 'lib/backbone',
            'bootstrap': 'lib/bootstrap.min',
            'bootstrap-timepicker': 'lib/bootstrap-timepicker',
            'bootstrap-datetimepicker': 'lib/bootstrap-datetimepicker',
            'bootstrap-slider': 'lib/bootstrap-slider.min',
            'bootstrap-notify': 'lib/bootstrap-notify.min',
            'buffer': 'lib/buffer',
            'd3': 'lib/d3.min',
            'draggabilly':'lib/draggabilly.pkgd.min',
            'dropzone': 'lib/dropzone',
            'gauge':'lib/gauge',
            'highcharts': 'lib/highstock/highstock.src',
            'highstock': 'lib/highstock/highstock.src',
            'highstock.nodata': 'lib/highstock/modules/no-data-to-display',
            'highcharts.exporting': 'lib/highstock/modules/exporting',
            'highcharts.export.csv': 'lib_modified/highstock-exporting/export-csv',
            'highcharts.heatmap': 'lib/highstock/modules/heatmap',
            'masonry': 'lib/masonry.min',
            'moment': "lib/moment.min",
            'moment-timezone': "lib/moment-timezone.min",
            'operative': 'lib/operative.min',
            'packery':'lib_modified/packery.pkgd',
            'promise': "lib/Promise.min",
            'select2': "lib/select2.min",
            'select2-matcher': "lib/select2-matcher",
            'stacktrace': "lib/stacktrace.min",
            'templates': 'templates/',
            'toposort': 'lib/toposort',
            'underscore': 'lodash/lodash.js',
            'validator': "lib/validator.min"
        }
    },
    module: {
        rules: [
            {test: /\.html$/, use: ["html-loader"]},
            {test: /\.(jpe?g|png|gif|woff|woff2|eot|ttf|svg)$/, use: ['url-loader?limit=8192']},
            {test: /\.ts$/, loader: 'ts-loader'},
            // Extract css files
            {
               test: /\.less$/,
               loader: ExtractTextPlugin.extract({ fallback: "style-loader", use: "css-loader!less-loader"})
           }
        ],
        loaders: [
            {test: /bootstrap-slider/, loader: 'imports?bootstrap'},
            {test: /operative/, loader: 'exports?operative'},
            {test: /promise/, loader: 'exports?promise'},
            {test: /moment-timezone/, loader: 'imports?moment'},
            {test: /highstock\.nodata/, loader: 'imports?highstock'},
            {test: /highcharts\.exporting/, loader: 'imports?highstock'},
            {test: /highcharts\.export\.csv/, loader: 'imports?highstock,highcharts.exporting'},
            {test: /highcharts\.heatmap/, loader: 'imports?highstock'},
        ]
    },
    plugins: [
        new CleanWebpackPlugin([path.resolve(__dirname, 'public/dist')]),
        new webpack.ProvidePlugin({
            $: 'jquery',
            jQuery: 'jquery',
            Highcharts: 'lib/highstock/highstock.src',
            Dropzone: 'lib/dropzone',
        }),
        // Vendor Splitting
        new webpack.optimize.CommonsChunkPlugin({
            name: 'vendor',
            minChunks: function (module) {
                return module.context && (
                        module.context.indexOf('node_modules') !== -1 || module.context.indexOf('lib') !== -1
                    )
            }
        }),
        new ExtractTextPlugin('[name].[hash].css'),
        new AssetsPlugin({path: __dirname, prettyPrint: true}),
        new CopyWebpackPlugin([{ from: "./node_modules/@epicfaace/mxgraph/javascript/src", to: "./mxgraph"}],)
        
    ]
};`

**Comment by mcastelnuovo** [comment]
` const webpack = require('webpack');
const path = require('path');
const AssetsPlugin = require('assets-webpack-plugin');
const CleanWebpackPlugin = require('clean-webpack-plugin');
const ExtractTextPlugin = require("extract-text-webpack-plugin");
const CopyWebpackPlugin = require("copy-webpack-plugin")

const namePattern = '[name].[chunkhash]';

module.exports = {
    devtool: 'eval-source-map',
    entry: __dirname + '/public/js/app.ts',
    output: {
        filename: namePattern +'.js',
        path: path.resolve(__dirname, 'public/dist'),
        publicPath: '/static/dist/'
    },
    resolve: {
        modules: ['srv/public/js', 'node_modules'],
        extensions: ['.ts', '.js'],
        alias: {
            'backbone': 'lib/backbone',
            'bootstrap': 'lib/bootstrap.min',
            'bootstrap-timepicker': 'lib/bootstrap-timepicker',
            'bootstrap-datetimepicker': 'lib/bootstrap-datetimepicker',
            'bootstrap-slider': 'lib/bootstrap-slider.min',
            'bootstrap-notify': 'lib/bootstrap-notify.min',
            'buffer': 'lib/buffer',
            'd3': 'lib/d3.min',
            'draggabilly':'lib/draggabilly.pkgd.min',
            'dropzone': 'lib/dropzone',
            'gauge':'lib/gauge',
            'highcharts': 'lib/highstock/highstock.src',
            'highstock': 'lib/highstock/highstock.src',
            'highstock.nodata': 'lib/highstock/modules/no-data-to-display',
            'highcharts.exporting': 'lib/highstock/modules/exporting',
            'highcharts.export.csv': 'lib_modified/highstock-exporting/export-csv',
            'highcharts.heatmap': 'lib/highstock/modules/heatmap',
            'masonry': 'lib/masonry.min',
            'moment': "lib/moment.min",
            'moment-timezone': "lib/moment-timezone.min",
            'operative': 'lib/operative.min',
            'packery':'lib_modified/packery.pkgd',
            'promise': "lib/Promise.min",
            'select2': "lib/select2.min",
            'select2-matcher': "lib/select2-matcher",
            'stacktrace': "lib/stacktrace.min",
            'templates': 'templates/',
            'toposort': 'lib/toposort',
            'underscore': 'lodash/lodash.js',
            'validator': "lib/validator.min"
        }
    },
    module: {
        rules: [
            {test: /\.html$/, use: ["html-loader"]},
            {test: /\.(jpe?g|png|gif|woff|woff2|eot|ttf|svg)$/, use: ['url-loader?limit=8192']},
            {test: /\.ts$/, loader: 'ts-loader'},
            // Extract css files
            {
               test: /\.less$/,
               loader: ExtractTextPlugin.extract({ fallback: "style-loader", use: "css-loader!less-loader"})
           }
        ],
        loaders: [
            {test: /bootstrap-slider/, loader: 'imports?bootstrap'},
            {test: /operative/, loader: 'exports?operative'},
            {test: /promise/, loader: 'exports?promise'},
            {test: /moment-timezone/, loader: 'imports?moment'},
            {test: /highstock\.nodata/, loader: 'imports?highstock'},
            {test: /highcharts\.exporting/, loader: 'imports?highstock'},
            {test: /highcharts\.export\.csv/, loader: 'imports?highstock,highcharts.exporting'},
            {test: /highcharts\.heatmap/, loader: 'imports?highstock'},
        ]
    },
    plugins: [
        new CleanWebpackPlugin([path.resolve(__dirname, 'public/dist')]),
        new webpack.ProvidePlugin({
            $: 'jquery',
            jQuery: 'jquery',
            Highcharts: 'lib/highstock/highstock.src',
            Dropzone: 'lib/dropzone',
        }),
        // Vendor Splitting
        new webpack.optimize.CommonsChunkPlugin({
            name: 'vendor',
            minChunks: function (module) {
                return module.context && (
                        module.context.indexOf('node_modules') !== -1 || module.context.indexOf('lib') !== -1
                    )
            }
        }),
        new ExtractTextPlugin('[name].[hash].css'),
        new AssetsPlugin({path: __dirname, prettyPrint: true}),
        new CopyWebpackPlugin([{ from: "./node_modules/@epicfaace/mxgraph/javascript/src", to: "./mxgraph"}],)
        
    ]
}; `

**Comment by mcastelnuovo** [comment]
[webpack.config.txt](https://github.com/jgraph/mxgraph/files/3314341/webpack.config.txt)

**Comment by mcastelnuovo** [comment]
I can't share the repo but this is my entire webpack.config file [webpack.config.txt](https://github.com/jgraph/mxgraph/files/3314346/webpack.config.txt)

**Comment by epicfaace** [comment]
@mcastelnuovo sorry, don't think I can help unless you share the entire repo (or at least a minimal reproduction) so I can get the entire context.
