### ISSUE TITLE
jGraph - avoid edge collision and fixed vertexes

### ISSUE THREAD

**Issue by robertmoral** [jgraph/mxgraph#271]
Hi, I would like to ask about 2 questions about issue I dont know how to solve.

1. I have static vertexes and need to display edges to avoid collision edges and vertexes.
2. Is it possible to apply layout only on specific cell group? Cos I need in one group vertexes in column and these vertexes connect to vertexes in other group. In specific group order of vertexes could be changed.

I thought about solution to override mxStackLayout, but there is not support to avoid edge collision.

Thank you for advance.

![untitled](https://user-images.githubusercontent.com/31476973/48271904-ad834780-e43d-11e8-9d3e-fe7fd71947de.png)

**Comment by davidjgraph** [comment]
This looks like Java, mxGraph is the JavaScript client.
