### ISSUE TITLE
reopen graph xml, key handler not working

### ISSUE THREAD

**Issue by shaw1111** [jgraph/mxgraph#273]
hi,
i reopened graph xml with following codes:

> let doc = mxUtils.parseXml(graphXml);
let codec = new mxCodec(doc);
let graph = this.graph;
codec.decode(doc.documentElement, graph.getModel());

not only the 'load' or the 'keyhandler' way doesn't work, however, the toolbar thatwhen clicked works well.

> // var config = mxUtils.load('./assets/mxgraph/editors/config/keyhandler-commons.xml').getDocumentElement();
// editor.configure(config);
var keyHandler = new mxKeyHandler(graph);
keyHandler.bindKey(46, function (evt) {
if (graph.isEnabled()) {
//graph.removeCells();
graph.container.focus();
editor.execute("delete")
}
});

the event has been triggered, but the callback method: cellsRemoved(cells) cells is []

I found the graph container related is old graph, not latest. so is anything else to do with key handler

**Comment by shaw1111** [comment]
resolved。 the keyhandler's callback graph is not latest

**Comment by ekoz** [comment]
> resolved。 the keyhandler's callback graph is not latest

Hi @shaw1111 , how to get the lastest graph ?

**Comment by ekoz** [comment]
the correct solution is #277
