### ISSUE TITLE
Styles are applied newly dropped cells

### ISSUE THREAD

**Issue by subbiah89** [jgraph/mxgraph#274]
If I changed color of the one cell in canvas. to green, then that color is applied to newly drag and drop cells also.

**Comment by davidjgraph** [comment]
Do you have a question?

**Comment by subbiah89** [comment]
yes. It am not sure it is issue or not.
But I want to avoid that.  If style is applied it will not come for newly added cells. Could you plz help on this

**Comment by davidjgraph** [comment]
No question asked.
