### ISSUE TITLE
Custom button for Export/Save Graph Editor

### ISSUE THREAD

**Issue by esdglo** [jgraph/mxgraph#276]
I've created a layout to wrap your Graph Editor, it's working really great and I love the library. But there are two things I couldn't find on the documentation:

- how can I use a custom button to export/save my graph
- it  only possible to export in XML? No json, or something else?

**Comment by cnanyi** [comment]
you can find this in example:
path to mxgraph/java/examples/com/mxgraph/examples/web/ExportServlet.java
