### ISSUE TITLE
mxKeyHandler not working when React component is remounted

### ISSUE THREAD

**Issue by stayko16** [jgraph/mxgraph#277]
I'm using **mxGraph** in a React Single Page Application and instantiating a new **mxKeyHandler** in **componentDidMount**. I also invoke its destroy method in **componentWillUnmount**. It all works fine the first time you visit the page that has the **mxGraph** component, but if I navigate away to a different page and come back (without a page refresh), it no longer works.  

```
componentDidMount() {
    this.editor = new mxEditor();
    this.editor.setGraphContainer(this.mxGraphRef.current);
    ...... 
    this.keyHandler = new mxKeyHandler(this.editor.graph);
    this.keyHandler.bindKey(46, evt => {
      this.editor.graph.removeCells();
    });
}

componentWillUnmount() {
    this.keyHandler.destroy();
    this.editor.destroy();
}
```
Any advice as to what I'm doing wrong?

**Comment by davidjgraph** [comment]
I'll leave this up, but none of us have used React, so you won't get an answer from the core team. You might want to try StackOverflow, there is an mxGraph tag on there.

**Comment by stayko16** [comment]
It has something to do with the graph losing focus when coming back to the page. If I double click on one of the cells to start editing the text inside, I can then delete it... 

I've tried adding the following line before the mxKeyHandler initialisation but it still didn't work:

`this.editor.graph.container.focus();`

**Comment by stayko16** [comment]
Ok, the solution was to add the following 2 lines:

```
this.editor.graph.container.setAttribute('tabindex', '-1');
this.editor.graph.container.focus();
```
As described here: [https://jgraph.github.io/mxgraph/docs/known-issues.html](https://jgraph.github.io/mxgraph/docs/known-issues.html)
