### ISSUE TITLE
Missing .sln file from dotnet side

### ISSUE THREAD

**Issue by papyr** [jgraph/mxgraph#28]
Hi in the samples there supposed to be a .sln file to bind all the projects in the visual studio project, but its missing.

In the help it [shows here](http://jgraph.github.io/mxgraph/dotnet/) but missing [here ](https://github.com/jgraph/mxgraph/tree/master/dotnet)

**Comment by alderg** [comment]
See https://github.com/jgraph/mxgraph/blob/master/mxgraph-dotnet.sln
