### ISSUE TITLE
Save and save As are  not working. Can you please help me in this?

### ISSUE THREAD

**Issue by Nisha-Yadav-1** [jgraph/mxgraph#280]
I want to change diagram property as well. 

Thanks in advance!

**Comment by davidjgraph** [comment]
Please write a bug report, see http://testthewebforward.org/docs/bugs.html for details on how to report a bug.

If you have a general usage question, please submit to Stackoverflow using the "mxgraph" tag, https://stackoverflow.com/questions/tagged/mxgraph

**Comment by Nisha-Yadav-1** [comment]
Thanks! I post the problem as you guide.
