### ISSUE TITLE
Integrate mxgraph in Django?

### ISSUE THREAD

**Issue by snape6666** [jgraph/mxgraph#283]
Hey guys,
i was wondering if its possible to integrate mxgraph in a django app? If so, how would i do that?

Any experience with that?

Thx in advance!

**Comment by alicelebi61** [comment]
Hi!

I  have some experience about it. 

First of all. You must add to your static folder path under settings.py
```
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
```
Secondly,

You add mxgraph files under your static folder.

![image](https://user-images.githubusercontent.com/46648612/56362323-37f08400-61f2-11e9-8d90-a594b00fdc1a.png)

End,

Add scripts paths your html file

```
<script type="text/javascript">
		mxBasePath = '{% static 'mxgraph-master/javascript/src' %}';
</script>
<script type="text/javascript" src="{% static 'mxgraph-master/javascript/src/js/mxClient.js' %} "></script>
```


It works for me.

![image](https://user-images.githubusercontent.com/46648612/56362511-b8af8000-61f2-11e9-967a-b99b49601124.png)

**Comment by johanovic** [comment]
@alicelebi61 I am assuming you still implemented the API to save the data afterwards, right? Do you have a sample of that API?
