### ISSUE TITLE
bug: child edge to container rendered wrong when container entered

### ISSUE THREAD

**Issue by adamfk** [jgraph/mxgraph#284]
See gif below for easy steps to reproduce. Note that the container is the stock draw.io swimlane container object.

![child-edge-to-container-infinity](https://user-images.githubusercontent.com/274012/50813949-95189780-12dd-11e9-8133-66b77248a0b8.gif)

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
