### ISSUE TITLE
bug: deleting attached vertex in entered group layout issue

### ISSUE THREAD

**Issue by adamfk** [jgraph/mxgraph#285]
See below gif. I can reproduce this in mxGraph 3.9.12 as well.
![deleting-attached-vertex-in-entered-group-layout-issue](https://user-images.githubusercontent.com/274012/50992461-e17df600-14dc-11e9-8f33-04709d73227c.gif)

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
