### ISSUE TITLE
mxgraph: Export PNG image using PHP

### ISSUE THREAD

**Issue by nexiocloud** [jgraph/mxgraph#289]
Hi all,

I'm trying to export a graph as image using the below code but it is not working for me. The resulted file is not readable.

Can someone help me?

thanks

      <?php
      include_once("../src/mxServer.php");

      $xml = mxUtils::readFile("diagrams/graphmodel.xml");
      $doc = mxUtils::parseXml($xml);

     $model = new mxGraphModel();
     $graph = new mxGraph($model);

     $codec = new mxCodec($doc);
     $codec->decode($doc->documentElement, $graph->getModel());

     $image = $graph->createImage(null, "#FFFFFF");

    imageInterlace($image, 1);
    imageColorTransparent($image, imageColorAllocate($image, 255, 255, 255));

    header("Content-Type: image/png");
    echo mxUtils::encodeImage($image, 'png');
    ?>

_Originally posted by @alderg in https://github.com/jgraph/mxgraph/issues/89#issuecomment-448261948_

**Comment by davidjgraph** [comment]
We don't properly support PHP image export. I would try the Java backend, if you must use one, or the Node.js implementation.
