### ISSUE TITLE
License info

### ISSUE THREAD

**Issue by ycintre** [jgraph/mxgraph#29]
Hi,
The LICENSE file indicate that the project is under Apache 2 license but the JS user manual (https://github.com/jgraph/mxgraph/blob/master/docs/manual.html#L132) refers to a commercial license http://www.jgraph.com/mxlicense.html

Looking at the commit history I can guess that this is an old doc that haven't been updated yet, but can you confirm that the current license is Apache 2?

**Comment by davidjgraph** [comment]
It's Apache 2.
