### ISSUE TITLE
integrate mxgraph-js in grafana plugin

### ISSUE THREAD

**Issue by algenty** [jgraph/mxgraph#290]
Hi,

I am novice with javascript, i am not a devloper but an production ingenneer.
i try to integrate mxgraph, first with mxgraph, and now with mxgraph-js.
But in grafana, i have an error.
Plugin component error TypeError: t.setAttribute is not a function
    at Object.eval [as disableContextMenu] (mxgraph-js.js:2435)
    at FlowchartCtrl.initializeMxgraph (flowchartControl.js:133)

`            disableContextMenu: function() {
                return mxClient.IS_IE && ("undefined" == typeof document.documentMode || document.documentMode < 9) ? function(t) {
                    mxEvent.addListener(t, "contextmenu", function() {
                        return !1
                    })
                } : function(t) {
                    t.setAttribute("oncontextmenu", "return false;")
                }
            }(),`

You can found flowchartControl.js at https://github.com/algenty/grafana-flowcharting/blob/master/src/flowchartControl.js

Help me, please, i dont understand why its work in html, not in import ts files

Best regards
Arnaud

**Comment by davidjgraph** [comment]
I would try StackOverflow, we have no experience with TypeScript.
