### ISSUE TITLE
JGraphX: label rotation support

### ISSUE THREAD

**Issue by VsevolodGolovanov** [jgraph/mxgraph#292]
mxConstants.STYLE_ROTATION in JGraphX affects shapes, but not their labels. Should affect labels too, as it does in mxGraph.

![rotation](https://user-images.githubusercontent.com/8070317/52709705-88ebbe00-2f9e-11e9-8fd5-176e0a1353e0.png)

**Comment by VsevolodGolovanov** [comment]
I've been looking into implementing this. Obviously the painting code needs to be updated in mxDefaultTextShape and mxHtmlTextShape.
Secondarily, mxUtils.getScaledLabelBounds, mxGraph.getPreferredSizeForCell and mxGraphView.getWordWrapWidth should take rotation into account. Is that it?

**Comment by davidjgraph** [comment]
Unfortunately, we don't actively develop JGraphX, we closed down the issue tracker in that project for this reason.

**Comment by VsevolodGolovanov** [comment]
I suggest updating jgraphx/README.md to reflect its current status.

**Comment by davidjgraph** [comment]
Done.
