### ISSUE TITLE
Cannot draw correct shape with style="triangle" (style="shape=triangle")

### ISSUE THREAD

**Issue by loongmxbt** [jgraph/mxgraph#296]
I draw graph with draw.io and export the XML file. The XML looks like
``` xml
<mxCell id="h8RaVuQXiskC9_7859E5-3" value="G1" style="ellipse;whiteSpace=wrap;html=1;aspect=fixed;fillColor=#f8cecc;strokeColor=#b85450;" vertex="1" parent="1"><mxGeometry x="80" y="76" width="35" height="35" as="geometry"/></mxCell>
```

But my xml decode cannot draw correctly with `style="ellipse;"`, it draws the ellipse and triangle into rect.

I need to manually modify it to`style="shape=ellipse;"` and `style="shape=triangle;"` and so on.

What am I missing?

``` js
    var graph = new mxGraph(container);
    
    graph.setEnabled(false);
    graph.setPanning(true);
    graph.setTooltips(true);
    graph.panningHandler.useLeftButtonForPanning = true;
    
    // Adds a highlight on the cell under the mousepointer
    new mxCellTracker(graph);
    graph.getModel().beginUpdate();
    try
    {	
      // Loads the custom file format (TXT file)
      // parse(graph, 'fileio.txt');

      // Loads the mxGraph file format (XML file)
      read(graph, '/xml/3BusGrid.xml');
                
      // Gets the default parent for inserting new cells. This
      // is normally the first child of the root (ie. layer 0).
      var parent = graph.getDefaultParent();

      // Executes the layout
      // layout.execute(parent);
    }
    finally
    {
      // Updates the display
      graph.getModel().endUpdate();
    }

```

Wish some help, thanks!

**Comment by alderg** [comment]
Use this stylesheet https://github.com/jgraph/drawio/blob/master/src/main/webapp/styles/default.xml

**Comment by loongmxbt** [comment]
@alderg Thanks a lot!
I looked into https://jgraph.github.io/mxgraph/docs/js-api/files/io/mxStylesheetCodec-js.html 
But cannot find an example to use it
`codec.decode = function( dec,node,into )`  does it mean:
```
function readStyleSheet(graph, filename)
{
  var req = mxUtils.load(filename);
  var root = req.getDocumentElement();
  var dec = new mxStylesheetCodec(root.ownerDocument);
  dec.decode(dec, root, graph.getModel())
}
```

**Comment by ilmimris** [comment]
> @alderg Thanks a lot!
> I looked into https://jgraph.github.io/mxgraph/docs/js-api/files/io/mxStylesheetCodec-js.html
> But cannot find an example to use it
> `codec.decode = function( dec,node,into )` does it mean:
> 
> ```
> function readStyleSheet(graph, filename)
> {
>   var req = mxUtils.load(filename);
>   var root = req.getDocumentElement();
>   var dec = new mxCodec(root.ownerDocument);
>   dec.decode(dec, root, graph.getModel())
> }
> ```

I try this, but it ain't works. I think the way to apply the style sheet is `graph.getStylesheet()` **not** `graph.getModel()`. So, I modified that function to be like this:
```
/**
 * Loads the stylesheet for this graph.
 */
var loadStylesheet = function (graph, url) {
    var node = (graph.themes != null)
        ? graph.themes[graph.defaultThemeName] : mxUtils.load(url).getDocumentElement();

    if (node != null) {
        var dec = new mxCodec(node.ownerDocument);
        dec.decode(node, graph.getStylesheet());
    }
};``
