### ISSUE TITLE
How can I change the link label position?

### ISSUE THREAD

**Issue by yavasolpatron** [jgraph/mxgraph#297]
I want to establish a label to link, which position must be near the arrow. (java mxgraph)

VERTEX1 ----------------EdgeLabel-->VERTEX2

**Comment by yavasolpatron** [comment]
NO ONE TO HELP??? @davidjgraph

**Comment by yavasolpatron** [comment]
What happened? I asked a question to @davidjgraph . And you did not answer me, but also closed this issue...
Can you help me ?

**Comment by yavasolpatron** [comment]
Hey @davidjgraph, why are you deleting my comments?

**Comment by yavasolpatron** [comment]
Shit

**Comment by yavasolpatron** [comment]
answer my question

**Comment by yavasolpatron** [comment]
> I want to establish a label to link, which position must be near the arrow. (java mxgraph)
> 
> VERTEX1 ----------------EdgeLabel-->VERTEX2

WHY DID YOU CLOSE THIS ISSUE??? CAN YOU HELP ME?

**Comment by yavasolpatron** [comment]
>

**Comment by yavasolpatron** [comment]
` `

**Comment by yavasolpatron** [comment]
[ ](url)

**Comment by davidjgraph** [comment]
Issues are for JavaScript only, not Java.

**Comment by yavasolpatron** [comment]
ok

**Comment by yavasolpatron** [comment]
why did not you answer, but delete ?

**Comment by davidjgraph** [comment]
Shouting at specific developers is not acceptable behaviour. See https://gist.github.com/richhickey/1563cddea1002958f96e7ba9519972d9, to quote:

"As a user of something open source you are not thereby entitled to anything at all. You are not entitled to contribute. You are not entitled to features. You are not entitled to the attention of others. You are not entitled to having value attached to your complaints. You are not entitled to this explanation."

**Comment by yavasolpatron** [comment]
yea ok
