### ISSUE TITLE
Vue use import mxGraph undefined

### ISSUE THREAD

**Issue by jiangdefu** [jgraph/mxgraph#300]
First I  install mxGraph that version is 3.9.12 in vue project by command  `npm install  mxgraph`,
then I  import mxgraph object in vue page use code `import {
    mxGraph,
    mxObjectCodec,
    mxEvent,
    mxEffects,
    mxClient,
    mxUtils,
    mxEditor,
    mxConstants,
    mxGraphHandler,
    mxGuide,
    mxEdgeHandler,
} from 'mxgraph';`
last i use code ` console.log(mxBasePath);
            console.log(mxClient.basePath);
            console.log(mxUtils);` print to console and all result is  undefined

[view all code
](https://github.com/jiangdefu/ThinkJS-RABC/blob/master/editAbilityMap.vue)

**Comment by Diaskhan** [comment]
Try this 
https://github.com/jgraph/mxgraph/issues/243

**Comment by become-iron** [comment]
Look at my answer:
https://github.com/jgraph/mxgraph/issues/175#issuecomment-482008896
