### ISSUE TITLE
menu.additem and mxCodec.decode used in react not work

### ISSUE THREAD

**Issue by zhang52098Cby** [jgraph/mxgraph#301]
I‘ve used mxgraph in vue, because ES5 support function calls between different files, but react with ES6 is different, I installed mxgraph-js, and most functions can work well, but mxCodec.decode and menu.additem   are wrong.
const apprXml=<...> ; xml file
const doc=mxUtils.parseXml(apprXml);
const dec=new mxCodec(doc);
dec.decode(doc.document,editor.graph.getmodel()); editor was defined  when initializing graph
 cannot decode the doc and put the values in editor

**Comment by JonasJonny** [comment]
We have the same problem.
We already tried many "options" but without any luck.

A.
```
var xmlDocument = mxUtils.parseXml('<mxGraphModel><root><mxCell id="0"/><mxCell id="1" parent="0"/><mxCell id="v1" value="v1" vertex="1" parent="1"><mxGeometry width="80" height="30" as="geometry"/></mxCell><mxCell id="v2" value="v2" vertex="1" parent="1"><mxGeometry width="80" height="30" as="geometry"/></mxCell><mxCell id="e1" value="e1" edge="1" parent="1" source="v1" target="v2"><mxGeometry relative="1" as="geometry"/></mxCell></root></mxGraphModel>');

var decoder = new mxCodec(xmlDocument);
var node = xmlDocument.documentElement;
decoder.decode(node, graph.getModel());

var layout = new mxHierarchicalLayout(graph);
layout.execute(graph.getDefaultParent());
```
Result:
```
<g><g></g><g></g><g></g><g></g></g>
```
B.
```
const xml = `<root>
        <mxCell id="0"/>
        <mxCell id="1" parent="0"/>
        <mxCell id="2" style="" vertex="1" parent="1">
            <mxGeometry x="0" y="0" width="100" height="40" as="geometry"/>
          </mxCell>
        </root>`;

        // graph.model.clear();
        const doc = mxUtils.parseXml(xml);
        const { documentElement } = doc;
        const codec = new mxCodec(doc);
        const decode = codec.decode(doc.documentElement);
        let elt = doc.documentElement.firstChild;
        const cells = [];

        while (elt != null) {
          cells.push(codec.decodeCell(elt));
          graph.refresh();
          elt = elt.nextSibling;
        }

        graph.addCells(cells);

        const layout = new mxFastOrganicLayout(graph);
        layout.execute(graph.getDefaultParent());
```
Result:
```
<g><g></g><g><g style="visibility: hidden;"></g></g><g></g><g></g></g>
```

Can @alderg, @davidjgraph or anyone help?

If there is no easy answer we will try `insertVertex/insertEdge` which should work fine with #React but also looks a bit complicated.

**Comment by alderg** [comment]
I have never used react and I'm not going to given it seems to block access to vanilla JS.

**Comment by yangdailin** [comment]
> We have the same problem.
> We already tried many "options" but without any luck.
> 
> A.
> 
> ```
> var xmlDocument = mxUtils.parseXml('<mxGraphModel><root><mxCell id="0"/><mxCell id="1" parent="0"/><mxCell id="v1" value="v1" vertex="1" parent="1"><mxGeometry width="80" height="30" as="geometry"/></mxCell><mxCell id="v2" value="v2" vertex="1" parent="1"><mxGeometry width="80" height="30" as="geometry"/></mxCell><mxCell id="e1" value="e1" edge="1" parent="1" source="v1" target="v2"><mxGeometry relative="1" as="geometry"/></mxCell></root></mxGraphModel>');
> 
> var decoder = new mxCodec(xmlDocument);
> var node = xmlDocument.documentElement;
> decoder.decode(node, graph.getModel());
> 
> var layout = new mxHierarchicalLayout(graph);
> layout.execute(graph.getDefaultParent());
> ```
> 
> Result:
> 
> ```
> <g><g></g><g></g><g></g><g></g></g>
> ```
> 
> B.
> 
> ```
> const xml = `<root>
>         <mxCell id="0"/>
>         <mxCell id="1" parent="0"/>
>         <mxCell id="2" style="" vertex="1" parent="1">
>             <mxGeometry x="0" y="0" width="100" height="40" as="geometry"/>
>           </mxCell>
>         </root>`;
> 
>         // graph.model.clear();
>         const doc = mxUtils.parseXml(xml);
>         const codec = new mxCodec(doc.documentElement);
>         codec.decode(doc.documentElement);
>         let elt = doc.documentElement.firstChild;
>         const cells = [];
> 
>         while (elt != null) {
>           cells.push(codec.decodeCell(elt));
>           graph.refresh();
>           elt = elt.nextSibling;
>         }
> 
>         graph.addCells(cells);
> 
>         const layout = new mxFastOrganicLayout(graph);
>         layout.execute(graph.getDefaultParent());
> ```
> 
> Result:
> 
> ```
> <g><g></g><g><g style="visibility: hidden;"></g></g><g></g><g></g></g>
> ```
> 
> Can @alderg, @davidjgraph or anyone help?
> 
> If there is no easy answer we will try `insertVertex/insertEdge` which should work fine with #React but also looks a bit complicated.

you should add  
'window['mxGraphModel'] = mxGraphModel;
window['mxGeometry'] = mxGeometry;
before 
'let doc = mxUtils.parseXml(this.props.data.model);
let codec = new mxCodec(doc);
codec.decode(doc.documentElement, graph.getModel());'

I found that the decode method resolve xml need windows param
