### ISSUE TITLE
Cannot use imageAligh on createVertexTemplateEntry

### ISSUE THREAD

**Issue by mebitek** [jgraph/mxgraph#307]

**Comment by mebitek** [comment]
Hi,
i'm trying to use grapheditor as tempalte for my applciation and I have some problems using the imageAligh attribute for my clipart elements. how do I change the label position?

**Comment by davidjgraph** [comment]
https://stackoverflow.com/help/how-to-ask

**Comment by mebitek** [comment]
@davidjgraph change the question, hope it's better now

**Comment by mebitek** [comment]
I edited Sidebar.js as:

```
Sidebar.prototype.addImagePalette = function(id, title, prefix, postfix, items, titles, tags)
{
	var showTitles = titles != null;
	var fns = [];
	
	for (var i = 0; i < items.length; i++)
	{
		(mxUtils.bind(this, function(item, title, tmpTags)
		{
			if (tmpTags == null)
			{
				var slash = item.lastIndexOf('/');
				var dot = item.lastIndexOf('.');
				tmpTags = item.substring((slash >= 0) ? slash + 1 : 0, (dot >= 0) ? dot : item.length).replace(/[-_]/g, ' ');
			}

			fns.push(this.createVertexTemplateEntry('image;imageBorder=blue;html=1;labelBackgroundColor=#ffffff;image=' + prefix + item + postfix,
				this.defaultImageWidth, this.defaultImageHeight, (titles != null) ? titles[i] : null, title, title != null, null, this.filterTags(tmpTags)));
		}))(items[i], (titles != null) ? titles[i] : null, (tags != null) ? tags[items[i]] : null);
	}

	this.addPaletteFunctions(id, title, false, fns);
};
```

but the label is still in the bottom of the image

**Comment by ashrafteleb** [comment]
This is not a bug, please have a look at the images example (https://devhost.jgraph.com/mxgraph2/javascript/examples/images.html)

One possible style is:
image=stencils/clipart/Lock_128x128.png;imageAlign=left;verticalAlign=middle;align=right;imageVerticalAlign=middle

Note: Don't use the image shape as indicated in the above style
