### ISSUE TITLE
How to customize mxgraph toolbar and properties panel

### ISSUE THREAD

**Issue by bahmansh** [jgraph/mxgraph#308]
I'm writing an web application. I have workflow in my application, means that we should create our workflow and extract data from it and save in database.

I chose mxgraph for designing workflow. For now I need to customize it for my project: 1. custom toolbar that just contain some tools for bpmn and workflow. 2. ability for double click on elements and open modal for creating element attributes.

How can I do this? I read documents but was not clear for me.

@alderg
@davidjgraph

**Comment by davidjgraph** [comment]
Closing, you have an answer at https://stackoverflow.com/questions/55119807/how-to-customize-mxgraph-toolbar-and-properties-panel
