### ISSUE TITLE
React?

### ISSUE THREAD

**Issue by clearly** [jgraph/mxgraph#31]
Any plans to support React? Ever? From what I read there seems to be a philosophical bent to not support a specific framework. Just wanted to gain clarity.

**Comment by alderg** [comment]
Is there a problem when using it with React?

**Comment by davidjgraph** [comment]
mxGraph is platform frameworks, which isn't the the same thing as not supporting any frameworks. The idea is to not put anything in it that is too "opinionated" in terms of framework support. Why is it you feel it's incompatible with React?
