### ISSUE TITLE
Tooltip doesn't show

### ISSUE THREAD

**Issue by deyarelo** [jgraph/mxgraph#311]
Hello everybody,
I use to mxgraph-js. I want to show **tooltip**, so I coded as below. But tooltip **doesn't show**. What is the _wrong_. 

```
graph.setTooltips(true);
graph.getTooltipForCell = function(cell)
{
    return 'this is a tooltip';
}
```

**Comment by deyarelo** [comment]
I tried to below code, 

```
graph.setTooltips(true);
graph.getTooltip = function(state){
   var cell = state.cell;
   var model = this.getModel(),

   if(model.isEdge(cell)){
      var source = this.getLabel(model.getTerminal(cell,true));
      var target = this.getLabel(model.getTerminal(cell,false));
      return source + "->" + target;
   else return this.getLabel(cell);
      
```

**But tooltip is not show.**

**Comment by deyarelo** [comment]
@davidjgraph @davedwards @DennisTUE  can you help me

**Comment by deyarelo** [comment]
https://stackoverflow.com/questions/55256690/mxgraph-tooltip-doesnt-show

**Comment by deyarelo** [comment]
Hello, @davidjgraph can you help me to solve this problem

**Comment by agentS** [comment]
I am experiencing exactly the same issue. My version of `mxgraph-js` is 1.0.1 and I'm creating the graph inside a React application.

For further details see my code below:

```javascript
createGraph(container) {
    // Create and Configure Graph
    let graph = new mxGraph(container);
    // ...
    graph.setTooltips(true, TOOLTIP_POPUP_TIME);
    graph.getTooltipForCell = this.handleHover;
}

handleHover = (cell) => {
    // ...
    console.log(this.mxgraph.tooltipHandler);
    return "It works!";
}
```

The `console.log` statement inside the function `getTooltipForCell` indicates that this function is invoked correctly. However, the popup delay is set to 500ms, although `TOOLTIP_POPUP_TIME` is defined as follows: `const TOOLTIP_POPUP_TIME = 200; // ms`

**Comment by dumplings** [comment]
Why is there no official reply to this issue, but the person who saw it deleted two replies

**Comment by davidjgraph** [comment]
Because

1) Deleting off-topic comments takes 10 seconds, unlike fully investigating the issue.
2) Why is it you think you're entitled to an official reply?

**Comment by dumplings** [comment]
> Because
> 
> 1. Deleting off-topic comments takes 10 seconds, unlike fully investigating the issue.
> 2. Why is it you think you're entitled to an official reply?

not for me, ok?
