### ISSUE TITLE
mxOutline destroy calls addEventListener

### ISSUE THREAD

**Issue by mmacfadden** [jgraph/mxgraph#312]
First, thanks for such a great open source project! The following applies to 3.x and 4.0.

The `mxOutline` class registers a scroll listener on the source graph's container in the `init` method:

https://github.com/jgraph/mxgraph/blob/33911ed7e055c17b74d0367f5f1f6c9ee4b4fd44/javascript/src/js/view/mxOutline.js#L239

In `mxOutline.prototype.destroy` the following code exists:

https://github.com/jgraph/mxgraph/blob/33911ed7e055c17b74d0367f5f1f6c9ee4b4fd44/javascript/src/js/view/mxOutline.js#L740

I believe this should be calling `removeEventListener` instead.

**Comment by alderg** [comment]
Thanks for the report, this will be fixed in the next release!

**Comment by mmacfadden** [comment]
Thanks for the quick response! I have really enjoyed working with this API.
