### ISSUE TITLE
how to replace mxgraph part in my favorite divisions?

### ISSUE THREAD

**Issue by bahmansh** [jgraph/mxgraph#318]
I need to implement workflow in my software. So I chose mxgraph for this purpose. I've used grapheditor in my code and customize it. My problem is that I can't adopt it with bootstrap(css), I want to show separate parts(menu, toolbar, properties and ...) in different places that I want. But it append them to body tag.

EditorUi.js

//this.menubarContainer = this.createDiv('geMenubarContainer');
//this.toolbarContainer = this.createDiv('geToolbarContainer');
//this.sidebarContainer = this.createDiv('geSidebarContainer');
//this.formatContainer = this.createDiv('geSidebarContainer geFormatContainer');
//this.diagramContainer = this.createDiv('geDiagramContainer');
this.sidebarContainer =$('#sidebarContainer')[0];
this.formatContainer =$('#formatContainer')[0]; 
this.diagramContainer = $('.geDiagramContainer')[0];
this.menubarContainer = $('#menubarContainer')[0];
this.toolbarContainer = $('#toolbarContainer')[0];

Index.html

<body class="geEditor">
    <div class="container" id='graphContainer'>
        <div class="row">
            <div class="col-md-12 geMenubarContainer" id="menubarContainer">
                <div class="geMenubar" id="menuBar"></div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 geToolbarContainer" id="toolbarContainer">
                <div class="geToolbar" id="toolbar"></div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-2 geSidebarContainer" id="sidebarContainer">
            </div>
            <div class="col-md-6 geDiagramContainer geDiagramBackdrop">
            </div>
            <div class="col-md-2 geSidebarContainer geFormatContainer" id="formatContainer">
            </div>
      </div>
   </div>
   <a href="javascript:void(0)" id="exportXml">Export</a>
</body>

![mxgraphworkflow](https://user-images.githubusercontent.com/19801131/56959011-4b400f80-6b61-11e9-9ead-b901374b3f03.png)

**Comment by davidjgraph** [comment]
Do you have an [example](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem?
