### ISSUE TITLE
getCellAt(x,y) returns null after zoom

### ISSUE THREAD

**Issue by marrySmarry** [jgraph/mxgraph#319]
I have problems to get the cells for given x/y coordinates, which I receive from the mxUtils.makeDraggable  functions.  
GetCellAt(x,y) returns the correct results only for the default zoom. When zooming out, the result is always null. 

Here is an example: https://codesandbox.io/s/vmy89w0pk3 (MxGraphGridEditor.js 
(line 385 - see console output) 

Is there a currently a workaround?

**Comment by ashrafteleb** [comment]
Try the following to take the graph translate and scale into consideration:

 ```
	var s = graph.view.scale;
	var t = graph.view.translate;
	var dx = t.x * s;
	var dy = t.y * s;
    const targetCell = graph.getCellAt(dx + x * s, dy + y * s);
```
