### ISSUE TITLE
Is there any well-written documentation for mxgraph?

### ISSUE THREAD

**Issue by bahmansh** [jgraph/mxgraph#320]
I want to use workflow in my web application. I've decided to use mxgraph. My main problem is that it have very pure documentation.

For example I want to add items to toolbar for bpmn but I don't now how I should do that.

I need some sample that explain main methods step by step.

**Comment by hamzajis** [comment]
All shapes are defined in \javascript\examples\grapheditor\www\js\Shapes.js. A way to define them is using the function createVertexTemplateEntry() or AddEntry() , you can look at the examples on the file and it'll be obvious.

**Comment by bahmansh** [comment]
@davidjgraph 

In grapheditor example you have 10 javascript file (EditorUi,Editor and so on) that each do something and have too much codes without clear comments.

I want to use your sample but my main issue is that in your sample graph has scroll and is another container.
I need to use it with bootstrap.css's grids.


![image](https://user-images.githubusercontent.com/19801131/57358798-7216cb00-718b-11e9-80c6-eaffe231663c.png)

**Comment by davidjgraph** [comment]
Then submit a PR that improves the comments.

**Comment by bahmansh** [comment]
> Then submit a PR that improves the comments.

How should I do it?

**Comment by davidjgraph** [comment]
Type "github pull request" into google and select the first result, https://help.github.com/en/articles/about-pull-requests

**Comment by malienist** [comment]
@davidjgraph Is there a way to register a shape as a group container?
