### ISSUE TITLE
Can't change highlight color from green

### ISSUE THREAD

**Issue by CristianLemeni** [jgraph/mxgraph#328]
Hello, I have a problem when trying to change the highlight color, of a vertex, from green. 

I have an icon next to the vertex that when you click it it starts drawing an edge. I have changed all other colors from green but this one doesn't seem to work for some reason.

https://drive.google.com/open?id=1q-j61aQ_4o1Okc2-BetDW4K_kjVGghGb

**Comment by alderg** [comment]
What code are you using in the click handler?

**Comment by CristianLemeni** [comment]
var arrow_right = 'images/arrow_right.png';



        var vertexHandlerInit = mxVertexHandler.prototype.init;
        mxVertexHandler.prototype.init = function()
        {
            vertexHandlerInit.apply(this, arguments);

            // Only show connector image on one cell and do not show on containers
            if (this.graph.connectionHandler.isEnabled() &&
                this.graph.isCellConnectable(this.state.cell) &&
                this.graph.getSelectionCount() == 1)
            {
                this.connectorImg = mxUtils.createImage(arrow_right);
                this.connectorImg.style.cursor = 'pointer';
                this.connectorImg.style.width = '16px';
                this.connectorImg.style.height = '16px';
                this.connectorImg.style.position = 'absolute';
                this.connectorImg.setAttribute('title', 'connect');
                if (!mxClient.IS_TOUCH)
                {
                    mxEvent.redirectMouseEvents(this.connectorImg, this.graph, this.state);
                }

                // Starts connecting on touch/mouse down
                mxEvent.addGestureListeners(this.connectorImg,
                    mxUtils.bind(this, function(evt)
                    {
                        this.graph.popupMenuHandler.hideMenu();
                        this.graph.stopEditing(false);

                        var pt = mxUtils.convertPoint(this.graph.container,
                            mxEvent.getClientX(evt), mxEvent.getClientY(evt));
                        this.graph.connectionHandler.start(this.state, pt.x, pt.y);
                        this.graph.isMouseDown = true;
                        this.graph.isMouseTrigger = mxEvent.isMouseEvent(evt);
                        mxEvent.consume(evt);
                    })
                );

                this.graph.container.appendChild(this.connectorImg);
            }

            this.redrawHandles();
        };

        var vertexHandlerReset = mxVertexHandler.prototype.reset;
        mxVertexHandler.prototype.reset = function()
        {
            vertexHandlerReset.apply(this, arguments);

            if (this.connectorImg != null)
            {
                this.connectorImg.style.visibility = '';
                console.log(this);
            }
        };

        var vertexHandlerRedrawHandles = mxVertexHandler.prototype.redrawHandles;
        mxVertexHandler.prototype.redrawHandles = function()
        {
            vertexHandlerRedrawHandles.apply(this);

            if (this.state != null && this.connectorImg != null)
            {
                var pt = new mxPoint();
                var s = this.state;

                // Top right for single-sizer
                if (mxVertexHandler.prototype.singleSizer)
                {
                    pt.x = s.x + s.width - this.connectorImg.offsetWidth / 2;
                    pt.y = s.y - this.connectorImg.offsetHeight / 2;
                }
                else
                {
                    pt.x = s.x + s.width + mxConstants.HANDLE_SIZE / 2 + 4 + this.connectorImg.offsetWidth / 2;
                    pt.y = s.y + s.height / 2;
                }

                var alpha = mxUtils.toRadians(mxUtils.getValue(s.style, mxConstants.STYLE_ROTATION, 0));

                if (alpha != 0)
                {
                    var cos = Math.cos(alpha);
                    var sin = Math.sin(alpha);

                    var ct = new mxPoint(s.getCenterX(), s.getCenterY());
                    pt = mxUtils.getRotatedPoint(pt, cos, sin, ct);
                }

                this.connectorImg.style.left = (pt.x - this.connectorImg.offsetWidth / 2) + 'px';
                this.connectorImg.style.top = (pt.y - this.connectorImg.offsetHeight / 2) + 'px';
            }
        };

        var vertexHandlerDestroy = mxVertexHandler.prototype.destroy;
        mxVertexHandler.prototype.destroy = function(sender, me)
        {
            vertexHandlerDestroy.apply(this, arguments);

            if (this.connectorImg != null)
            {
                this.connectorImg.parentNode.removeChild(this.connectorImg);
                this.connectorImg = null;
            }
        };


        mxVertexHandler.prototype.getSelectionColor = function(){
            return '#000000';
        }

// Pre-fetches touch connector
        new Image().src = arrow_right;*/

**Comment by alderg** [comment]
You seem to be using the touch.html example. Try: graph.connectionHandler.marker.validColor = 'yellow';

**Comment by CristianLemeni** [comment]
It worked, thank you!
