### ISSUE TITLE
vue-cli3 mxgraph delete

### ISSUE THREAD

**Issue by wujincun** [jgraph/mxgraph#330]
vue-cli3 use mxgraph:
 keyHandler.bindKey(46, () => {
        if (this.graph.isEnabled()) {
          this.graph.removeCells()
        }
})
It is normal under refresh, but it is invalid in other situations such as from router to this page, after checking， figure out ' graph.getSelectionCell()' is undefined when delete, but when i click ,i can get a cell,i do not know why, if someone knows, thanks for helping

**Comment by davidjgraph** [comment]
https://stackoverflow.com/help/minimal-reproducible-example

**Comment by ekoz** [comment]
@wujincun please read #273 , It may help you.

**Comment by ekoz** [comment]
the correct solution is #277
