### ISSUE TITLE
How to get source and target of edge after any change on cell connect?

### ISSUE THREAD

**Issue by bahmansh** [jgraph/mxgraph#332]
I need save source and target of cell after any change on cell.
How can I get them?

**Comment by davidjgraph** [comment]
Your question is seeking debugging help but needs more information. The question should be updated to include desired behavior, a specific problem or error, and the shortest code necessary to reproduce the problem.

**Comment by Santhosh-Iyer** [comment]
Whenever there is a change in graph state, dynamically parse the graph to XML or JSON format. Then you can get them stored somewhere and access the source and target.
