### ISSUE TITLE
How to integrate mxgraph with reactjs

### ISSUE THREAD

**Issue by prakashvpsm** [jgraph/mxgraph#337]
I want to integrate Javascript MxGraph-Editor to React js .I have tried many ways.But It's still showing 'variable'(javascript variable ) not defined .Can anyone help me ?

**Comment by davidjgraph** [comment]
Stackoverflow is the correct place for such questions, as they are not specifc to mxGraph. I see you've found that at https://stackoverflow.com/questions/56731058/how-to-integrate-mxgraph-with-reactjs so I'll close this double post.
