### ISSUE TITLE
Vertex childs are getting x and y as NaN in Nodejs

### ISSUE THREAD

**Issue by scoelli** [jgraph/mxgraph#338]
I have the same project built with nodejs and other running locally in my browser (html+js).

The problem is that in the nodejs version, Vertex childs are getting bounds.x and bounds.y set to NaN when trying to decode an xml while in my local project it's working fine.

The XML I'm trying to decode it's the same in both cases.

Any idea on why this is happening? Maybe is missing some variable provided by the browser?

**Comment by scoelli** [comment]
Update:

In the nodejs project, the cell geometry offset returns a full object while on the other project (the one that runs locally), it returns the offset with just the x and y properties.
That's what is causing x and y to be NaN, it searchs for `offset.x` when it doesn't exists. 

A temporary fix would be to change `offset.x` to `parseInt(offset.attributes.x.value)` but I think someone should take a deeper look at this problem to fix what's really causing this issue.

**Comment by davidjgraph** [comment]
We've never tested it in Node. mxGraph needs a DOM and I don't think Node has one, how are you getting around that?

**Comment by scoelli** [comment]
I'm using webpack and backbone. 
I call the mxgraph library in the view (mvc). Don't know if that answers your question.

**Comment by davidjgraph** [comment]
It doesn't. NodeJS does not have an SVG DOM, so stuff like text width measuring will fail. If you don't know whether you added such a DOM, that's most likely the issue.
