### ISSUE TITLE
Can I add PR in this repo?

### ISSUE THREAD

**Issue by Lakshamana** [jgraph/mxgraph#340]
I've added a PR on [mxgraph's bitbucket repo](https://bitbucket.org/jgraph/mxgraph2/pull-requests/3/fix-mxcodec-decode-function/diff) but apparently no one reviewed it. I was thinking in submitting a PR in this repo (github) to make it easier for people to review. Can it be done?
BTW, is there a manual to, given the local clone of that repo (bitbucket), to make a build so that I could build and import for frontend projects? 

Thank you.

**Comment by alderg** [comment]
Eval should not be used in decode for security reasons. Please override the function instead in your project.
