### ISSUE TITLE
How can I set cell not movable when use mxCompactTreeLayout

### ISSUE THREAD

**Issue by soulcm** [jgraph/mxgraph#341]
When I use mxCompactTreeLayout and set cell can not movable by set it style movable=0,
the graph show some problems. when set 1 it is ok.

for example  in tree.html in project

I add one line code ```mxGraph.prototype.cellsMovable = false;```

it is display like
![image](https://user-images.githubusercontent.com/5706155/60436079-df038a00-9c3d-11e9-80fd-971534032aac.png)

the normal is this
![image](https://user-images.githubusercontent.com/5706155/60436175-15410980-9c3e-11e9-9621-4e7ad1f93e47.png)

Is it a bug or can give another method to resolve this problem? 

thanks.

**Comment by davidjgraph** [comment]
The tree layout doesn't support fixed cells as part of the layout.

**Comment by ashrafteleb** [comment]
`mxGraph.prototype.cellsMovable = false;` sets all cells not movable

To control each cell individually, set `movable=0` in style as you suggested which means keep the cell at its defined location.

In tree.html, line 225, add `v1.style = "movable=0"` which will stick Child 1 cell at (0, 0) position
