### ISSUE TITLE
How do I fix the canvas size

### ISSUE THREAD

**Issue by smallCoderZhou** [jgraph/mxgraph#342]
I don't want expand the canvas when cell drag out the canvas? what should i do? thanks

**Comment by dtheetla** [comment]
@smallCoderZhou Are you able to solve it? I am also trying the same

**Comment by uzumakinaruto123** [comment]
I was able to do achieve this to some extent. Setting maximumGraphBounds won't let shapes from exceeding the specified size. It still expands though.

**Comment by sigmainfo** [comment]
Thx @uzumakinaruto123 
Setting the graph.pageFormat, graph.maximumGraphBounds to some 10 points less than pageFormat worked for me.

**Comment by sigmainfo** [comment]
Thx @uzumakinaruto123
Setting the graph.pageFormat, graph.maximumGraphBounds to some 10 points less than pageFormat worked for me.

**Comment by davidjgraph** [comment]
[mxGraph.autoExtend](https://jgraph.github.io/mxgraph/docs/js-api/files/view/mxGraph-js.html#mxGraph.autoExtend)
