### ISSUE TITLE
Running example "http://localhost/mxgraph/php/examples/graph.php" gives Deprecated errors PHP 7.2

### ISSUE THREAD

**Issue by europa9** [jgraph/mxgraph#344]
I've just downloaded a fresh install of jgraph, and I tried to run the PHP example. However I get this error:

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; mxPoint has a deprecated constructor in C:\Users\bruker\wamp64\www\mxgraph\php\src\util\mxPoint.php on line 5

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; mxRectangle has a deprecated constructor in C:\Users\bruker\wamp64\www\mxgraph\php\src\util\mxRectangle.php on line 5

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; mxEventObject has a deprecated constructor in C:\Users\bruker\wamp64\www\mxgraph\php\src\util\mxEventObject.php on line 5

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; mxImageBundle has a deprecated constructor in C:\Users\bruker\wamp64\www\mxgraph\php\src\util\mxImageBundle.php on line 5

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; mxCell has a deprecated constructor in C:\Users\bruker\wamp64\www\mxgraph\php\src\model\mxCell.php on line 5

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; mxGeometry has a deprecated constructor in C:\Users\bruker\wamp64\www\mxgraph\php\src\model\mxGeometry.php on line 5

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; mxGraphModel has a deprecated constructor in C:\Users\bruker\wamp64\www\mxgraph\php\src\model\mxGraphModel.php on line 5

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; mxGdCanvas has a deprecated constructor in C:\Users\bruker\wamp64\www\mxgraph\php\src\canvas\mxGdCanvas.php on line 5

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; mxHtmlCanvas has a deprecated constructor in C:\Users\bruker\wamp64\www\mxgraph\php\src\canvas\mxHtmlCanvas.php on line 5

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; mxGraphViewImageReader has a deprecated constructor in C:\Users\bruker\wamp64\www\mxgraph\php\src\reader\mxGraphViewImageReader.php on line 6

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; mxGraphViewHtmlReader has a deprecated constructor in C:\Users\bruker\wamp64\www\mxgraph\php\src\reader\mxGraphViewHtmlReader.php on line 6

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; mxCellState has a deprecated constructor in C:\Users\bruker\wamp64\www\mxgraph\php\src\view\mxCellState.php on line 5

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; mxConnectionConstraint has a deprecated constructor in C:\Users\bruker\wamp64\www\mxgraph\php\src\view\mxConnectionConstraint.php on line 5

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; mxStylesheet has a deprecated constructor in C:\Users\bruker\wamp64\www\mxgraph\php\src\view\mxStylesheet.php on line 5

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; mxGraphView has a deprecated constructor in C:\Users\bruker\wamp64\www\mxgraph\php\src\view\mxGraphView.php on line 5

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; mxGraph has a deprecated constructor in C:\Users\bruker\wamp64\www\mxgraph\php\src\view\mxGraph.php on line 6

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; mxCodec has a deprecated constructor in C:\Users\bruker\wamp64\www\mxgraph\php\src\io\mxCodec.php on line 5

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; mxObjectCodec has a deprecated constructor in C:\Users\bruker\wamp64\www\mxgraph\php\src\io\mxObjectCodec.php on line 5

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; mxCellCodec has a deprecated constructor in C:\Users\bruker\wamp64\www\mxgraph\php\src\io\mxCellCodec.php on line 5

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; mxModelCodec has a deprecated constructor in C:\Users\bruker\wamp64\www\mxgraph\php\src\io\mxModelCodec.php on line 5

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; mxStylesheetCodec has a deprecated constructor in C:\Users\bruker\wamp64\www\mxgraph\php\src\io\mxStylesheetCodec.php on line 5

Warning: imagettfbbox(): Could not find/open font in C:\Users\bruker\wamp64\www\mxgraph\php\src\util\mxUtils.php on line 197

Warning: imagettfbbox(): Could not find/open font in C:\Users\bruker\wamp64\www\mxgraph\php\src\util\mxUtils.php on line 197

Warning: imagettfbbox(): Could not find/open font in C:\Users\bruker\wamp64\www\mxgraph\php\src\util\mxUtils.php on line 197

Warning: sizeof(): Parameter must be an array or an object that implements Countable in C:\Users\bruker\wamp64\www\mxgraph\php\src\canvas\mxGdCanvas.php on line 139

Warning: imagettfbbox(): Could not find/open font in C:\Users\bruker\wamp64\www\mxgraph\php\src\canvas\mxGdCanvas.php on line 1077

Warning: imagettftext(): Could not find/open font in C:\Users\bruker\wamp64\www\mxgraph\php\src\canvas\mxGdCanvas.php on line 1126

Warning: sizeof(): Parameter must be an array or an object that implements Countable in C:\Users\bruker\wamp64\www\mxgraph\php\src\canvas\mxGdCanvas.php on line 139

Warning: imagettfbbox(): Could not find/open font in C:\Users\bruker\wamp64\www\mxgraph\php\src\canvas\mxGdCanvas.php on line 1077

Warning: imagettftext(): Could not find/open font in C:\Users\bruker\wamp64\www\mxgraph\php\src\canvas\mxGdCanvas.php on line 1126

Warning: imagettfbbox(): Could not find/open font in C:\Users\bruker\wamp64\www\mxgraph\php\src\canvas\mxGdCanvas.php on line 1077

Warning: imagettftext(): Could not find/open font in C:\Users\bruker\wamp64\www\mxgraph\php\src\canvas\mxGdCanvas.php on line 1126

Warning: Cannot modify header information - headers already sent by (output started at C:\Users\bruker\wamp64\www\mxgraph\php\src\view\mxGraph.php:6) in C:\Users\bruker\wamp64\www\mxgraph\php\examples\graph.php on line 42
�PNG  IHDR,r�@ pHYs���+�IDATx���;R�YEQ��cc yD!S��ԁ�hd�c�ϻV�*l��/����ퟥ?섖��%hh Z�����%hh Z�����%hh Z�����%hh Z�����%h|�������[�����G`��j�p8|�6�����p�wp9Z�����%hh Z�����%hh Z�����%hh Z�����%hh Z�����%hh Z�����%hh Z�����%h������z8�r<��8}ۍ/�!4hK'?~����_zz|��ؘ��w���#����{�i��;{�;�K�����ΰ�����s����>�@q9o� ��ܥ��{\BK��������@�-]́�,oW� �Y�ҍ�=���]�=^�xw��x�.�=Z �{��RɁ��zԘ�=��޾iiVԎii�.y{X��]r�c�팖f�톖��@탖��:ok�Ab�ܥu���KKkd�m���F���K�e�m������ -m�� Z�j�=l���s�6��[--m���B6�&�{+�.m���*Z�<{o%���hi?�ey{��r����[����ޛ��vˁ���v΁������ 1wi���4{oR6�@�I�Kñ�&��A�{9-�ˁjiitT����a�]����ޅ�%.b�}JK\��������7Z��{������%ng��NK���;�񸗽w�.Ѱ��Di佧%b�(-1���&1����Ą��{Zbr��=-1����Ͼ���� -1�SNo��G`ZbnO���r������������ w�%m:�7�%sv�m���K����>~qr���>򸊻�T���Z����/o��4� -ACK��4� -ACK��4� -ACK��4� -ACK��4� -ACK��4� -ACK��4� -A���g*�/c}Յ�� -ACK��4� -ACK��4� -ACK��4� -ACK��4� -ACK��4� -ACK��4� -ACK��4� -ACK��4� -ACK��4� -ACK��4� -ACK��4� -ACK��4� -ACK��4� -ACK��4� -ACK��4� -ACK��4� -ACK��4� -ACK��4� -ACK��4� -ACK��4� -ACK��4� -ACK��4� -ACK��4� -ACK��4� -ACK���b}.CD�IEND�B`�1

**Comment by alderg** [comment]
What version of PHP, what OS and web server are you using?

**Comment by europa9** [comment]
Hi, Im running Windows 10 with PHP 7.2.18.

I think I have located the problem.
Example mxgraph\php\src\canvas\mxGdCanvas.php has the function
`function mxGdCanvas($width = 0, $height = 0, $scale = 1,
		$background = null, $imageBasePath = "")`

However since the class name is then the function name for the constructor should be "__construct":
`	function __construct($width = 0, $height = 0, $scale = 1,
		$background = null, $imageBasePath = "")
	{`
Also this is true for all calling of parent classes, as example "class mxGeometry extends mxRectangle", here when calling on mxRectangle it should be done like this:
`parent::__construct($x, $y, $width, $height);`

**Comment by davidjgraph** [comment]
We're deprecating the PHP model, it's moving to https://github.com/jgraph/mxgraph-php. You're welcome to submit a PR there.
