### ISSUE TITLE
Can you support .net core?

### ISSUE THREAD

**Issue by netnr** [jgraph/mxgraph#345]
`utils > mxUtils.cs` 

`using System.Windows.Forms`

**Comment by Diaskhan** [comment]
U ve tried to compile on net core ?

**Comment by Diaskhan** [comment]
Could u share project that u ve ported on net core ?!

**Comment by netnr** [comment]
？

**Comment by Diaskhan** [comment]
Could u provide stack trace. Or error list that utills doesnt compile ?

**Comment by netnr** [comment]
```
utils > mxUtils.cs
using System.Windows.Forms
```
This class name space is not supported

**Comment by davidjgraph** [comment]
Unfortunately, we no longer support the Java and .NET rendering functionality. I've udpated the README to reflect this.
