### ISSUE TITLE
keyboard event has expired after click other html element

### ISSUE THREAD

**Issue by paper-play** [jgraph/mxgraph#346]
In the official Demo anchors.html, if you click the autoLayout button and delete the selected node, you will find that the keyboard event has expired. I found out that mxKeyHandler.prototype.isGraphEvent will judge the source of evt, and find that the source of evt is still the autolayout button, and it has not been switched to the node. I also encountered this problem on my project. In one sentence, as long as I clicked on the html element other than mxgraph containtor, subsequent keyboard events would not be captured.

**Comment by alderg** [comment]
There is no autoLayout button in https://jgraph.github.io/mxgraph/javascript/examples/anchors.html

**Comment by paper-play** [comment]
<html>
 <head>
	<title>Anchors example for mxGraph</title>
	<script type="text/javascript">
		mxBasePath = '../src';
	</script>
	<script type="text/javascript" src="../src/js/mxClient.js"></script>
	<script type="text/javascript">

		var graph;
		var v1;
		window.isEnabled = false;
		
		function main(container) {
			// Checks if the browser is supported
			if (!mxClient.isBrowserSupported()) {
				mxUtils.error('Browser is not supported!', 200, false);
			}
			else {
				graph = new mxGraph(container);
				graph.setConnectable(true);

				graph.setEnabled(true);
				var parent = graph.getDefaultParent();
				var i = 1;

				//bind the key event
				var keyHandler = new mxKeyHandler(graph);
				keyHandler.bindKey(46, function (evt) {
					if (graph.isEnabled()) {
						graph.removeCells();
					}
				});
				keyHandler.bindControlKey(90, function (evt) {
					console.log('222222')
				})
				
				try {
					graph.getModel().beginUpdate();
					v1 = graph.insertVertex(parent, null, 'Hello,', 200, 20, 80, 80);
					var v2 = graph.insertVertex(parent, null, 'World!', 200, 150, 80, 80);
					var v3 = graph.insertVertex(parent, null, 'World!', 300, 150, 80, 80);
					var v4 = graph.insertVertex(parent, null, 'World!', 400, 150, 80, 80);
					var v5 = graph.insertVertex(parent, null, 'World!', 500, 150, 80, 80);
					var e1 = graph.insertEdge(parent, null, '', v1, v2);
					var e1 = graph.insertEdge(parent, null, '', v2, v3);
					var e1 = graph.insertEdge(parent, null, '', v4, v5);

				}
				finally {
					// Updates the display
					graph.getModel().endUpdate();
				}
				var layout = new mxRadialTreeLayout(graph);
				var layout2 = new mxParallelEdgeLayout(graph);
				layout.execute(graph.getDefaultParent());
			}
			window.executeLayout = function (change, post) {
				layout.execute(graph.getDefaultParent());
			};
		};

	</script>
</head>

<body onload="main(document.getElementById('graphContainer'))">
	<button onclick="setLayout()">autoLayout</button>
	<div id="graphContainer"
		style="position:relative;overflow:hidden;width:100%;height:90%;background:url('editors/images/grid.gif');cursor:default;">
	</div>
</body>

</html>

**Comment by davidjgraph** [comment]
That is not the anchors example, https://github.com/jgraph/mxgraph/blob/master/javascript/examples/anchors.html is

**Comment by paper-play** [comment]
like code at "paper-play commented Jul 24, 2019", when I click autoLayout button then key event will expired. If I refresh the browser and delete the node first , it's OK.

**Comment by paper-play** [comment]
@davidjgraph yes, there is no the example. I modify the example to describle my problem. You can refer to my code above.

**Comment by paper-play** [comment]
I'm sure it's a issue, Can you position it?

**Comment by ekoz** [comment]
@paper-play the correct solution is #277
