### ISSUE TITLE
Community examples page?

### ISSUE THREAD

**Issue by ericis** [jgraph/mxgraph#348]
Is there a place to share community examples?

I've always found it difficult that I can't "script" draw.io diagrams. So, I ran an experiment today with `mxGraph` and `puppeteer` to generate graphs that are compatible with `draw.io`.
https://github.com/ericis/lab-mxgraph-autograph/blob/master/README.md#experiment-with-mxgraph-puppeteer-and-drawio

The next step is to look at tools like:

* PlantUML: draw.io provides import capability. Wondering if there are already NodeJS scripts to convert this library and generate standard `mxGraph` XML instead for native `.drawio` diagram generation
* MermaidJS: already a javascript library. Wondering if this could also be extended to generate 
standard `mxGraph` XML for native `.drawio` diagram generation

The capabilities I want to enable:

* Script your own diagrams
* Use custom, declarative languages to describe standard diagrams and convert them into `mxGraph` XML, `.png` and `.drawio` outputs

**Comment by davidjgraph** [comment]
We don't want the responsibilty of a community page. We'll be responsible for offensive material, copyright issues, etc.
