### ISSUE TITLE
mxHierarchicalLayout overrides default Y for vertexes

### ISSUE THREAD

**Issue by CristianLemeni** [jgraph/mxgraph#349]
Hello, I have a problem when I use this layout. For some reason it overrides the default value I set for y and I don't understand why?
`
var l = new mxHierarchicalLayout(graph);
                mxHierarchicalLayout.prototype.deterministic = false;
                mxHierarchicalLayout.prototype.parallelEdgeSpacing = 10;
                mxHierarchicalLayout.prototype.disableEdgeStyle = false;
                mxHierarchicalLayout.prototype.roots = lookup_state.state;
l.execute(graph.getDefaultParent());
`
![Screenshot (84)](https://user-images.githubusercontent.com/37481559/61689878-f525d700-ad1f-11e9-8052-817cf4b642e1.png)

**Comment by davidjgraph** [comment]
You mean you set the Y of the root and that was moved?

**Comment by CristianLemeni** [comment]
Yes, I set a default Y for all vertexes.

**Comment by davidjgraph** [comment]
This hierarchical cannot run with pre-fixed vertices using either co-ordinate. What should the result of the above example look like?

**Comment by CristianLemeni** [comment]
I would like to have the vertexes position a bit lower in the page, si that it doesn't cut off the edge
