### ISSUE TITLE
How to change connection points color of vertex 

### ISSUE THREAD

**Issue by ekoz** [jgraph/mxgraph#350]
![企业微信截图_15639752958839](https://user-images.githubusercontent.com/3312512/61798022-26ef8880-ae5b-11e9-8ac5-6acd0dbf22da.png)

**Comment by alderg** [comment]
See mxConstraintHandler.prototype.pointImage

**Comment by ekoz** [comment]
@alderg Hi, I read the code `mxConstraintHandler.prototype.pointImage = new mxImage(mxClient.imageBasePath + '/point.gif', 5, 5);`, it can change the point image, but how to change the point color from green to another, like blue?

**Comment by ekoz** [comment]
@alderg I learned how to change point image from demo  [https://jgraph.github.io/mxgraph/javascript/examples/portrefs.html](https://jgraph.github.io/mxgraph/javascript/examples/portrefs.html) 

when I hover the point, the point border is green color, how to change?

**Comment by alderg** [comment]
See mxConstraintHandler.prototype.highlightColor

**Comment by ekoz** [comment]
@alderg thanks for your reply, `mxConstraintHandler.prototype.highlightColor` default value is `mxConstants.DEFAULT_VALID_COLOR`, it is the vertex border hover color, not connection point hover color.
![企业微信截图_15640338381293](https://user-images.githubusercontent.com/3312512/61849238-36b2af80-aee3-11e9-9f5f-29355f4f1f2c.png)

**Comment by alderg** [comment]
What have you tried?

**Comment by ekoz** [comment]
I almost set all property of mxConstants about color to #FF0000, but not effect.
```
    mxConstants.HIGHLIGHT_COLOR = '#FF0000'
    mxConstants.TARGET_HIGHLIGHT_COLOR = '#FF0000'
    mxConstants.INVALID_CONNECT_TARGET_COLOR = '#FF0000'
    mxConstants.DROP_TARGET_COLOR = '#FF0000'
    mxConstants.VALID_COLOR = '#FF0000'
    mxConstants.INVALID_COLOR = '#FF0000'
    mxConstants.OUTLINE_HIGHLIGHT_COLOR = '#FF0000'
    mxConstants.CONNECT_HANDLE_FILLCOLOR = '#FF0000'
    mxConstants.OUTLINE_COLOR = '#FF0000'
    mxConstants.OUTLINE_HANDLE_FILLCOLOR = '#FF0000'
    mxConstants.OUTLINE_HANDLE_STROKECOLOR = '#FF0000'
    mxConstants.SHADOWCOLOR = '#FF0000'
    mxConstants.VML_SHADOWCOLOR = '#FF0000'
    mxConstants.DEFAULT_VALID_COLOR = '#FF0000'
    mxConstants.DEFAULT_INVALID_COLOR = '#FF0000'
    mxConstants.OUTLINE_HIGHLIGHT_COLOR = '#FF0000'
    mxConstants.OUTLINE_HIGHLIGHT_COLOR = '#FF0000'
    mxConstants.LABEL_HANDLE_FILLCOLOR = '#FF0000'
    mxConstants.LOCKED_HANDLE_FILLCOLOR = '#FF0000'
    mxConstants.HIGHLIGHT_COLOR = '#FF0000'
    mxConstants.HIGHLIGHT_COLOR = '#FF0000'
    mxConstants.HIGHLIGHT_COLOR = '#FF0000'
    mxConstants.HIGHLIGHT_COLOR = '#FF0000'
```
the demo [grapheditor](https://jgraph.github.io/mxgraph/javascript/examples/grapheditor/www/index.html) also changed connection point style, it is nice. how to?
![企业微信截图_15640375722390](https://user-images.githubusercontent.com/3312512/61852367-e68c1b00-aeeb-11e9-9f16-6e7ad56ad2e0.png)

**Comment by ekoz** [comment]
@alderg @davidjgraph I have no idea to change the connection point style, could you help me? thank you.

**Comment by kirisamejin** [comment]
```
		// Overrides highlight shape for connection points
		mxConstraintHandler.prototype.createHighlightShape = function()
		{
			var hl = new mxEllipse(null, this.highlightColor, this.highlightColor, 0);
			hl.opacity = mxConstants.HIGHLIGHT_OPACITY;
			
			return hl;
		};
		
```
I used debug tool and then found this code in Editors.js of graphEditor of examples. It can modify the highlight shape and color.

**Comment by ekoz** [comment]
@kirisamejin thank you , it is great. the key points are: 

1. `mxConstants.DEFAULT_VALID_COLOR = '#409EFF'` 

2. `mxConstraintHandler.prototype.highlightColor =
      mxConstants.DEFAULT_VALID_COLOR`

also thank @alderg for your reply
