### ISSUE TITLE
Default fontFamily not work at least on windows platform

### ISSUE THREAD

**Issue by werewolfvit** [jgraph/mxgraph#351]
Hi, at 4.0.1 update was added:
`- Forces quotes around font names in CSS and SVG`
But default style font family is "Arial, Helvetica", if  set it in quotes in CSS no font will be finded by browser at Windows and I think in any others OS's too.
Chrome uses "Times New Roman" with such CSS style.

**Comment by davidjgraph** [comment]
Do you have a simple, complete, runnable example that demonstrates the issue?

**Comment by werewolfvit** [comment]
It is more easy  just open standart "helloworld.html" example from last version mxgraph. But  if it needed in attached archive you will see standart copied "helloworld.html" example and screenshot with proofs.
[helloworld.zip](https://github.com/jgraph/mxgraph/files/3435599/helloworld.zip)

**Comment by davidjgraph** [comment]
OK, pretty obvious. Fixed in 4.0.3. Thanks for report.
