### ISSUE TITLE
Implementing multiplicities on ports

### ISSUE THREAD

**Issue by CristianLemeni** [jgraph/mxgraph#352]
Hello, I wanted to ask if you can apply multiplicities on ports, so that I can limit the number of edges per port and if so, how?

**Comment by ashrafteleb** [comment]
Check the validation and ports examples

https://github.com/jgraph/mxgraph/blob/master/javascript/examples/validation.html
https://github.com/jgraph/mxgraph/blob/master/javascript/examples/ports.html
