### ISSUE TITLE
How can I show completed tasks in mxgraph as read-only graph?

### ISSUE THREAD

**Issue by bahmansh** [jgraph/mxgraph#360]
I have used mxgraph for designing workflows in my web application. So I need to show to users done steps of workflow on graph.

My graph should be read-only and I need colorize edge and tasks that are done.

**Comment by davidjgraph** [comment]
There are either too many possible answers, or good answers would be too long for this format. Please add details to narrow the answer set or to isolate an issue that can be answered in a few paragraphs.
