### ISSUE TITLE
Can't drag entry Points for edge

### ISSUE THREAD

**Issue by CristianLemeni** [jgraph/mxgraph#362]
Why can't I drag the entry point of an edge while I can drag the exit point. I have hardcoded the style like  so styleString = "style=" + "exitX=" + "0.75" + ";" + "exitY=" + "0" +
                        ";exitDx=0;exitDy=0;" + "entryX=" + "0.5" + ";" + "entryY=" +
                        "0.5" + ";entryDx=0;entryDy=0;"

![Screenshot_6](https://user-images.githubusercontent.com/37481559/63347565-4345ee80-c34f-11e9-8bf9-de8ddf404f77.png)
![Screenshot_7](https://user-images.githubusercontent.com/37481559/63347570-450fb200-c34f-11e9-96b9-87051a56be66.png)
![Screenshot_8](https://user-images.githubusercontent.com/37481559/63347575-46d97580-c34f-11e9-9e56-a8853c134de0.png)

**Comment by ashrafteleb** [comment]
Can we have a complete example so we can reproduce your issue
