### ISSUE TITLE
Is this a bug in orthogonal edge routing?

### ISSUE THREAD

**Issue by wuleibobo** [jgraph/mxgraph#368]
When user zoom the graph, orthogonal edge routing will calculate the absolute points of the edge.
but sometimes the route is wrong.

In scale 30%, the route is right:
![image](https://user-images.githubusercontent.com/19942836/64064240-45525c00-cc31-11e9-8ab7-fb122b1af785.png)
But in scale 20%, the route is wrong:
![image](https://user-images.githubusercontent.com/19942836/64064247-6024d080-cc31-11e9-95d6-c4f74d66af22.png)

This issue will cause the outline is different with graph, because they are different scale.
![image](https://user-images.githubusercontent.com/19942836/64064256-8b0f2480-cc31-11e9-8bd5-8cde0c309920.png)

**Comment by alderg** [comment]
Can you attach the diagram file please?

**Comment by wuleibobo** [comment]
Diagram data in draw.io. Please trace it.

`<mxfile host="www.draw.io" modified="2019-10-17T07:39:21.076Z" agent="Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0" etag="AAg8-OIUdK4PYmy24gXI" version="12.1.2" type="device" pages="1"><diagram id="B5IUQbCcViYoLn4myiS4" name="Page-1">zZRLT8MwDMc/TY+gPhjbrmwdSIwDmgTjGK1eG5TWVea++PSkq7O2mjbBAYlT8//FTvyo4wSLtH7UIk9eMALl+G5UO8HS8X3fDTzzaUnTEc+dzzsSaxkx68FGfoE1ZFrICA4jQ0JUJPMx3GGWwY5GTGiN1dhsj2p8ay5iOAObnVDn9F1GlHR05k97/gQyTuzN3j3nlwprzJkcEhFhNUBB6AQLjUjdKq0XoNrq2bp0fqsLu6fANGT0E4d9OJu/Ht5Xb+Gm1GW51rB+vrnj2KixCUNk8meJmhKMMRMq7OmDxiKLoD3VNaq3WSPmBnoGfgJRw80UBaFBCaWKd6GWtGX3dv3Rrm/9CctlPdhbNlZkpJvtUHRu04nVvd9RWccuwzati4VjdMBC7+BKtewPKHQMdMXOP7XXDAZgCiYe46dBCZLlOA7BP2h8sut7aBbcxl+0lM8thSr4prMejztYJZJgk4tj6pWZ43G3+DjQBPX1Cp5nbB3mPAP8ClhZ9RPl2TFJhtPk/lGN/P9fo8D7uyIZ2b87x73B8x2E3w==</diagram></mxfile>`

**Comment by davidjgraph** [comment]
Fixed in next release.
