### ISSUE TITLE
Outline is not working for second diagram once user clears the first diagram (Without browser page reload)

### ISSUE THREAD

**Issue by siddappah** [jgraph/mxgraph#369]
Hello team,
Thanks for doing the great job.

Am new to the mxGraph and facing an issue in 'outline' the diagram.

When user load the diagram(Travel Booking diagram) and clicks on outline from the toolbar then user can able to use outline perfectly.

[As shown in this diagram](https://github.com/siddappah/images/blob/master/diagram1.png)

Actual issue - When user clears the existing diagram and load the same/different diagram(Travel Booking/Swimlanes diagram), again click on outline then outline is not behaving like earlier, instead of showing the diagram, it is just showing a kind of dot without the diagram,this is the issue user is facing.

[As shown in this diagram](https://github.com/siddappah/images/blob/master/diagram2.PNG)

Hoping for the response as soon as possible.

Thanks in advance

**Comment by davidjgraph** [comment]
Please provide a minimal, complete, runnable example that demonstrates the issue.
