### ISSUE TITLE
mxGraph analysis function is missing

### ISSUE THREAD

**Issue by Joseph880929** [jgraph/mxgraph#37]
Hello

I read the mxGraph User manual and I found something useful: 
![image](https://cloud.githubusercontent.com/assets/22244863/21103576/0fa2e334-c051-11e6-8563-388a49d36850.png)

This image shows the result of a function that determines and shows all the possible routes between two cells and also shows another function that returns the shortest path between those cells.

I already found the ShortestPath Function, but I am still looking for the function that allows me to get all possible routes between two cells, despite checking out the analysis package of mxGraph, I haven´t been able to identify this function; so I ask: Does this function exist? 

If the function exists, it would be good to know its name and how to find it in mxGraph API.

Thank you.

**Comment by davidjgraph** [comment]
No, it doesn't exist.
