### ISSUE TITLE
Adding points to an edge doesn't work

### ISSUE THREAD

**Issue by CristianLemeni** [jgraph/mxgraph#371]
After I create an edge e = insertEdge(parent, null, name, .sourceVertex, targetVertex, styleString)

and I want to add points to it like so e.geometry.points.push((new mxPoint(x, y)))

it adds them to the object but doesnt draw it corectly

**Comment by davidjgraph** [comment]
Please provide a minimal, complete, runnable example that demonstrates the issue.
