### ISSUE TITLE
Open xml (graphEditor example) Error: 2: Duplicate ID

### ISSUE THREAD

**Issue by Damasy** [jgraph/mxgraph#372]
When I use setGraph function to set XML to the editor this error appears to me:
**Error: 2: Duplicate ID**

here are you myCode:

`
function openWorkflow(xml) {
      $('#workflows-list').modal('hide');
      var doc = mxUtils.parseXml(xml);
      GeneralEditor.editor.setGraphXml(doc.documentElement);
			mxEditor.setModified(false);
			mxEditor.undoManager.clear();
    }
`

I'm using grapheditor example as my project base.
I've made a debugger and found the error in **mxCodec.prototype.addElement**

here exactly:

`else if (this.elements[id] != node)
			{
				throw new Error(id + ': Duplicate ID');
			}`;

Can you help, please?
@davidjgraph 
@alderg

**Comment by davidjgraph** [comment]
Please provide a minimal, complete, runnable example that demonstrates the issue.

**Comment by jromerob** [comment]
same issue for me when use coder to save and load model.

This is the model i try to decode, come from previous 
result= encoder.encode(this.graph.getModel()) 
mxUtils.getXml(result)

`<mxGraphModel>
  <root>
    <mxCell id='0' value='Nuevo gráfico' />
    <mxCell id='1' parent='0' />
    <VertexImgValve id='2'
      geographicGeometry='{&quot;type&quot;:&quot;Point&quot;,&quot;coordinates&quot;:[976326.419226513,4504912.4173704935]}'
      identificator='#2'>
      <Object as='value'><Object title='Presión. Max' value='18' units='(Bar)' validationRegEx='([0-1]+[0-9])' type='number' required='1' as='max_pressure'/><Object title='Presión. Min' value='1' units='(Bar)' type='number' as='min_pressure'/><Object title='Salto' value='10' units='' type='number' as='step'/></Object>
      <MxGeometry x='350' y='280' width='40' height='40' as='geometry' />
      <Array as='mxTransient'>
        <add value='id' />
        <add value='value' />
        <add value='parent' />
        <add value='source' />
        <add value='target' />
        <add value='children' />
        <add value='edges' />
      </Array>
      <mxCell id='1' parent='0' as='parent' />
    </VertexImgValve>
  </root>
</mxGraphModel>`

when try to load with 
`  const document = mxUtils.parseXml(schemeModel);
    const root = document.childNodes[0];
    const dec = new MxCodec(document);
    const model = this.graph.getModel();
    dec.decode(root, model);`

i have the same error, the problem is in the ' <mxCell id='1' parent='0' as='parent' />' node witch try to load on model again as new cell whith the same id as previus cell #1 
Any idea to fix?

**Comment by alderg** [comment]
The mxCellCodec should move the id attribute from the mxCell element to the outer element (VertexImgValue in your case) and remove the id attribute from mxCell on line 99-101. Can you check why this is not the case when you encode the model?

**Comment by jromerob** [comment]
Fixed, my problem was a custom encoder, adding parent as idref solved the problem.


```javascript
 codec.encode = (enc, obj) => {
            // Usamos el codificador de un MXCell
            const cellCodec = MXUTILITIES.mxCodecRegistry.getCodec(MxCell);
            // Asignamos la plantilla de nuestro objeto al codec de MxCell
            **cellCodec.idrefs = ['parent'];**
            cellCodec.template = this;
            // Codificamos el nodo
            return cellCodec.encode(enc, obj);
        };
`

**Comment by nieyangyang712** [comment]
> When I use setGraph function to set XML to the editor this error appears to me:
> **Error: 2: Duplicate ID**
> 
> here are you myCode:
> 
> `function openWorkflow(xml) { $('#workflows-list').modal('hide'); var doc = mxUtils.parseXml(xml); GeneralEditor.editor.setGraphXml(doc.documentElement); mxEditor.setModified(false); mxEditor.undoManager.clear(); }`
> 
> I'm using grapheditor example as my project base.
> I've made a debugger and found the error in **mxCodec.prototype.addElement**
> 
> here exactly:
> 
> `else if (this.elements[id] != node) { throw new Error(id + ': Duplicate ID'); }`;
> 
> Can you help, please?
> @davidjgraph
> @alderg


Why, mxcell id = "0", when the ID in this is generated, you can customize a random number so that it won't be repeated; my personal opinion is for reference only!

**Comment by nieyangyang712** [comment]
Why, mxcell id = "0", when the ID in this is generated, you can customize a random number so that it won't be repeated; my personal opinion is for reference only!
