### ISSUE TITLE
Can't hide edges behind vertexes with ordered = false

### ISSUE THREAD

**Issue by CristianLemeni** [jgraph/mxgraph#374]
I tried to hide the edges with mxGraph.prototype.ordered = false; and it's not working

**Comment by davidjgraph** [comment]
Please provide a minimal, complete, runnable example that demonstrates the issue.

**Comment by CristianLemeni** [comment]
https://codepen.io/cristianlemeni/pen/JjjYeRm

**Comment by davidjgraph** [comment]
Move the edge to back:

`graph.orderCells(true, [e1]);`

https://codepen.io/davidjgraph/pen/poojQwW
