### ISSUE TITLE
Snap to grid not as accurate when copying shape and using CTRL + scrolling

### ISSUE THREAD

**Issue by mattscotty** [jgraph/mxgraph#376]
When using the CTRL button to drag and copy shapes, the grid snapping function of only works if the mouse is not used to automatically scroll the screen in any direction. 
To replicate :
1.	Create a shape in e.g. rectangle created with Dims 200pt x 80pt in position 160pt x 80pt. 
2.	CTRL+Drag the rectangle down but without scrolling the screen.  Note the position dimensions are still integers.
3.	Now, CTRL+Drag one of the shapes in any direction but ensure the screen auto scrolls. 

Note the Top position is now a large decimal number, e.g. 601.5999755859375 pt. 

This only seems to occur in the direction of the auto-scrolling. 

[mxGraph Drag Copy Precision.pdf](https://github.com/jgraph/mxgraph/files/3606009/mxGraph.Drag.Copy.Precision.pdf)

**Comment by davidjgraph** [comment]
To clarify, you're saying follow these steps in the GraphEditor example?

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.

**Comment by mattscotty** [comment]
Fantastic, thanks
