### ISSUE TITLE
maximumGraphBounds won't work if shape close to bounds is rotated & aspect ratio breaking

### ISSUE THREAD

**Issue by uzumakinaruto123** [jgraph/mxgraph#378]
If any shape is dragged and dropped, then maximumGraphBounds is respected and shape does move within the graph bounds.

If the shape is resized then it does adjusts itself within the bounds.

But, if any shape close to the border is rotated, then it extends outside the graph bounds, which is not expected.

Also,

while resizing the shape, if shape touches the bounds, then shape still resizes vertically breaking the aspect ratio since it cannot move outside the graph. It should resize until it reaches the graph bounds and then stop.

**Comment by davidjgraph** [comment]
Please provide a minimal, complete, runnable example that demonstrates the issue.

**Comment by uzumakinaruto123** [comment]
I am facing difficulties in setting up the graph editor sample online. I will try that. Till then check these links:

- **Rotate and exceeding bounds:** https://drive.google.com/file/d/1jz05DX03I5suc2LZLKdGV37uKUzAQ4nD/preview

- **Aspect ratio change and resize 
 on reaching bounds when the vertex is dragged:** https://drive.google.com/file/d/1FUEq7Syi_lh_gr6eHvrNL4hK_3qc5TsK/preview


Nothing to reproduce as such. Just needs setting maximumGraphBounds and trying the above cases.

**Comment by uzumakinaruto123** [comment]
Temporarily fixed rotation issue with the following since I don't need rotation

`mxVertexHandler.prototype.rotationEnabled = false;`
