### ISSUE TITLE
MxPrintPreview Electron Issue

### ISSUE THREAD

**Issue by jmarieghernandez** [jgraph/mxgraph#379]
Hi,

I have been trying to create an mxPrintPreview window in Electron and whenever I open it, the page  is blank. I know that Electron does not have Print Preview but from my understanding MxGraph renders an HTML page with multiple "pages" for printing a graph. Is there a way to make this work in an Electron window? My application opens the Window but does not render the graph pages.

Thank you

**Comment by davidjgraph** [comment]
Hi. Your question is seeking debugging help but needs more information. The question should be updated to include desired behavior, a specific problem or error, and the shortest code necessary to reproduce the problem.
