### ISSUE TITLE
mxXmlUtils::getDocumentBuilder not thread safe

### ISSUE THREAD

**Issue by unkish** [jgraph/mxgraph#382]
With release 3.7.3 `DocumentBuilder` instance of `mxXmlUtils::getDocumentBuilder` was refactored to be `static`.
However `DocumentBuilder` may be not thread safe which would lead to runtime errors.

A simple example that demonstrates the issue:
```java
final String xml = mxXmlUtils.getXml(new mxCodec().encode(new mxGraph()));

final ExecutorService executor = Executors.newFixedThreadPool(2);
IntStream.range(0, 100)
         .mapToObj(i -> (Runnable) () -> mxXmlUtils.parseXml(xml))
         .forEach(executor::submit);
executor.shutdown();
```

Is it possible to make `mxXmlUtils::getDocumentBuilder` thread safe or it was intentionally left this way?

**Comment by alderg** [comment]
Thanks for the report. We will generate a new instance on each call to fix this in the next release.

**Comment by unkish** [comment]
A suggestion if i might:
If creating new instance of `DocumentBuilderFactory` is consuming a lot of resources, maybe it would be possible to avoid generating new instance on each invocation and instead move `DocumentBuilderFactory` creation into static initializer block additionally synchronizing access to it ?

**Comment by alderg** [comment]
The instance is only generated once on the first invocation and then cached in the static variable documentBuilderFactory.
