### ISSUE TITLE
show unconnected edges after decode 

### ISSUE THREAD

**Issue by jromerob** [jgraph/mxgraph#385]
After encode a graph model, if it has unconnected edges when i load again the model with decode the unconnected edges appears in model but arent' show on graph. Is there any graph property to set ?

**Comment by alderg** [comment]
Did you pass the document to the mxCodec constructor?

**Comment by jromerob** [comment]
Yes, on load 

```javascript
const dataModel = localStorage.getItem('modelo');

    const document = MXUTILITIES.mxUtils.parseXml(dataModel);
    const root = document.childNodes[0];
    const dec = new MxCodec(document);
```

**Comment by jromerob** [comment]
Yes man, that's was the problem, i'm using Angular and mxGraph load classes on window object that aren't present on my arquitecture. I have to manualy load it

> ```javascript
window['mxGraphModel'] = mx.mxGraphModel;
window['mxGeometry'] = mx.mxGeometry;
window['MxGeometry'] = mx.mxGeometry;
window['MxPoint'] = mx.mxPoint;
```

**Comment by Vbboi24** [comment]
Hello @jromerob , Would you mind sharing how you got your way through in integrating mxgraph with angular ? More a high level guide would help

**Comment by jromerob** [comment]
You can view in:

https://stackoverflow.com/questions/49922708/how-to-integrate-mxgraph-with-angular-4/59022452#59022452
