### ISSUE TITLE
__mxOutput is not defined

### ISSUE THREAD

**Issue by paivaandeerson** [jgraph/mxgraph#386]
I was trying to do the tutorials by my self to learn how to use this library, with the current version so far [4.0.5] from _npm_, and using the **mxClient.js** file the browser console shows:

>     __mxOutput is not defined

I could do everything that I wanted using this file, but this error continues there, I also noticed that using **mxClient.min.js** file is a workaround, and this bug started since version [3.9.11], seems like pasting the version code [3.9.10] solves the problem, but I don´t know which consequences I'd have doing that.

**Comment by davidjgraph** [comment]
Please post a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
