### ISSUE TITLE
Label not displayed on connector creation

### ISSUE THREAD

**Issue by mattsrinc** [jgraph/mxgraph#387]
Hi, I would like to have labels added when a connector is created between two shapes in the diagram editor example. In the documentation for mxConnectionHandler:

https://jgraph.github.io/mxgraph/docs/js-api/files/handler/mxConnectionHandler-js.html

it appears there's a way with a custom handler:

```
mxConnectionHandlerInsertEdge = mxConnectionHandler.prototype.insertEdge;
mxConnectionHandler.prototype.insertEdge = function(parent, id, value, source, target, style)
{
  value = 'Test';

  return mxConnectionHandlerInsertEdge.apply(this, arguments);
};
```
yet the label is not added and displayed. It doesn't matter if I modify verticalConnector like this:

```
<add as="verticalConnector">
  <add as="elbow" value="vertical"/>
  <add as="label" value="Test"/>
  <add as="html" value="1"/>
  <add as="whiteSpace" value="wrap"/>
</add>
```

to the mxStyleSheet tag in the diagrameditor.xml file (e.g. to have default label set in configuration).

UPDATE: in draw.io the relevant example would be UML Message shape with a label on a line.

As a side question - how to detect if the connector to be created and displayed now is a verticalConnector or straightConnector (as defined in mxStyleSheet as well). E.g. changing a function in XML CDATA section in diagrameditor.xml doesn't help and I also had no luck of adding mouse click event handlers to icons in toolbar to maintain a value of selected connector (I use only straight and default elbow connectors). This would the be used in conditional insertEdge statement to change the label based on connector type.

**Comment by ashrafteleb** [comment]
mxStyleSheet is for styles only and the label is not part of the style. You can change label attribute in Connector

```
		<add as="connector">
			<Connector label="Default Label" href="">
				<mxCell edge="1">
					<mxGeometry as="geometry" relative="1"/>
				</mxCell>
			</Connector>
		</add>

```
As for mxConnectionHandler, this example uses a factory so you can set the label after executing the `insertEdge`, e.g, `edge.getValue().setAttribute('label', 'text')`
