### ISSUE TITLE
XML node attributes removed on UNDO 

### ISSUE THREAD

**Issue by Kenjekenny** [jgraph/mxgraph#389]
I have noticed some strange behaviour when undoing changes made to the attributes of a XML node.

My XML node template has several attributes WITH a value and some empty attributes WITHOUT a value. I can edit any of the attributes and save them without issue (the XML shows the modifications and so does the properties panel).

When undoing the changes, it reverts the attributes to their previous values but attributes that did NOT have a value prior to the undoing, are completely removed from the XML node.

**XML node before edit:**
```
<Activity label="Activiteit" type="standard" alias="" definition="" inputs="" outputs="" controls="" mechanisms="" id="2">
      <mxCell vertex="1" parent="1">
        <mxGeometry x="200" y="150" width="120" height="90" as="geometry"/>
      </mxCell>
</Activity>
```
**XML node after edit:**
```
<Activity label="test1" type="standard" alias="test2" definition="test3" inputs="test4" outputs="" controls="" mechanisms="" id="2">
      <mxCell style="defaultVertex" vertex="1" parent="1">
        <mxGeometry x="200" y="150" width="120" height="90" as="geometry"/>
      </mxCell>
</Activity>
```

**XML node after undo:**
```
<Activity label="Activiteit" type="standard" id="2">
      <mxCell vertex="1" parent="1">
        <mxGeometry x="200" y="150" width="120" height="90" as="geometry"/>
      </mxCell>
    </Activity>
```

**Comment by alderg** [comment]
What code are you using the set/undo the changes?

**Comment by Kenjekenny** [comment]
I haven't touched any of the basic functionalities provided by mxUndoManager, nor have i added/modified any event handlers that might interfere. 

Initially i had overridden the createProperties function but the problem still persists when using the standard createProperties function from mxEditor. Aside from that it's a very simple project using some of the examples provided (custom labels, tooltips, connection-handlers & connection-constraints).

**Comment by alderg** [comment]
Found the problem. In mxCell.getAttribute we use return val || defaultValue where we should use return (val != null) ? val : defaultValue, ie.

```
mxCell.prototype.getAttribute = function(name, defaultValue)
{
	var userObject = this.getValue();
	
	var val = (userObject != null &&
		userObject.nodeType == mxConstants.NODETYPE_ELEMENT) ?
		userObject.getAttribute(name) : null;
		
	return (val != null) ? val : defaultValue;
};
```

This will be fixed in the next release. As a workaround, override the function using the code above.
