### ISSUE TITLE
Bug in Graph.js for editor

### ISSUE THREAD

**Issue by algenty** [jgraph/mxgraph#390]
Hi,

In the Graph.js, there is an object not declared : 
angular.js:14700 ReferenceError: Editor is not defined
    at mxConnector.paintLine (Graph.js:2540)
    at mxConnector.mxPolyline.paintEdgeShape (build.js:25805)
    at mxConnector.paintEdgeShape (build.js:28575)
    at mxConnector.mxShape.paint (build.js:23391)
    at mxConnector.mxShape.paint (Shapes.js:567)
    at mxConnector.mxShape.redrawShape (build.js:22980)
    at mxConnector.mxShape.redraw (build.js:22818)
    at mxCellRenderer.doRedrawShape (build.js:50043)
    at mxCellRenderer.redrawShape (build.js:50022)
    at mxCellRenderer.redraw (build.js:49936)

If I put that in comment, it works perfectly

var arcSize = mxUtils.getValue(this.style, mxConstants.STYLE_ARCSIZE,
mxConstants.LINE_ARCSIZE) / 2;
var size = (parseInt(mxUtils.getValue(this.style, 'jumpSize',
Graph.defaultJumpSize)) - 2) / 2 + this.strokewidth;
var style = mxUtils.getValue(this.style, 'jumpStyle', 'none');
**// var f = Editor.jumpSizeRatio;**
var moveTo = true;
var last = null;
var len = null;
var pts = [];

the xml : 
<mxfile modified="2019-11-04T11:50:13.371Z" host="www.draw.io" agent="Mozilla/5.0 (Windows NT 6.1; WOW64; rv:60.0) Gecko/20100101 Firefox/60.0" etag="A7NgX8zXNjVwE96EBD9P" version="12.2.0" type="device" pages="1"><diagram id="8ANqGdhLLS95A8qOACvl" name="Page-1">7V1bd5u4Fv41XuvMg2eBxPUxdet2ZpI2TTo5zbx0EVuxabDlKjiO++tHgMCgLRP7hFt98EMCGyEu37e1L4jNAI8Wz++Zt5pf0CkJBkibPg/w2wFCum45/F8k2SYSGxmJYMb8qWi0E1z7P4kQakK69qfksdAwpDQI/VVROKHLJZmEBZnHGN0Um93ToHjUlTcjQHA98QIo/a8/DefZdbm7DR+IP5uLQzvITjbceZOHGaPrpTjeAOFR/Es2L7y0L3Ghj3NvSjc5EX43wCNGaZgsLZ5HJIjubXrbkv3Ge7Zm583IMjxkh7vL27PVkDz9vZ3d/BGydw9fb9hQ9PLkBWuSXkZ8suE2vUHxJZKoE32A30zowp/wZY0vf18vVtei4ZIuSSpKMNYxX6csnNMZXXrBOaUr0cd3EoZb0cpbh5SL5uEiEFuz+xQdgiynZxHIuyNwydgPgt120ZHD10KPzUh4SZi/ICFh1ytv4i9nouljyOhDhrHFJfe8nxENKIsvFE8dTbNx1jK3Zcx/Wny44C4+lyfCQp9ziIsgDOKekmmBeAKU94Tyc2Nb3oCRwAv9pyIPPUHnWdYu2/WS+vwQSBOqZ2Oxi1A8pJnFLh7pmk2I2CtPDKkjpBU70k2t2JG4rXJHHBhvm2u2iho87j9hC6PfTeUp7z0zU77EAsX5QnIO6Vru9u5EsRqoVWJ48X1pa59+3r770wyN+/Fs4d8NOW97nThEJ/imrumEoztFKmOJyofrhFboCGv16ISNi8fhyld6XhbSj2pv2lL/llZ+3UZp+1dr3JstIfrX0dnbOXE25z+/PW3mH4bIBQr2v+gI4HKFinKAWudHgYK+FgeLIxRMSxTMYxNxHBT3nVBYfZ6taZ7lFonpHKYvLxojK7MZL6jwsZqH3KItsnDpeRmGZCRdp1xRsdzeLW/vqo1wVYpnfP7xkdzgf2zLHv3xY7vRP0y/DJ1e76DeRWbNaVWXZKOQcufVygQ8u4p0CRuyn1auS7JRKm9uYatMlepRDegEQi+Qd8Oj1IiTm7kfkoi50ZYND5SLKuI9rpLQ9d5/jggp6YwRSRLaf4mVbmjEjKXLcOwt/CC67hvCpt7SE+JUJRLvMw6MvbtYUkrcyEUjz6XUTbc6juSr66lnsMlFySIUnufi41SmonsOsuO9BAcggptDhLso8M7vAQgCIro6J/fRIYd2bNUDf7bka0EsrAIzbJgyZnrLmGEbgCYc1kZQ0w4HTex3JW7K0LTLkHxDw5AuYk2tSOEsB0nqprcLXaruhTDYCiKuTv0nvjiLFnUjFfKD5OSKpqnojskSedfu0yOvwBMOOmEHsSUe1msgi2W3zBU4Er/akbTrcyR5QNWkH0me/fCr2Dtavo365SN1svb2Ob2YaGX7kgmv2/d0Hck3A/HXoc6ni7XfdWv3s+V+cf4nUXOPY1pVxsEwesKWZPR+ZcIalRHWlfttk7AmsMaXa7bi7EDauc+ZJtOZW5JQxdYUb0HPPDmESHJM07TumRAv/Ok02GeMd8xLbeuLAczrraHrSuFyxoC8PRSJzIJBRNp+tr3OIFoArk/MW856uCBcuH249N4a7E8//9LWAKaPq7EGVrvWoOerwt12TsDddmriq9MqX2HKp+frbk7Jr8xXXauJsFHHLTLW6hl7oiOsXl1GwwUdt8hYu2fsqTK2rpSG3m5OI3041VNWyhqfgFtQV9yltxt46ainLKCsdhIPOnQH10RZ3nGblO2fzZ2qY4C0migbddwmZfv81slSFtVFWdQuZfsU18lS1qiLska7lO1zXCdLWasuylrtUrZPcp0sZesKv1DL4VcN77b1lO0EZTGPkmzHtHUDJX/roG90EEt3NcNO/jbLXgQngV9xuPtJTPIkJrP9SUzZReywes8IWWZoaf95pHT5Ww/bDja7A7AhANst340Psb2WyXC5HYALvhj4JlrqlWz/fNwOTMhFcP702Y+118NWAlsHJuYiOI/6wmMcqX5whHh1wQeB73t+9J62PVoQLRu3jxZ8pfqcB4j9oFgCm9s+bBh6jJ+CKKztcduLG7dm7eMGXcfrh22PWglquAOoQc/xC/GCHrYS2MwOwAZt24U349fY+/xlyHXAK0kLX+QjbEY3fR6rDLdm3RJlKVlV2UxYL8Rtu+jHrrbSa0r5ZHVisD2opKSHo0ululKcGqjpoYTTAHDCanG1gWS9CqMK4EBpSZPM79dVCtYkINAPgU/Du6E1imI5tYCEod/RGETO1be/9KtRMB7//fGB3X42byZGX037yFccOlQ5GFTT1iU72bXKwSYo/11eYNRA6vOqqorin6OLb+zGvr4xg2/fnz6F6J8P814hjnyBokMKYWGjaAFlHh+uEHLZd1MafyurLy+dsVte0tc8sj12LdVl1KpAMNXXYPnE6o0+oyHnJF2K1anP+PZkndMpOotK/AILMK5J700JJIyO4PTbTgKZRDhtQWlIBf1tt10YYVSUxm1dx7E+LxzJuQjlc8hGy85ClJoDSTsaomJ9UAhSTboFazybzeUclEW3XYAbfBOsk8oV3eaaEhEuagsi5QCoKOjcYBnuI3TrpSrc2j79ezzsgxpHVOtFcl1ut7k8hfrBPwSxweQedqtFsQKIbCRlX8XXPVpTM/j0SvHuSzF0fgElZdSpwcg1gmv3xRlTcvVctRtx3Ki50+W9Kpn3WuaU+T95h14wUKutXRELTN2WC+grn6uk1YMbYUKah8pT4aUsyv8vFYZVccFKb3IrTFB+mA6O2oMRHrjjjrpItbhDhiWn/JsMNtTfCwSwwFe+ThgRGEU0GwAqB034rCx97BzdmkH0Ndl08LN+rGnyBDouyTge50XSlytSwWXuIfad4msWyUH2PNkuThg4aqgWOWrIiX3TDooZ6OyLBHsnOIBvWhSd4XoIZEqPWrEqWYcUUxnSdyurt7mKoVbmwK2aA50BO6sv2m2wlVPFmgUbZos+dghHrXqlVZmL3BHv4189eGO3dbhhCveqQ3BnZddPAm5LOxDuKmalqeFWfImhU3A7DcMtnJxa4EbOoXjXp94wQXnRIbyzuS8ngTfWUF1o81VGIy882/aeIzO/oFMStfgX</diagram></mxfile>

**Comment by davidjgraph** [comment]
Do you have an [example](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this?

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
