### ISSUE TITLE
Getting Circular-Json Error while storing mxGraph configuration

### ISSUE THREAD

**Issue by sachinpatil1920** [jgraph/mxgraph#394]
Hi folks,

I am able to integrate mxGraph with angular8 but i am facing some issue please help me in that,

Steps:-
1. I have drag and drop the two edges in canvas connected two boxes, for each edges/boxes mxGraph create the json.
2.Now i am trying to save this json object in the localStorage then getting Circular-JSON error.

**Comment by davidjgraph** [comment]
Your question is seeking debugging help but needs more information. The question should be updated to include desired behavior, a specific problem or error, and the shortest code necessary to reproduce the problem.
