### ISSUE TITLE
CSS class for edge

### ISSUE THREAD

**Issue by GLeBaTi** [jgraph/mxgraph#395]
Hello. How can i use css class for edges?

Now i can use only style from code:
```
let lineStyle = "strokeColor=rgb(96,96,96);";
let newEdge = graph.insertEdge(parent, line.line_id, '', from.vertex, to.vertex, lineStyle );
```

Maybe something like:
`newEdge.class = ".agLine"; `

**Comment by davidjgraph** [comment]
See [named styles](https://jgraph.github.io/mxgraph/docs/manual.html#3.1.3.1)
