### ISSUE TITLE
Can I use mxgraph with Angular2+ and NodeJS?

### ISSUE THREAD

**Issue by hooshbartar** [jgraph/mxgraph#397]
Hi,
I am not a web developer but I know a little about it. I have a company and we need something like GraphEditor for our app. Our developers work with Angular2+ and NodeJS. I liked to know can they use GraphEditor as an open source project in our project? Is it integrable with technologies we use easily or it's better to search for other projects?

Thanks

**Comment by davidjgraph** [comment]
Given your summary I would seek a commercial diagramming library.
