### ISSUE TITLE
Contextmenu error when using custom conditions

### ISSUE THREAD

**Issue by Kenjekenny** [jgraph/mxgraph#398]
In a project i'm working on, i have different types of XML nodes and i want to have different menu options in the context menu based on the type of XML node that is selected. I used the following custom condition:

```
<mxEditor>
	<mxDefaultPopupMenu as="popupHandler">

		<condition name="activity"><![CDATA[
			function (editor, cell, evt) {
				return cell.value.nodeName == "Activity";
			}]]>
		</condition>

<add as="Activity type" if="activity">
		<add as="Activiteit" action="setTypeActivity" icon="images/rectangle.gif"/>
		<add as="Decompositie" action="setTypeDecomp" icon="images/decomp.gif"/>

	</mxDefaultPopupMenu>
</mxEditor>
```
This works fine and displays the additional menu options only if the selected object is a Activity. However the contextmenu no longer works when right clicking the graph background and casts an error message to the log.

> Uncaught TypeError: Cannot read property 'value' of null
>     at _mxJavaScriptExpression (eval at eval (mxUtils.js:232), <anonymous>:3:17)
>     at mxDefaultPopupMenu.createConditions (mxDefaultPopupMenu.js:301)
>     at mxDefaultPopupMenu.createMenu (mxDefaultPopupMenu.js:158)
>     at mxEditor.createPopupMenu (mxEditor.js:2865)
>     at mxEditor.<anonymous> (mxEditor.js:1652)
>     at mxPopupMenuHandler.factoryMethod (mxUtils.js:208)
>     at mxPopupMenuHandler.mxPopupMenu.popup (mxPopupMenu.js:513)
>     at mxPopupMenuHandler.mouseUp (mxPopupMenuHandler.js:188)
>     at mxGraph.fireMouseEvent (mxGraph.js:12715)
>     at mxGraphView.<anonymous> (mxGraphView.js:2607)

If i remove the custom condition, the context menu works on the background again. 

Thx in advance!

**Comment by davidjgraph** [comment]
Exactly which version of mxGraph are you using? What's on line 301 of mxDefaultPopupMenu.js?

**Comment by ashrafteleb** [comment]
You need to check if cell is null
change `return cell.value.nodeName == "Activity";` to `if (cell != null && cell.value != null) return cell.value.nodeName == "Activity"; else return false;`

**Comment by ga5tan** [comment]
@Kenjekenny how do you load you rXML config into grapheditor?
I was unable to achieve it. 
thank you

**Comment by Kenjekenny** [comment]
@ga5tan 
I'm not exactly sure which XML you are refering to, but i assume it's the XML config for the popupmenu. I hope this helps!

**Code** 
```
//Instantiate editor
window.editor = new mxEditor();
window.graph = editor.graph;

//Editor configuration
var config = mxUtils.load('config/editor-config.xml').getDocumentElement();
mxObjectCodec.allowEval = true;
editor.configure(config);
```
**editor-config.xml**
```
<mxEditor defaultGroup="decompositie" defaultEdge="connector" defaultVertex="activity">
	<ui>
		<add as="toolbar" element="toolbar"/>
		<add as="status" element="status"/>
		<add as="graph" element="graph"/>
	</ui>

	<mxGraph as="graph">
		<include name="config/stylesheet.xml"/>
	</mxGraph>
 
	<include name="config/key-handler.xml"/>
	<include name="config/templates.xml"/>
	<include name="config/toolbar-config.xml"/>
	<include name="config/popup-handler.xml"/>
	<include name="config/actions.xml"/>
	
</mxEditor>
```
**popup-handler.xml**
```
<mxEditor>
		<mxDefaultPopupMenu as="popupHandler">

		<!-- Check if the selected object is a activity -->
		<condition name="activity"><![CDATA[
			function (editor, cell, evt) {
				if (cell != null && cell.value != null) {
					return cell.value.nodeName == "Activity";
				} else {
					return false;
				}
			}]]>
		</condition>

		<!-- Sub-menu if the selected object is a activity -->
		<add as="Activity type" if="activity">
			<add as="Activiteit" action="setTypeActivity" icon="images/rectangle.gif"/>
			<add as="Decompositie" action="setTypeDecomp" icon="images/decomp.gif"/>
		</add>

	</mxDefaultPopupMenu>
</mxEditor>
```
