### ISSUE TITLE
Performance Issues: Data Virtualization 

### ISSUE THREAD

**Issue by AlexETF** [jgraph/mxgraph#41]
Hello,

I am currently facing with some performance issues in my application and I was wondering if there are any advises from you guys how to avoid them.

I was thinking that data virtualization might be solution for my problems and my question is, what would be the proper way to implement such thing in mxgraph ?

Thanks in advance.

**Comment by davidjgraph** [comment]
You've given zero details other then you have "some performance problems". In software engineering there are standard ways to submit bugs, it's worth reading http://www.chiark.greenend.org.uk/~sgtatham/bugs.html and re-submitting a proper report.

**Comment by AlexETF** [comment]
Sorry for lacking details, but my question was general. 
I am interested in data virtualization and proper way to implement this in mxgraph. 

May I open another issue where I specify details of my problem ?

Thanks for the article.

**Comment by davidjgraph** [comment]
You're welcome to open a specific issue, I've don't really understand how data virtualization applies in mxGraph, but someone else might.
