### ISSUE TITLE
Error in mounted hook (Promise/async): "TypeError: Illegal constructor"

### ISSUE THREAD

**Issue by liuqiyu** [jgraph/mxgraph#416]
Hello, when I use NPM to generate editing tools with mxgraph. The following error message appears:
![image](https://user-images.githubusercontent.com/19789062/71141816-53fc6780-2250-11ea-8907-5e5eccfa3ac3.png)

The XML file is as follows:

<mxGraphModel>
  <root>
    <mxCell id="0"/>
    <mxCell id="1" parent="0"/>
    <mxCell id="4" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;exitX=0.25;exitY=1;exitDx=0;exitDy=0;entryX=0.5;entryY=0;entryDx=0;entryDy=0;" parent="1" source="2" target="3" edge="1">
      <mxGeometry relative="1" as="geometry"/>
    </mxCell>
    <mxCell id="2" value="" style="rounded=0;whiteSpace=wrap;html=1;" parent="1" vertex="1">
      <mxGeometry x="159" y="152" width="120" height="60" as="geometry"/>
    </mxCell>
    <mxCell id="3" value="" style="rounded=1;whiteSpace=wrap;html=1;" parent="1" vertex="1">
      <mxGeometry x="94" y="309" width="120" height="60" as="geometry"/>
    </mxCell>
    <mxCell id="5" value="" style="curved=1;endArrow=classic;html=1;" parent="1" edge="1">
      <mxGeometry width="50" height="50" relative="1" as="geometry">
        <mxPoint x="211" y="138" as="sourcePoint"/>
        <mxPoint x="261" y="88" as="targetPoint"/>
        <Array as="points">
          <mxPoint x="261" y="138"/>
          <mxPoint x="211" y="88"/>
        </Array>
      </mxGeometry>
    </mxCell>
  </root>
</mxGraphModel>

Error reporting scenario: when using curve and drag line waypoints

**Comment by liuqiyu** [comment]
<mxGraphModel>
  <root>
    <mxCell id="0"/>
    <mxCell id="1" parent="0"/>
    <mxCell id="4" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;exitX=0.25;exitY=1;exitDx=0;exitDy=0;entryX=0.5;entryY=0;entryDx=0;entryDy=0;" parent="1" source="2" target="3" edge="1">
      <mxGeometry relative="1" as="geometry"/>
    </mxCell>
    <mxCell id="2" value="" style="rounded=0;whiteSpace=wrap;html=1;" parent="1" vertex="1">
      <mxGeometry x="159" y="152" width="120" height="60" as="geometry"/>
    </mxCell>
    <mxCell id="3" value="" style="rounded=1;whiteSpace=wrap;html=1;" parent="1" vertex="1">
      <mxGeometry x="94" y="309" width="120" height="60" as="geometry"/>
    </mxCell>
    <mxCell id="5" value="" style="curved=1;endArrow=classic;html=1;" parent="1" edge="1">
      <mxGeometry width="50" height="50" relative="1" as="geometry">
        <mxPoint x="211" y="138" as="sourcePoint"/>
        <mxPoint x="261" y="88" as="targetPoint"/>
        <Array as="points">
          <mxPoint x="261" y="138"/>
          <mxPoint x="211" y="88"/>
        </Array>
      </mxGeometry>
    </mxCell>
  </root>
</mxGraphModel>

**Comment by liuqiyu** [comment]
`<mxGraphModel>
  <root>
    <mxCell id="0"/>
    <mxCell id="1" parent="0"/>
    <mxCell id="4" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;exitX=0.25;exitY=1;exitDx=0;exitDy=0;entryX=0.5;entryY=0;entryDx=0;entryDy=0;" parent="1" source="2" target="3" edge="1">
      <mxGeometry relative="1" as="geometry"/>
    </mxCell>
    <mxCell id="2" value="" style="rounded=0;whiteSpace=wrap;html=1;" parent="1" vertex="1">
      <mxGeometry x="159" y="152" width="120" height="60" as="geometry"/>
    </mxCell>
    <mxCell id="3" value="" style="rounded=1;whiteSpace=wrap;html=1;" parent="1" vertex="1">
      <mxGeometry x="94" y="309" width="120" height="60" as="geometry"/>
    </mxCell>
    <mxCell id="5" value="" style="curved=1;endArrow=classic;html=1;" parent="1" edge="1">
      <mxGeometry width="50" height="50" relative="1" as="geometry">
        <mxPoint x="211" y="138" as="sourcePoint"/>
        <mxPoint x="261" y="88" as="targetPoint"/>
        <Array as="points">
          <mxPoint x="261" y="138"/>
          <mxPoint x="211" y="88"/>
        </Array>
      </mxGeometry>
    </mxCell>
  </root>
</mxGraphModel>`

**Comment by liuqiyu** [comment]
```
<mxGraphModel>
  <root>
    <mxCell id="0"/>
    <mxCell id="1" parent="0"/>
    <mxCell id="4" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;exitX=0.25;exitY=1;exitDx=0;exitDy=0;entryX=0.5;entryY=0;entryDx=0;entryDy=0;" parent="1" source="2" target="3" edge="1">
      <mxGeometry relative="1" as="geometry"/>
    </mxCell>
    <mxCell id="2" value="" style="rounded=0;whiteSpace=wrap;html=1;" parent="1" vertex="1">
      <mxGeometry x="159" y="152" width="120" height="60" as="geometry"/>
    </mxCell>
    <mxCell id="3" value="" style="rounded=1;whiteSpace=wrap;html=1;" parent="1" vertex="1">
      <mxGeometry x="94" y="309" width="120" height="60" as="geometry"/>
    </mxCell>
    <mxCell id="5" value="" style="curved=1;endArrow=classic;html=1;" parent="1" edge="1">
      <mxGeometry width="50" height="50" relative="1" as="geometry">
        <mxPoint x="211" y="138" as="sourcePoint"/>
        <mxPoint x="261" y="88" as="targetPoint"/>
        <Array as="points">
          <mxPoint x="261" y="138"/>
          <mxPoint x="211" y="88"/>
        </Array>
      </mxGeometry>
    </mxCell>
  </root>
</mxGraphModel>
```

**Comment by liuqiyu** [comment]
website: https://liuqiyu.github.io/core-editor/#/editor

**Comment by davidjgraph** [comment]
Your quetsion is seeking debugging help but needs more information. The question should be updated to include desired behavior, a specific problem or error, and the shortest code necessary to reproduce the problem.
