### ISSUE TITLE
.net nuget package

### ISSUE THREAD

**Issue by PaulVrugt** [jgraph/mxgraph#417]
Is there any reason why there is no nuget package for the .net library? We are browsing through all non-nuget references we have in our projects, and I'd expect there to be a nuget package for this component, so we can easily integrate it in our CI builds are maintain versions.

**Comment by Diaskhan** [comment]
There is no support for dot net!
Is deprecated !

Nuget could only be added for js stack!

**Comment by PaulVrugt** [comment]
@Diaskhan where did you find the info about .net support being deprecated?

**Comment by Diaskhan** [comment]
https://github.com/jgraph/mxgraph/issues/345

Here !
