### ISSUE TITLE
The library searches for a non-existent file

### ISSUE THREAD

**Issue by unbegrenzt** [jgraph/mxgraph#419]
regards

### current result:
-The library is looking for a non-existent file in the path: ~/lib/mxGraph/resources/graph_es.txt.
![image](https://user-images.githubusercontent.com/19624703/72111984-f49af000-3301-11ea-8573-9de8364eb45e.png)

### expected result:
The library should take these files by default if they do not exist
![image](https://user-images.githubusercontent.com/19624703/72112277-bb16b480-3302-11ea-9584-b3b5358fd31c.png)

Maybe I am using the library erroneously, however I thank you for your attention and response.

**Comment by davidjgraph** [comment]
Is the browser being used install in Spanish, maybe?

**Comment by unbegrenzt** [comment]
Yes, the browser is in spanish.

**Comment by ralequi** [comment]
I'm very new with this library, however it seems to be a locale-issue.
Have you tried to copy editor/graph.txt to editor_es/graph_es.txt as a quick work around? The lang would be still in English but it may work.

**Comment by davidjgraph** [comment]
Yes, you'd either have to make the _es file return the English version, or implement the Spanish translation.
