### ISSUE TITLE
How to disable click?

### ISSUE THREAD

**Issue by glebov21** [jgraph/mxgraph#420]
Hi. How can i disable click on my text element?
I have background and text lable. How can i prevent click event on lable? How make it "not interactable"?

```
let background = graph.insertVertex(parent, 1, "bg", 0, 0, screenW, screenH, bgStyle);
let text = graph.insertVertex(parent, 2, "text", 10, 10, w, h, textStyle);

graph.addListener(mxEvent.CLICK, (sender, evt) => {
            if (evt.properties.cell) {
                let cellId = evt.properties.cell.id;
                if(cellId  == 1)
                        console.log("on background click");
            }
        });
```

**Comment by PrudhviMadasu** [comment]
Instead of click event use

  graph.isCellEditable = function (cell) {
            if (cell.style == 'style 1') {
                return false;
            } else {
                return true;
            }
        };
