### ISSUE TITLE
[BUG] source and target not encoded when using mxCodec

### ISSUE THREAD

**Issue by mbmaeso** [jgraph/mxgraph#423]
Hello, I found out that this code example from mxCodec to encode a graph model does not work as expected:
```
var encoder = new mxCodec();
var result = encoder.encode(graph.getModel());
var xml = mxUtils.getXml(result);
```
When a normal mxGraph instance is provided, everything is encoded correctly except the attributes 'source' and 'target' of  an edge, the same that [happens in this stackoverflow chat](https://chat.stackoverflow.com/rooms/196301/discussion-between-sankalp-kataria-and-nickath), which is not resolved yet (if @Nickath eventually discovered why that happens, it would be really a big help).

While debugging, the method `mxCodec.prototype.getId()` returns false when it checks if an Edge is an instance of mxCell. How could it be fixed?

Working code:

```
const encoder = new mx.mxCodec();
const xmlNode = encoder.encode(graph.getModel());
```

Input graph:
![graph](https://user-images.githubusercontent.com/17617795/72427351-dd3d8600-378b-11ea-849c-7d6370dc9eec.PNG)

Graph information:
![graph_info](https://user-images.githubusercontent.com/17617795/72427564-4ae9b200-378c-11ea-91ea-1caaeda46f46.PNG)

Edge when encode() is called
![edge_encode](https://user-images.githubusercontent.com/17617795/72431311-cd766f80-3794-11ea-85e8-9dc6f0484887.PNG)

Encoding source and value of the edge 
![edge_encodeObject(source)](https://user-images.githubusercontent.com/17617795/72431346-eb43d480-3794-11ea-9c71-1251df5b552c.PNG)

method getId() that returns null when checking source's value
![edge_getId(source)](https://user-images.githubusercontent.com/17617795/72431409-12020b00-3795-11ea-9982-909e27a51c10.PNG)

Also, I am using the `mxObjectCodec.encode` written in the [jsondata.html](https://github.com/jgraph/mxgraph/blob/master/javascript/examples/jsondata.html) example:

```
  constructor(private _electronService: ElectronService) {
    this.objectCodec = new mx.mxObjectCodec(new EdgeData());
    this.objectCodec.encode = (enc, obj) => {
      const node = enc.document.createElement('EdgeData');
      mx.mxUtils.setTextContent(node, JSON.stringify(obj));
      return node;
    };
    mx.mxCodecRegistry.register(this.objectCodec);
  }
```
Output when encode is finished:
```
<mxGraphModel>
    <root>
        <mxCell value="Started" id="2" vertex="1">
            <mxGeometry x="140" y="30" width="80" height="40" as="geometry"/>
        </mxCell>
        <mxCell value="Stopped" id="3" vertex="1">
            <mxGeometry x="140" y="190" width="80" height="40" as="geometry"/>
        </mxCell>
        <mxCell id="4" edge="1">
            <EdgeData as="value">{"name":"stopCar","parameters":[]}</EdgeData>
            <mxGeometry relative="1" as="geometry"/>
        </mxCell>
    </root>
</mxGraphModel>
```

I am developing this using angular 7, electron and the version 4.0.5 of mxgraph.

Thank you in advance!

**Comment by mbmaeso** [comment]
@jromerob I saw that you wrote a similar issue in #372, could you have a look? It will help me a lot

**Comment by davidjgraph** [comment]
Do you have a https://stackoverflow.com/help/minimal-reproducible-example in plain JavaScript with Angular or Electron?

**Comment by mbmaeso** [comment]
I tried to recreate it through a Stackblitz app, but it is not performing the same behavior as in local. If someone encounters this problem again, I would recommend to continue the discussion [here](https://chat.stackoverflow.com/rooms/196301/discussion-between-sankalp-kataria-and-nickath). However, many thanks for your interest
