### ISSUE TITLE
how could implement only allowing arrow end with top of cell and start from bottom of cell

### ISSUE THREAD

**Issue by chgitcrazy** [jgraph/mxgraph#424]
I would like implement the arrow connection  constraints according to the following scene:
When a user want to connecting node A to node B, only allow connect from bottom point of A to the top point of B and disable start with top point of A and end with bottom  point of B;
Above all , I want to add constraints  on vertex point, if a vertex has four point : top ,bottom , left ,right; it would constraint the direction of arrow at specific point of vertex;
How can I implement this function? Does the mxGraph library support this?

**Comment by chgitcrazy** [comment]
fixed

**Comment by Exlord** [comment]
> 
> 
> fixed

Could you share the code on how did you fix this?
