### ISSUE TITLE
Cross-Site Scripting: DOM

### ISSUE THREAD

**Issue by qiank128** [jgraph/mxgraph#426]
Abstract:

The method popup() in mxClient.min.js sends unvalidated data to a web browser on line 89, which can result in the browser executing malicious code.

**Comment by alderg** [comment]
All HTML Entities are converted in the output.

**Comment by davidjgraph** [comment]
@qiank128 Without an exact reproduction case we'll have to close this. You are welcome to submit such a case and we'll consider it.
