### ISSUE TITLE
website: broken links to PHP

### ISSUE THREAD

**Issue by mytskine** [jgraph/mxgraph#429]
On the public homepage <https://jgraph.github.io/mxgraph/> the links "PHP" are broken. Each one is the first link under "Installation & Examples" and "API Specifications".

On a side note about the web site, I could not find there any link to the source code, nor any link to Github. Even "Installation and Example / Javascript" had not a word about that or any real *installation* on a server.

These two problems made me wonder if the project was still alive, or if it had changed its licence. I've now seen this isn't the case.

**Comment by davidjgraph** [comment]
Updated links upstream, thanks for report.
