### ISSUE TITLE
Prevent graph expand beyond container bounds

### ISSUE THREAD

**Issue by nssantos** [jgraph/mxgraph#43]
Is it possible to prevent the cells expand[overcome] the container limits? I.e. When I move any cell, I'd like it does not create a scroll bar.

**Comment by smallCoderZhou** [comment]
hi, do you resolve this problem? i don't want expand the canvas while cell move out canvas.

**Comment by davidjgraph** [comment]
[mxGraph.autoExtend](https://jgraph.github.io/mxgraph/docs/js-api/files/view/mxGraph-js.html#mxGraph.autoExtend)

**Comment by baio** [comment]
`mxGraph.autoExtend = true` will still expand canvas when left part of the dropped figure on the canvas and right is out
