### ISSUE TITLE
Does mxGraph support a sub-process container?

### ISSUE THREAD

**Issue by besley** [jgraph/mxgraph#430]
In my case, the sub process is needed to embeded in a main process, and it seemed that we can put these sub process activities elements into a group box, this box can be connected to the nodes from main process. the picture is similary here:
[sub process box container exmaple](https://www.sparxsystems.com/enterprise_architect_user_guide/14.0/model_simulation/event_sub_process.html)

By the way, is message flow supported when crossing two different swimlanes? the style of message flow usually is dashed line in toolbox.

Thanks your reply, we really like mxGraph library.

**Comment by tbouffard** [comment]
@besley can you provide more context please?
It looks like you are working on a BPMN solution as most of the wording you are using are related to this business domain, so most mxGraph users won't know what you are talking about. So please, keep that in mind for a future question.

Here are some hints
- for a subprocess, you can create a mxRectangle vertex and make it be the parent of elements (vertexes and edges) that defined the subprocess content
- for message flow, this is an edge so you can assign it a dedicated style when creating it to have a dashed line. On insertion, you make the graph default parent as its parent to ensure it is displayed. You may have to experiment on this area if you want to manage lane collapsing and keep consistent display of the message flow

I am also currently working on a BPMN rendering solution based on mxGraph. I will be interesting in talking with you about use cases, implementation choices, targeted application

**Comment by besley** [comment]
@tbouffard , thanks your reply. This is very helpful to me. I have looked into the mxGraph examples in the project. By the way, I find swimlane control is also a choice to separate different processes. I am glad to talk about it with you.

**Comment by tbouffard** [comment]
@besley great to know you found a solution
Good catch about the swimlane: it can be a way to do it, especially as it already provides expand/collapse capabilities out of the box

**Comment by besley** [comment]
@tbouffard , I have a question, the customer suggested we use bpmn.io rather than mxGraph, How can I respond to their requirement? what's the benefit of these two projects each other?

**Comment by tbouffard** [comment]
@besley I guess you are talking about [bpmn-js](https://github.com/bpmn-io/bpmn-js/), mainly developed by Camunda.
If you need a BPMN modeler/editor, this is the way to go except if you want to develop a competitor lib which is going to be a large amount of work.
For BPMN viewing/visualization, this is a big amount of work as well. You can also have a look at [bpmn-visualization](https://github.com/process-analytics/bpmn-visualization-js), a Typescript lib using `mxGraph` that I am working on and sponsored by Bonitasoft. Notice that this lib is in early development and is not BPMN features complete.

Be aware of the bpmn.io license which forces you to display the bpmn.io logo on the bottom right position of the diagrams (the license forbids you to remove it)
