### ISSUE TITLE
Register a shape which is a react component

### ISSUE THREAD

**Issue by sriramjv1219** [jgraph/mxgraph#435]
Hello Team,

 I am trying to register a shape which is basically a react component. 
Is it possible to do so? Kindly Help.

Thanks & Regards,
Sriram JV

**Comment by tbouffard** [comment]
@sriramjv1219 can you provide more details please?
your shape must extends the `mxShape` class as described in https://jgraph.github.io/mxgraph/docs/js-api/files/shape/mxShape-js.html
Can you describe the issue you encounter?
