### ISSUE TITLE
Out of memory using createTripleBuffer method when zooming in and out

### ISSUE THREAD

**Issue by hjxy2012** [jgraph/mxgraph#439]
Hello, I am using java swing version. My graph contains about 2000 cells. When I zoom in and out quickly, the createTripleBuffer may fail to create a triple buffer. How could I decrease the memory useage?  The code is as bellow.
protected void createTripleBuffer(int width, int height)
	{
		try
		{
			tripleBuffer = mxUtils.createBufferedImage(width, height, null);
			tripleBufferGraphics = tripleBuffer.createGraphics();

			// Repaints the complete buffer
			repaintTripleBuffer(null);
		}
		catch (OutOfMemoryError error)
		{
			log.log(Level.SEVERE, "Failed to create a triple buffer", error);
		}
	}

**Comment by davidjgraph** [comment]
https://github.com/jgraph/mxgraph

**Comment by hjxy2012** [comment]
Sorry. I would close this issue.
