### ISSUE TITLE
Keyboard support disabling

### ISSUE THREAD

**Issue by vihanga-liyanage** [jgraph/mxgraph#44]
This is regarding the diagrameditor located in [here](https://jgraph.github.io/mxgraph/javascript/examples/editors/diagrameditor.html).
Keyboard shortcuts such as delete and undo is supported for this editor. You can select a cell and hit del key to delete and ctrl + z also do work. But if you view the source and come back again, those keys won't function. You can restore the functionalities by dropping a new cell from the pallet. Otherwise non of the keys work. Can we do something about this?

**Comment by alderg** [comment]
Probably a focus issue. That said, it works for me in Chrome and Firefox. What browser are you using? What are the exact steps to reproduce this problem?

**Comment by vihanga-liyanage** [comment]
First of all I'm using ubuntu and I think that's the case. I tried both firefox and chromium browsers on my ubuntu laptop and they both seems to have this issue. But windows one worked just fine. Follow are the steps.

- Drag and drop a rectangle, rounded and an ellipse.
- Connect two cells.
- Press dlt key to make sure you can delete that connection. Also select one of the three cells and try to delete it as well.
- Check the source checkbox to view source and then uncheck it.
- Try deleting a cell again by selecting and pressing dlt key.

If you drag and drop a new cell, you'll be able to use the dlt key again.

**Comment by alderg** [comment]
Setting the tabindex attribute of the DIV should fix this, eg. <div id="graph" tabindex="-1" ...

**Comment by vihanga-liyanage** [comment]
Thank you @alderg !
