### ISSUE TITLE
how to only move the edge position,not reconnect the source or target

### ISSUE THREAD

**Issue by hanlei840405** [jgraph/mxgraph#444]
I'm a newer to use mxgraph, when I pick the edge that was connected source and target,I just want to move its position to avoid other cells, I dont want the edge reconnect other source or target by the point which the mouse click up.
Please! Thank you!

**Comment by PrudhviMadasu** [comment]
Use below function and return true if edge
graph.isCellMovable = function (cell) {
 if (this.model.isEdge(cell)){
return true;
}
}
