### ISSUE TITLE
Initiating mxEditor with XML layout fails randomly (v3.3.0.0)

### ISSUE THREAD

**Issue by janakapod** [jgraph/mxgraph#445]
I am working in a project where we are using mxGraph with the client version [3.3.0.0 ](https://github.com/jgraph/mxgraph/commit/731bcee03bb50beb02c3a213a5432a558d49e849). As part of one of the features I was looking into loading a graph created by users in one page to the other one with different styling implementations. This new page after retrieving XML to load the data using `mxUtils.load()` the code is using new instance of mxEditor.

When the page tries to load the mxEditor it fails randomly to fail with the following error:

![image](https://user-images.githubusercontent.com/4319195/78034398-501ace00-7385-11ea-8ac9-111c734b1b1e.png)

and here is the code that I have used to initialize the mxEditor:

```
function graphInitializer() {
    let graph;
    let editor;
    let node;

    function read(graph) {
        let req = mxUtils.load('/urlLocation');
        let instanceData = JSON.parse(req.getText());
        let parser = new DOMParser();
        let root = parser.parseFromString(instanceData.graph, 'text/xml');
        root = root.firstElementChild;
        let dec = new mxCodec(root.ownerDocument);
    }

    mxGuide.prototype.isEnabledForEvent = function (evt) {
        return !mxEvent.isAltDown(evt);
    };

    mxEdgeHandler.prototype.snapToTerminals = true;
    mxGraphHandler.prototype.guidesEnabled = true;
    mxConstants.DEFAULT_HOTSPOT = 1;


    mxObjectCodec.allowEval = true;
    node = mxUtils.load('config/workfloweditor.xml').getDocumentElement();
    editor = new mxEditor(node); // fails in here
    mxObjectCodec.allowEval = false;
    graph = editor.graph;
    graph.getDefaultParent();
    graph.getModel().beginUpdate();
    try {
        read(graph);

    }
    finally {
        // Updates the display
        graph.getModel().endUpdate();
    }

    graph.setEnabled(false);
    graph.panningHandler.useLeftButtonForPanning = true;
    graph.panningHandler.panGraph(0, 15);

}

$(function () {
    graphInitializer();
});

```
(please note that I have removed some of the try catch blocks so that I could get the error in the developer console). When the above code executes successfully, first the code will call the server to retrieve the following xml file mentioned bellow:

**config/workfloweditor.xml:**
```
<mxEditor urlPost="https://servername">
	<ui>
		<add as="graph" element="graph" />
	</ui>
	<mxGraph as="graph">
		<include name="config/wfgraph-commons.xml" />
	</mxGraph>
</mxEditor>
```
And if the line of code `editor = new mxEditor(node);` successfully read the XML data returned from the the serer, it will request the XML file mentioned in here `<include name="config/wfgraph-commons.xml" />` in the first xml file. (Here is the   wfgraph-commons.xml as a text file: [wfgraph-commons.xml.txt](https://github.com/jgraph/mxgraph/files/4409958/wfgraph-commons.xml.txt)
 )

Unfortunately this is the point where it goes wrong. if the code `editor = new mxEditor(node);`  successfully read the file I can see another request to to the server to retrieve the second XML file. if not the error comes up in the Developer Console and there will be no request for the second XML file.

I would be grateful if someone could look into this issue and provide a solution.
Thanks!

**Comment by davidjgraph** [comment]
Could you please update to the latest mxGraph and post a complete, self-contained example that reproduces the problem?
