### ISSUE TITLE
graph.moveCells does not respect STYLE_MOVABLE

### ISSUE THREAD

**Issue by benwalch** [jgraph/mxgraph#447]
Thank you for this project! 

[moveCells implementation](https://github.com/jgraph/mxgraph/blob/master/javascript/src/js/view/mxGraph.js#L6067) of graph does move all given cells - even the ones with `style[mxConstants.STYLE_MOVABLE]` set to `false`.

Why is this important? Some Layout mechanisms use [updateGroupBounds](https://github.com/jgraph/mxgraph/blob/master/javascript/src/js/view/mxGraph.js#L4265) which in turn calls `moveCells` with all children. If there is a child vertex in the group which is defined to **not** be movable (by setting `mxConstants.STYLE_MOVABLE` key in the cell style to `false`) it gets moved regardless of that setting.

**Comment by PrudhviMadasu** [comment]
use below function to decide whihc style can move and restrict

graph.isCellMovable = function (cell) {
            try {

                if (cell.style.includes('style name 1')) {
                    return true;
                } else if (cell.style.includes('style name 2')) {
                    return true;
                } else {
                    return false;
                }
            } catch (e) {
            }
        };
