### ISSUE TITLE
How adjust the order of cells in a layout?

### ISSUE THREAD

**Issue by hbzb168** [jgraph/mxgraph#451]
The maxgraph is a great tool.
I used the mxCompactTreeLayout to automatically layout after created cells. 
But I can not find a way to adjust the order of cells.
Hope your help.
Thanks.

**Comment by girumasfaw** [comment]
If you are trying to move a given cells to the front or back, you can actually use the orderCells function.
To disable the ordering just set the back parameter to false after the vertex is inserted.
 `this.graph.orderCells(false,[cells])`
