### ISSUE TITLE
Problem with connections

### ISSUE THREAD

**Issue by wowowowowowowo** [jgraph/mxgraph#453]
Hi, mxGraph Team, mxGraph is a great tool!
We need a help :)

We are working in a project where we are using mxGraph version 4.1.1
We have a problem with connections.
We have a diagram with many components , the components are connected to each other.
For some connections we are setting connection-label (cell.value) using function like below:
```javascript
setConnectionName(name: string)
{
	const model = graph.getModel();
	model.beginUpdate();
	try {
		cell.value = name;
		graph.refresh(cell);
	} finally {
		model.endUpdate();
	}
}
```
When we set label for one connection, some other connections are moved.
Components are connected but connection path is getting different.

When we did not call
```javascript
graph.refresh(cell);
```
connections remain in correct place but connection label is not visible.
What we have to do in order to set connection label and make it visible without refreshing whole model.

Thanks in advance and thanks a lot for building mxGraph.

**Comment by PrudhviMadasu** [comment]
try using graph.view.refresh(cell); to refresh only that particular cell.

**Comment by wowowowowowowo** [comment]
Thank you very much @PrudhviMadasu but your solution does not work.

**Comment by davidjgraph** [comment]
You're editing the cell in-place. mxGraph is designed with an API layer to go through to create proper, undoable actions within a model update, see https://jgraph.github.io/mxgraph/docs/manual.html#3.1.2.1

`graph.getModel().setValue(name)` is the function to use to set the label.

**Comment by wowowowowowowo** [comment]
> `graph.getModel().setValue(name)` is the function to use to set the label.

I used it and it works perfect.
Cell label is changing despite I do not refresh whole model.
