### ISSUE TITLE
mxUtils.getStylename(s) not working

### ISSUE THREAD

**Issue by Weltii** [jgraph/mxgraph#456]
Hey, https://github.com/jgraph/mxgraph/blob/fa0863895a9b260ad4a94800f7ecf8fbae96e4a4/javascript/src/js/util/mxUtils.js#L3271
https://github.com/jgraph/mxgraph/blob/fa0863895a9b260ad4a94800f7ecf8fbae96e4a4/javascript/src/js/util/mxUtils.js#L3300

Should it be `indexOf('=') > 0` instead of `indexOf('=') < 0`? A character cant be at a position smaller than 0.

**Comment by davidjgraph** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf

"The indexOf() method returns the first index at which a given element can be found in the array, or -1 if it is not present."

**Comment by Weltii** [comment]
Okay, thats right, I expressed it very badly. I think that it should be `pairs[i].indexOf('=') > 0' 
because in the doc it is written that I get an array like this `[(stylename|key=value);]`. Is it < 0, than I get the pair only if the pair has no '='. My result of 'x=2;y=3;2' is ["2"]. Is it > 0 than I get ["x=2","y=3"], because there is a '=' in the pair. 

If this is not a bug, than I am a little bit confused about the function and I am happy if you can explain it to me.
```
getStylenames: function(style)
{
	var result = [];
	if (style != null)
		{
			var pairs = style.split(';');
			for (var i = 0; i < pairs.length; i++)
			{
				if (pairs[i].indexOf('=') < 0)
				{
					result.push(pairs[i]);
				}
			}
		}		
		return result;
	},
```

**Comment by davidjgraph** [comment]
mxGraph has the concept of stylenames where you can have a stand-alone stylename that represents a collection of styles. There is no "=" in that case. 

See https://jgraph.github.io/mxgraph/docs/manual.html#3.1.3.1

If you have a reproduction case, please create a [SSCCE](http://sscce.org/) using a service like codepen so I can see the problem without having to write the test case myself.

**Comment by Weltii** [comment]
Sorry that I answer so late. 
Here is my [example](https://codepen.io/weltii/pen/oNbvpYj) and I think I found my issue. 
I expect that `getStylenames()` return an array like `["width=200","height=200"]` if I put a style like `"ROUNDED;width=200;height=200"` in the function. But I will get the style `["ROUNDED"]`. Now it make sense for me! Next time I will read the manual more detailed.
The [jsDoc](https://github.com/jgraph/mxgraph/blob/fa0863895a9b260ad4a94800f7ecf8fbae96e4a4/javascript/src/js/util/mxUtils.js#L3281) of `getStylenames()` says that the function will return an array like `[(stylename|key=value);]`, if the function returns only the stylename / an array of stylenames, what means `(stylename|key=value);`? Is it mean an stylename **or** a key value pair can return? My first thought is, that it will return `["width=200","height=200"]` not `["ROUNDED"]`.

Next time I will ask first on stackoverflow, before I open an issue.
