### ISSUE TITLE
backwards incompatible changes in 4.1.1 javascript/mxClient.js

### ISSUE THREAD

**Issue by nkiesel** [jgraph/mxgraph#459]
We just tried to upgrade to 4.1.1 and this fails for us because `mxClient.getPrettyXml` calls `mxUtils.htmlEntities` for nodes of type `mxConstants.NODETYPE_TEXT`. Switching to `mxClient.getXml` does not help either because that calls `mxClient.getPrettyXml` for IE browsers (which is a browser we still must support).  The changelog does not really explain why these changes were applied.

Our node value is a `<![CDATA[hello]]>` and `htmlEntities` encoding means that when we read the node text via an XML parser we do not get `hello` but `<![CDATA[hello]]>`.

Is there a rationale for the changed behavior?

**Comment by davidjgraph** [comment]
https://github.com/jgraph/mxgraph2/commit/be5fb3c6a4478e9fe1cc7a8a29d452df0642ada4
