### ISSUE TITLE
examples/scrollbars.html appears to be broken

### ISSUE THREAD

**Issue by kjhughes** [jgraph/mxgraph#462]
The [scrollbars example](https://jgraph.github.io/mxgraph/javascript/examples/scrollbars.html) appears to be broken:

![Screen Shot 2020-06-07 at 12 45 34](https://user-images.githubusercontent.com/382841/83974675-19998c00-a8bd-11ea-858b-fcbe7b376647.png)

Same results on Chrome (Version 83.0.4103.97 (Official Build) (64-bit)) and FF (77.0.1 (64-bit)).

**Comment by ErnestasBaltinas** [comment]
Waiting for the fix.

**Comment by davidjgraph** [comment]
@ErnestasBaltinas please just thumbs up the original post, your post doesn't add anything constructive and just creates noise.
