### ISSUE TITLE
the direction of rotation is incorrect default

### ISSUE THREAD

**Issue by hungtcs** [jgraph/mxgraph#468]
The default rotation behavior is incorrect in some examples (for instances [Stencils][] and [DiagramEditor][DiagramEditor])，but in [Graph Editor][GraphEditor], this problem seems to be solved.  

[Stencils]: https://jgraph.github.io/mxgraph/javascript/examples/stencils.html
[DiagramEditor]: https://jgraph.github.io/mxgraph/javascript/examples/editors/diagrameditor.html
[GraphEditor]: https://jgraph.github.io/mxgraph/javascript/examples/grapheditor/www/index.html

**Comment by hungtcs** [comment]
I found it here, if overwite here, the rotation becomes correct

https://github.com/jgraph/mxgraph/blob/693c67a81ed33e0fcffc761c242e9eaafcaeb95a/javascript/examples/grapheditor/www/js/Graph.js#L9777-L9784

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
