### ISSUE TITLE
Implementation of alignment lines?

### ISSUE THREAD

**Issue by ahdekkers** [jgraph/mxgraph#469]
When using draw.io, as shapes are moved around the graph, alignment lines popup to indicate whether the centers/tops/bottoms of two shapes are lined up. Is this functionality present in the current java mxgraph?

**Comment by PrudhviMadasu** [comment]
Yes, use  JGraphpadFormatAction, check below PDF
http://read.pudn.com/downloads199/sourcecode/java/934521/JGraph/JGraph%20in%20Action.pdf
