### ISSUE TITLE
Custom Image Upload

### ISSUE THREAD

**Issue by nasr18** [jgraph/mxgraph#470]
Need an option to select image from computer like this

![image](https://user-images.githubusercontent.com/7514936/87378853-723f0180-c5ac-11ea-8e20-d9810099bdf7.png)

instead of this...
![image](https://user-images.githubusercontent.com/7514936/87378900-9569b100-c5ac-11ea-9fa7-e3a00490448c.png)

**Comment by breezefaith** [comment]
Maybe you should take a look at the example of Drop.
