### ISSUE TITLE
How to clear the graph and create a new one ?

### ISSUE THREAD

**Issue by rudaoshi** [jgraph/mxgraph#474]
1. deleting all cells does not clear the shown graph
2. clear() the model results in adding new vertex failed.

**Comment by tbouffard** [comment]
@rudaoshi can you please provide more detatils?
- what is the mxgraph version you are using?
- what is the `adding new vertex failed.` error?
- in all examples I know, calling `model.clear()` clears the model and new vertex can be added when enclosed within the regular `model.beginUpdate()`/` model.endUpdate()`

**Comment by PrudhviMadasu** [comment]
Try this, it works for me
            graph.removeCells(graph.getChildVertices(graph.getDefaultParent()));

**Comment by nayaksnigdha** [comment]
I am also facing the same issue as @rudaoshi. If I invoke graph.removeCells(graph.getChildVertices(graph.getDefaultParent())); as suggested, the vertices are removed but if there are dangling edges (unconnected edges) in the graph they are not removed. If I invoke model.clear() everything gets deleted, even dangling edges but then adding new vertex fails.

**Comment by nayaksnigdha** [comment]
I am also facing the same issue as @rudaoshi. If I invoke graph.removeCells(graph.getChildVertices(graph.getDefaultParent())); as suggested, the vertices are removed but if there are dangling edges (unconnected edges) in the graph they are not removed. If I invoke model.clear() everything gets deleted, even dangling edges but then adding new vertex fails.
