### ISSUE TITLE
npm package (latest version 4.2.0) factory method mxBasePath param not working

### ISSUE THREAD

**Issue by hungtcs** [jgraph/mxgraph#479]
the follow code to load mxgraph, but `mxBasePath` not working:
```typescript
import factory from 'mxgraph';
const mx = factory({
      mxBasePath: 'assets',
});
```

![image](https://user-images.githubusercontent.com/11692935/90102616-95a7c880-dd73-11ea-8f9b-62d9332a80da.png)

if set `window.mxBasePath = 'assets'` is working well.

this demo can reappear the issues: https://stackblitz.com/edit/js-yjyqmw

-----------
version: 4.2.0

**Comment by LittleBoBo-beep** [comment]
文件路径在public下开始查找的

**Comment by hungtcs** [comment]
您好 @LittleBoBo-beep，通过`factory`配置`mxBasePath`之后前缀应该生效的，但是这里没有，如果通过`window.mxBasePath`配置可以生效

**Comment by LittleBoBo-beep** [comment]
看报错信息是build文件，你可以把mxgraph静态文件放置到根目录下的public或者static文件下，之后mxBasePath属性值改为./public或者./static即可

**Comment by hungtcs** [comment]
@LittleBoBo-beep 您好，我的意思是通过factory方法配置`mxBasePath`不生效

**Comment by LittleBoBo-beep** [comment]
多说无益直接上代码
![Snipaste_2020-08-18_16-02-05](https://user-images.githubusercontent.com/50006337/90486881-3b8c7600-e16c-11ea-942d-4a4a0b8c7120.png)

**Comment by LittleBoBo-beep** [comment]
![Snipaste_2020-08-18_16-02-05](https://user-images.githubusercontent.com/50006337/90486950-5828ae00-e16c-11ea-9912-3639362fc76c.png)

**Comment by LittleBoBo-beep** [comment]
import mx from 'mxgraph'
const mxgraph = mx({
  mxBasePath: './mxgraph'
})
这是我使用的

**Comment by hungtcs** [comment]
> import mx from 'mxgraph'
> const mxgraph = mx({
> mxBasePath: './mxgraph'
> })
> 这是我使用的

您那里`mxBasePath`生效了么？

**Comment by LittleBoBo-beep** [comment]
生效了，你的不生效主要是mxGraph的静态资源存放位置不对

**Comment by hungtcs** [comment]
> 看报错信息是build文件，你可以把mxgraph静态文件放置到根目录下的public或者static文件下，之后mxBasePath属性值改为./public或者./static即可

`mxBasePath`就是用来配置资源路径的，你这里放到`public`或者`static`下，mxGraph默认就是从根目录下获取资源，所以你这里配不配`mxBasePath`没什么关系，如果你遇到了和我一样的问题，那么你的`mxBasePath`这里随便配什么路径都没有影响的，所以还是没生效， 

https://stackblitz.com/edit/js-yjyqmw

**Comment by tbouffard** [comment]
@hungtcs @LittleBoBo-beep could you please provide a summary of your conversion in english for non-chinese speaking people :smile_cat: ?
The issue you are describing seems close to #49

**Comment by hungtcs** [comment]
Hi @tbouffard! Sorry for the unintelligible discussion, here are no substantive progress in the above discussion. 
I have been trying to explain to @LittleBoBo-beep the assets location path is not related to this issues.

**Comment by Diaskhan** [comment]
@hungtcs i ve understand what u trying to say.
The problem that the mxgraph is legacy library.
thats work for me!

```
import factory from 'mxgraph';

 const graphConfig = {
    mxBasePath: './assets/',
    mxImageBasePath: './assets/images',
    mxLanguage: 'en',
    mxDefaultLanguage: 'en',
    loadDefaultBundle:true,
    mxLoadResources: false,
    mxLoadStylesheets: false,
    mxForceIncludes: false,  
    mxResourceExtension: '',  
};

 Object.keys(graphConfig).map(k => {
     window[k] = graphConfig[k];
 })

const mx =factory ({});
var k=new mx.mxGraph(document.getElementById('graphContainer'));

```
This must be in html file !
```
<div id="graphContainer"
	</div>
```
