### ISSUE TITLE
validation

### ISSUE THREAD

**Issue by vachiin** [jgraph/mxgraph#48]
[validation.zip](https://github.com/jgraph/mxgraph/files/742038/validation.zip)

Example changed like this:

> 				// Source nodes needs 2 connected Targets
> 				graph.multiplicities.push(new mxMultiplicity(
> 				   true, 'Source', null, null, 2, 2, ['Target'],
> 				   'Source Must Have 2 Targets',
> 				   'Source Must Connect to Target'));

There is not error info when Source has 1 edge to Target.

Resolution, I think it should be like this in mxGraph.js:

```
mxGraph.prototype.getCellValidationError = function(cell)
{
	var outCount = this.model.getDirectedEdgeCount(cell, true);
	var inCount = this.model.getDirectedEdgeCount(cell, false);
	var value = this.model.getValue(cell);
	var error = '';

	if (this.multiplicities != null)
	{
		for (var i = 0; i < this.multiplicities.length; i++)
		{
			var rule = this.multiplicities[i];
			
			if (rule.source && mxUtils.isNode(value, rule.type,
				rule.attr, rule.value) && (outCount > rule.max || outCount < rule.min))
			{
				error += rule.countError + '\n';
			}
			else if (!rule.source && mxUtils.isNode(value, rule.type,
					rule.attr, rule.value) && (inCount > rule.max || inCount < rule.min))
			{
				error += rule.countError + '\n';
			}
		}
	}
	
	return (error.length > 0) ? error : null;
};

```

**Comment by alderg** [comment]
Thanks for the report, this will be fixed in the next release.
