### ISSUE TITLE
Draggable graph using mxgraph

### ISSUE THREAD

**Issue by govinda18** [jgraph/mxgraph#481]
I am new to mxgraph and want to create a behaviour to drag the entire graph. The behaviour is expected to be similar to this(from cytoscape):

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/mMza7.gif

Any way to achieve this in mxgraph?

**Comment by tbouffard** [comment]
@govinda18 mxGraph calls this feature `panning`, see https://jgraph.github.io/mxgraph/docs/js-api/files/view/mxGraph-js.html#mxGraph.setPanning and information about panning in this documentation

**Comment by tbouffard** [comment]
Same question on stackoverflow: https://stackoverflow.com/questions/63486608/panning-event-for-mxgraph
