### ISSUE TITLE
mxEvent.isLeftMouseButton(); dont work

### ISSUE THREAD

**Issue by tomerdad** [jgraph/mxgraph#485]
Some of the mxEvent don't work
I tried to use this but after many time that I search On the internet, I found that this event don't work
what I can do to fix this?
(it happens to mxEvent.isRightMouseButton() and also to the middle button maybe to more)

**Comment by PrudhviMadasu** [comment]
As I didnt see code, assuming evt is null
Try calling event inside addListener

graph.addListener(mxEvent.click, function (sender, evt) {
mxEvent.isRightMouseButton(evt)
}
