### ISSUE TITLE
Avoid intersection between edges

### ISSUE THREAD

**Issue by jaykumar-parmar** [jgraph/mxgraph#488]
Hi,

Is it possible to avoid intersection automatically between edges when vertexes are connected ? 

Current behavior : 
![image](https://user-images.githubusercontent.com/14372061/94008139-1a98ef80-fdc0-11ea-97c1-9eeb30be12a2.png)

Expected behavior : 
![image](https://user-images.githubusercontent.com/14372061/94008166-2ab0cf00-fdc0-11ea-812d-84b3c91e3772.png)

**Comment by davidjgraph** [comment]
No, that's not currently supported.
