### ISSUE TITLE
mxDragSource previewOffset is used but never declared

### ISSUE THREAD

**Issue by SilkyAlex** [jgraph/mxgraph#493]
previewOffset variable is used to make an offset when dragging cell on the graph
but is never declared or have a setter

mxClient.js:

```javascript
if (this.previewOffset != null)
{
    x += this.previewOffset.x;
    y += this.previewOffset.y;
}
```

**Comment by davidjgraph** [comment]
https://github.com/jgraph/mxgraph2/commit/e895c9280bc902be8df14bd503cbd027d0125035
