### ISSUE TITLE
Background image doesn't fill/fit or have opacity key

### ISSUE THREAD

**Issue by Henke-visual** [jgraph/mxgraph#494]
I would really like to have some more options regarding the page background image. 

When using the page background image option there is no setting for opacity. 
A background image very often has to be "dimmed" not to interfere with the overlaying graphics. 
An opacity setting would solve that problem. 

![image](https://user-images.githubusercontent.com/63777424/94545133-6fb78400-024c-11eb-8c1d-7d59a68d44e6.png)

There are currently also no option to upload background images (url only) or to make the background to fit/fill the page.
![image](https://user-images.githubusercontent.com/63777424/94546403-20725300-024e-11eb-96e4-5725febcc5d7.png)

But when adding an image for a shape you have the option to also upload an image.
![image](https://user-images.githubusercontent.com/63777424/94546481-397b0400-024e-11eb-84f9-e1d56234c066.png)

**Comment by davidjgraph** [comment]
Is this a draw.io usage question or an mxGraph development question?

**Comment by Henke-visual** [comment]
Both :) But primarily for development

**Comment by PrudhviMadasu** [comment]
In MxGraph add below style to your CSS to fill image in graphcontainer

.graphcontainer {
    background: url('<image relative path>');
    width: 100%;
    height: 100vh;
}
