### ISSUE TITLE
Label isn't in correct position after adding direction:rtl style

### ISSUE THREAD

**Issue by cdaria** [jgraph/mxgraph#497]
We use mxgraph for drawing workflow, and the label strings doesn't display on the workflow only in Arabic（have the style  direction:rtl ）, while they covered on the right of the page after upgrading mxgraph2.3.0.1 to 4.2.0.
I find and test the jgraph example--  [**secondlabel.html**](https://github.com/jgraph/mxgraph/blob/master/javascript/examples/secondlabel.html ) which is similar to how we use
The following screenshot shows the running result: the sencondlabels are beside to the rectangles, but they floats to the right after adding direction:rtl in graphContianer div.
![image](https://user-images.githubusercontent.com/15853617/95973320-10f62b00-0e46-11eb-8828-0f4f35d078ac.png)
After adding direction:rtl
![image](https://user-images.githubusercontent.com/15853617/95974134-23bd2f80-0e47-11eb-83ed-d3a1b33076bb.png)
I'm not sure if this is a bug or what. I was wondering if you would give me some advice.

**Comment by davidjgraph** [comment]
https://stackoverflow.com/help/how-to-ask
