### ISSUE TITLE
how to add cells on absolute coordinates on mxgraph , coordinates gets changed when the MxGraph area is moved , dragged with mouse

### ISSUE THREAD

**Issue by ashrafmansuri7272** [jgraph/mxgraph#498]
Hi , 
I am facing a problem with cells creation on random points on mxGraph, it takes random points on mxGraph after double click and also when the cells is created it was far from the point where we double clicked to create ,
so this problem is creating the problem of overlapping of cells too .

is there any way so the mxGraph does not take the relative  coordinates like whenever i drag the mxGraph it's coordinates gets changed and there is not absolute coordinate , one time (x,y) on one place and other time it is away so 
is there any way to  fix the coordinates please provide the source code too.
![image](https://user-images.githubusercontent.com/60643228/96080566-f5863100-0ed4-11eb-9a3e-6879b59ae14a.png)

**Comment by davidjgraph** [comment]
https://stackoverflow.com/help/how-to-ask

**Comment by ashrafmansuri7272** [comment]
Hi @davidjgraph Updated the issue.
