### ISSUE TITLE
how to upload Images using mxgraph/mxdraw 

### ISSUE THREAD

**Issue by sachinpawar13** [jgraph/mxgraph#499]
I had tried to add Image and put the image url path but its not getting  uploaded  as expected , please find it suggest us. Please refer attachment.
![Capture](https://user-images.githubusercontent.com/53223610/96089225-2752c400-0ee4-11eb-9833-fc6ba8d71fcd.PNG)

**Comment by davidjgraph** [comment]
Please re-structure the question following the guidelines at https://stackoverflow.com/help/how-to-ask, otherwise it will be closed.
