### ISSUE TITLE
Can we integrate mxgraph/mxdraw with  Microsoft Blazor

### ISSUE THREAD

**Issue by sachinpawar13** [jgraph/mxgraph#500]
kindly provide information about integration mxgraph/mxdraw open source tools with Microsoft Blazor Technology.
we want to integrate this tool with blazor please suggest the challenges faced.

**Comment by davidjgraph** [comment]
This is not the place for "write my application". If you have a specific bug report or problem, please submit that following the standard rigour for such reports in software engineering.
