### ISSUE TITLE
Apache License - Clause 4e Modification

### ISSUE THREAD

**Issue by Belisarith** [jgraph/mxgraph#505]
I‘ve got a question regarding the modified clause 4e of Apache 2 license. 
Does this mean, that 
1. this library may not be used to develop apps that integrate into Atlassian Jira or Confluence? 
2. Or does this mean I am not allowed to use Atlassian products as my git repository and not use the Atlassian products for my devops?

` (e) Neither the Work or Derivative Works may be used or form any
          part of a larger work that integrates with Atlassian's Jira
          or Confluence products. This clause continues to apply if
          the naming of Jira and Confluence changes or if they become
          part of a derivative work. This clause continues to apply if
          Altassian is sold or sells one or both of the products. `

**Comment by davidjgraph** [comment]
1 is correct. It's very specific which Atlassian products it refers to and Bitbucket and Bamboo are not in the list.

**Comment by Belisarith** [comment]
@davidjgraph Thank you for the clarification. 
But one last question: Does it mean I am not allowed to use Jira and Confluence in order to manage a project where the mxgraph library is a part of? 
I understand it, that you are not allowed to develop "sub-applications" which are integrated into Jira and Confluence services, thereby enabling the repository owners to develop and market their apps for Jira and Confluence and protecting this market.
But it is allowed to develop apps for other things and use Jira and Confluence to manage my software product.

**Comment by davidjgraph** [comment]
> Does it mean I am not allowed to use Jira and Confluence in order to manage a project where the mxgraph library is a part of?

That's allowed.

**Comment by Belisarith** [comment]
Thank you, that answers my question.
Kind regards.
