### ISSUE TITLE
How to get floating  connection points in mxCell?

### ISSUE THREAD

**Issue by developer3soft** [jgraph/mxgraph#511]
I have connected two mxCells together. How to achive floating connection point on second mxCell where connection has ended.  When I moved this mxCell, connection arrow should change connection to other point

1. Firt scenario
![image](https://user-images.githubusercontent.com/74239201/98657273-f8443c80-2341-11eb-9bf5-3520c8b863e1.png)

2. Second screnario
![image](https://user-images.githubusercontent.com/74239201/98657414-232e9080-2342-11eb-9760-46649acc09bc.png)

**Comment by davidjgraph** [comment]
This repo is being set to read-only.

**Comment by developer3soft** [comment]
So this is correct place to asking a question?
