### ISSUE TITLE
Recent changes EOL - can maintainers please provide the reason for putting this project in End Of Life

### ISSUE THREAD

**Issue by aibcmars** [jgraph/mxgraph#512]
Please provide the explanations to the community

**Comment by davidjgraph** [comment]
We don't want to maintain the project any longer. You are welcome to fork and continue the work.

**Comment by aibcmars** [comment]
OK, thank you for the information

**Anyone** who is **interested in development** please leave the trace - **create PR to the forked repository**:
https://github.com/process-analytics/mxgraph/tree/keep_it_alive
