### ISSUE TITLE
More than 1 color per shape?

### ISSUE THREAD

**Issue by alelordelo** [jgraph/mxgraph#52]
Is it possible to have more than 1 changeable color per shape, like bellow?

https://gyazo.com/cfa2f32ffb36ff0eba67d89b90faae21

**Comment by alelordelo** [comment]
I know not by default... But is there any way to hack it?

**Comment by alderg** [comment]
No this is not possible. Your best solution is writing a plugin to parse the SVG, extract the colors, display a dialog to replace individual colors and write the SVG back.

**Comment by alelordelo** [comment]
Thanks Gaudenz! But this method would open a modal or another window, right? Or should be possible to to change colors from  draw.io toolbar?

**Comment by alelordelo** [comment]
I know

**Comment by alderg** [comment]
Depends on the implementation of the plugin.

**Comment by alelordelo** [comment]
I'm using google's Polymer. Will check with my freelancer, hope it's possible!

Think this one could work?
https://github.com/zeke/get-svg-colors

**Comment by alderg** [comment]
"Designed for use in node, not the browser."

**Comment by alelordelo** [comment]
Ok. Sorry, newbie here....

Does anyone know of such a plugin?
