### ISSUE TITLE
Improvement: include XSD schema for mxGraph XML

### ISSUE THREAD

**Issue by denis60111** [jgraph/mxgraph#6]
#413849085

We'd like to validate mxGraph XML on the server side, and to extend it with our own XML namespace.

The result XML should remain the same for end users, apart from "xmlns" attribute on root node (e.g. no fully qualified namespaces for elements and attributes, just one target namespace).

The schema should be designed to allow extensibility. 

Also, if it is possible, we would like to review proposed XSD before release.

**Comment by alderg** [comment]
XSD would be too generic for validation.
