### ISSUE TITLE
bug mxPrintPreview when specifying a targetWindow in IE

### ISSUE THREAD

**Issue by coclav** [jgraph/mxgraph#60]
The default behaviour of `mxPrintPreview` is to open a new window with `window.open()`

But you can specify your own target window, you can even tell it to be the current window ( `preview.open( myGraph, window)` so that the HTML preview is just added to your current page; to be handled later.

In this scenario there is a bug in IE that can be fixed by editing mxPrintPreview.js line 564 :

`if ( isNewWindow && (mxClient.IS_IE || document.documentMode >= 11 || mxClient.IS_EDGE) )`

if it's NOT a new window, we don't face the issue for which this exception is written.

Hope this helps !

Colin

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
