### ISSUE TITLE
Documentation is hard to read

### ISSUE THREAD

**Issue by GeorgeDewar** [jgraph/mxgraph#61]
Hi there,

This looks like an amazing library - thanks to the maintainer(s) for your work.

I find the documentation and examples pages very hard to read due to the lightweight font and light-grey-on-white colour scheme.

May I suggest changing the font, and/or changing the colour to a darker shade of grey, or to black? In case it's platform-dependent, here's a picture of what it looks like for me on Chrome in Ubuntu:

![image](https://cloud.githubusercontent.com/assets/5344417/23680496/4bdba7e0-03f0-11e7-8571-2ff08e3d8839.png)

**Comment by davidjgraph** [comment]
It is a bit washed out. If you've a good CSS to apply, please feel free to submit a PR.

**Comment by GeorgeDewar** [comment]
Thanks @davidjgraph - I'll send one through shortly :)

**Comment by alderg** [comment]
Thanks for the PR. This will be fixed in the next release.
