### ISSUE TITLE
HTML 5 field types

### ISSUE THREAD

**Issue by nlinnett** [jgraph/mxgraph#64]
I noticed the mxForm class doesn't support any of the new HTML5 field types. I recently had to add a simple patch to use the Number field type.

Would you like me to submit a PR with support for more field types? I would think that the following types would be useful

* date
* email
* number
* tel
* url

**Comment by davidjgraph** [comment]
If these are supported on IE 9+, Chrome 32+, Firefox 38+, Safari 8.0.x, 9.1.x and 10.0.x, Opera 20+, Native Android browser 5.1.x+, the default browser in the current and previous major iOS versions (e.g. 10.x and 9.x) and Edge 23+ , then please feel free to submit a PR.

**Comment by nlinnett** [comment]
As always, IE9 is the sticking point. Most of them are supported in IE10+. 

If it impacts your decision, the failure mode for the non-supported types is supposed to be type="text". However, I don't have an IE9 system available for testing.

For compatibility, I was looking at this page, on the subfeatures tab.
http://caniuse.com/#feat=forms

**Comment by davidjgraph** [comment]
We're setting IE 9 End Of Life 30th June 2017 (Microsoft setting it EOL at the start of June). For a patch now the fallback would need to be tested, otherwise we can take it in July.

**Comment by alderg** [comment]
Try form.addText(name, value).setAttribute('type', type)
