### ISSUE TITLE
yarn add failed for mxgraph@3.7.2-2 but npm install worked

### ISSUE THREAD

**Issue by lupestro** [jgraph/mxgraph#73]
I've just been gearing up to try this out with an Ember app.
I did a fresh "ember init" and did a "yarn add mxgraph". 
Doing an "npm install mxgraph" and then a "yarn install" instead worked.
Not sure what the difference was in the post-processing.
Here's the error I got:

error C:\Users\rmack\Code\Local\Ember\SchematicDesigner2\node_modules\mxgraph: Command failed.
Exit code: 3
Command: C:\WINDOWS\system32\cmd.exe
Arguments: /d /s /c grunt build
Directory: C:\Users\rmack\Code\Local\Ember\SchematicDesigner2\node_modules\mxgraph
Output:
Loading "Gruntfile.js" tasks...ERROR
>> TypeError: Cannot read property 'grunt-contrib-concat' of undefined
Warning: Task "build" not found. Use --force to continue.

Aborted due to warnings.

(I tried attaching my package.json and it wouldn't let me. Let me know what you need and where you need it.)

Versions:
yarn 0.23.2
npm 4.2.0
node 6.10.0

**Comment by lupestro** [comment]
Further fallout... 

It turns out the failing postprocess is called every time I add anything to npm for this project. Since I have a yarn.lock, installs that are invoked via ember-cli end up using yarn, so it becomes impossible to install ember add-ons once this is in place. Every time, I supply an add-on, I have to remove mxgraph, install my add-ons, and then use npm to re-install mxgraph. With yarn widely used, especially on large projects, and getting integrated into infrastructures, this becomes very awkward.

**Comment by davidjgraph** [comment]
I have no idea what any of this means. Someone will have to submit a PR, we won't look at this.

**Comment by lupestro** [comment]
The substance of the issue is that the module installs with "npm install" but not with "yarn install".

If you're not familiar with it, **yarn** is an alternative client for npm. It's a joint project by folks at Facebook, Google, Tilde, and Exponent, folks with huge projects to manage, and is picking up steam in the SPA space. Besides being very fast, it uses a yarn.lock file to ensure that everybody who loads the project is using the same precise versions of everything, bypassing mysterious "it builds for me" issues on project teams. 

It appears I'll have to learn something about grunt, since I'm the one with the itch to scratch here. (We use Ember, which uses broccoli.) I'll have to find out what is different in the post-install task environment on yarn vs. npm that could be affecting the grunt script's ability to run.

**Comment by sergeybashtoviy** [comment]
I have same trouble, I use the angular-cli and packet manager yarn. When you try to add a library, the console throws a similar error. 

> Exit code: 3
Command: C:\WINDOWS\system32\cmd.exe
Arguments: /d /s /c grunt build
Directory: -----absolute path to my project---- \AngularUI\node_modules\mxgraph
Output:
Loading "Gruntfile.js" tasks...ERROR
>> TypeError: Cannot read property 'grunt-contrib-concat' of undefined
Warning: Task "build" not found. Use --force to continue.

>Aborted due to warnings.

I do not know why we get this behavior because I'm new to frontend and js, but the problem really exists. 
Versions:
yarn v0.21.3
npm 3.10.10
node 6.10.1
angular/cli 1.0.0

**Comment by lupestro** [comment]
This can only be happening in the course of processing the line:
require(parentFolderName === "node_modules" ? "load-grunt-parent-tasks" : "load-grunt-tasks")(grunt);
Hence, inside the execution of load-grunt-parent-tasks or load-grunt-tasks. 
So, it has to be originating upstream. Shall I close this?

**Comment by lupestro** [comment]
Found root cause - bug in load-grunt-parent-tasks. If load-grunt-parent-tasks is invoked without options, and you have no 'optionalDependencies', as mxgraph does, the logic fumbles the missing scope. There's a fix in a merge request from over a year ago. I've asked the maintainer to examine and accept the fix. If he follows through, it will probably be 0.1.2.

The workaround is to explicitly specify the scopes you actually use in the second parameter to the call, so:

require(parentFolderName === "node_modules" ? "load-grunt-parent-tasks" : "load-grunt-tasks")(grunt, {scope: 'dependencies'});

I'm still investigating why it behaves differently with npm vs yarn client.

**Comment by mimiflynn** [comment]
@lupestro Any news about this? I've run into the same issue using yarn.

**Comment by alexboyko** [comment]
@mimiflynn as temporary workaround you can install grunt globally: `npm install -g grunt`
