### ISSUE TITLE
Opening local file with name passed by url param

### ISSUE THREAD

**Issue by gabriele92** [jgraph/mxgraph#77]
Hi! How can I open a local file passing the name via urlParam? I tried with this code in index.html but it does not work.

var editor = new EditorUi(new Editor(urlParams['chrome'] == '0', themes));
				
				try
				{
				  editor.open(encodeURI(urlParams['xml']));
				}
				catch (e)
				{
				  mxUtils.error('Cannot open ' + urlParams['xml'] +
				    ': ' + e.message, 280, true);
				} 

Thanks in advance.

**Comment by davidjgraph** [comment]
For usage questions please post to http://stackoverflow.com/questions/tagged/mxgraph. This tracker is more for bugs, suggestions, PRs, etc.
