### ISSUE TITLE
@types/mxgraph ?

### ISSUE THREAD

**Issue by armandosoriano** [jgraph/mxgraph#81]
Hi, do you guys are planning to create typescript module ?

**Comment by davidjgraph** [comment]
We're not typescript users, so no. https://github.com/gooddaytoday/mxgraph-typescript-definitions is community effort, I would encourage everyone interested to try to collaborate in that one place.

**Comment by davidjgraph** [comment]
Actually, the user says the project is dead. Maybe fork it and start an active version.

**Comment by tbouffard** [comment]
For people interested in having mxgraph types, we have started a dedicated community initiative on this topic.
See [mxgraph road to DefinitelyTyped](https://github.com/process-analytics/mxgraph-road-to-DefinitelyTyped)

**Comment by davidjgraph** [comment]
@tbouffard Great idea.
