### ISSUE TITLE
Add rich html content into vertex

### ISSUE THREAD

**Issue by harshajayaweeraXHJ** [jgraph/mxgraph#85]
I need to render complex, custom shape as a vertex. I guess it would be possible to do if vertices can render HTML content since designing with HTML and CSS is easier.

**Comment by alderg** [comment]
Set mxGraph.htmlLabels to true, see https://jgraph.github.io/mxgraph/docs/js-api/files/view/mxGraph-js.html#mxGraph.htmlLabels
