### ISSUE TITLE
Some files in mxgraph distro are not in UTF-8

### ISSUE THREAD

**Issue by zelenij** [jgraph/mxgraph#86]
I honestly cannot claim it is a big issue, but here it goes: some files in the mxgraph distribution, for example mxgraph/docs/js-api/search/VariablesZ.html , are not in UTF-8 encoding.  I am not saying they must be, but it would be great if they were.

My use case - I'm trying to integrate mxgraph into a django application.  Django has an elaborated framework for handling static files.  In particular it executes a post-processing step where it expects (somewhat naively, I agree) all static files (js, css etc) to be in UTF-8, and the above causes it grief.

**Comment by alderg** [comment]
Unfortunately this file is generated, we have no control over the encoding.

**Comment by davidjgraph** [comment]
This is a documentation file, wouldn't it make more sense to just not pull it in at all? Maybe use the pure JS version of mxGraph instead? https://github.com/jgraph/mxgraph-js

**Comment by zelenij** [comment]
Yes, I'll probably do just that, thanks!
