### ISSUE TITLE
How to customize the sidebar when using grapheditor?

### ISSUE THREAD

**Issue by HunterXuan** [jgraph/mxgraph#91]
Hi, I'm trying to use grapheditor in my project about workflow designing. I have met some problems:
1. In the demo of draw.io, I can see "BPMN General" "BPMN Gateways" "BPMN Events", but in grapheditor here is only "BPMN General" available, Is there anyway to use other components?
2. If I want to display some certain shapes, what should i do?

**Comment by mkpasala** [comment]
Why its closed @davedwards ?

**Comment by davidjgraph** [comment]
We ask that StackOverflow type criteria are applied to questions here. You're welcome to ask, but we need basic good process followed so we don't spend hours extracting the right info.

Here, there's 2 questions in one thread, should be split. What format are the shapes to be display in? Are they to be added an existing library or a new one?

Plus, here, there should have been some attempt on something like codepen, to give a reasonable example that could be corrected. This is, as SO would close it for, too broad....

**Comment by davidjgraph** [comment]
Question remains too broad and comprises multiple questions.
