### ISSUE TITLE
mxGraph does not work with bootstrap modal dialog

### ISSUE THREAD

**Issue by cstumpe** [jgraph/mxgraph#92]
I'm trying to use mxGraph with bootstrap, but if the graph is displayed in a modal dialog no edges are displayed on mouse over and you cannot connect the cells

I setup a codepen project for testing, see
[https://codepen.io/codepen-carola/pen/zdpdZq](https://codepen.io/codepen-carola/pen/zdpdZq)

It is adapted from the example "HelloPort"
[https://jgraph.github.io/mxgraph/javascript/examples/helloport.html](https://jgraph.github.io/mxgraph/javascript/examples/helloport.html)

**Comment by davidjgraph** [comment]
I get this on FF, what the matter with it?

![screen shot 2017-08-17 at 09 19 08](https://user-images.githubusercontent.com/1761087/29402567-5bab12f2-832d-11e7-9a8c-e731df0b0fac.png)

**Comment by cstumpe** [comment]
Yes it looks nice, but you cannot create a new connection...

![image](https://user-images.githubusercontent.com/23188563/29403235-0a2b2e0c-8338-11e7-87d2-aef239092b19.png)

**Comment by davidjgraph** [comment]
Errors in the console?

**Comment by cstumpe** [comment]
No, there are no errors in the console. It seems that bootstrap hooks events which are also used by mxGraph?

**Comment by alderg** [comment]
The modal-body has a padding. Try using it as a wrapper as follows:

`<div class="modal-body">
	<div id="graphContainer" style="overflow:hidden;width:100%;height:100%;cursor:default;">
	</div>
</div>`
