### ISSUE TITLE
can any one help to integrate mxGraph with angular 2 application 

### ISSUE THREAD

**Issue by sibaspage** [jgraph/mxgraph#96]

**Comment by nicklemay** [comment]
Have you found any solution? I got the same problem...

**Comment by sibaspage** [comment]
Yes found just copy all the mxgraph plugins into your asset folder it will work.

**Comment by wanted419** [comment]
@sibaspage  can you provide the source code .

**Comment by sibaspage** [comment]
@wanted419 
[https://github.com/sibaspage/mxgraph-with-angular2](https://github.com/sibaspage/mxgraph-with-angular2)

**Comment by asad11111** [comment]
@sibaspage  there are errors in the app. Please do run it. If you resolve the issues do share with us.

**Comment by sibaspage** [comment]
@asad11111 Can you share the error please. i.e screenshot

**Comment by asad11111** [comment]
![capture](https://user-images.githubusercontent.com/22851715/42199596-b8ed091c-7ea8-11e8-951d-765b62f7b50f.PNG)

Could not found " /open " You cannot even export the diagram as an xml,
